### ISSUE TITLE
Not played on ubuntu

### ISSUE THREAD

**Issue by conect** [trizen/youtube-viewer#101]
It doesn't work. I installed via the webupd8 repository.
But it doesn't open any video.

**Comment by trizen** [comment]
Make sure that you have a video player installed, such as MPV or VLC and edit the configuration file (`~/.config/youtube-viewer/youtube-viewer.conf`) to reflect this (`video_player_selected => "mpv"`).

**Comment by conect** [comment]
thx, mpv works vlc(newest repository version) doesn't

**Comment by trizen** [comment]
Install `youtube-dl` as well to play videos with encrypted signatures.

**Comment by conect** [comment]
Does this video work for you https://www.youtube.com/watch?v=xWa8Rf9cBps ?

**Comment by trizen** [comment]
Yes, it does.
![2015-10-12-141035_1920x1080_scrot](https://cloud.githubusercontent.com/assets/614513/10426690/1e9a99ba-70eb-11e5-8dff-6dc2d8b07e4c.png)

**Comment by trizen** [comment]
What happens when you try to play that video?

**Comment by conect** [comment]
nothing i am running ubuntu 14.04

**Comment by trizen** [comment]
Try to install `youtube-dl`, as some videos which use encrypted signatures do not work otherwise.

**Comment by conect** [comment]
already did so but it didn't change anything

**Comment by trizen** [comment]
One other way is letting mpv or vlc to play an YouTube video by URL.

For mpv, change the configuration files to include the following entry inside the `video_players` section:

```perl
mpv_native => {
         arg => "--really-quiet *URL*",
         cmd => "mpv",
         fs => "--fullscreen",
         novideo => "--no-video",
         srt => "--sub-file *SUB*",
},
```
and change the value of `video_player_selected` from `"mpv"` to `"mpv_native"`.

(see also #107 and #109)
