### ISSUE TITLE
403 Forbidden issue

### ISSUE THREAD

**Issue by ahungry** [trizen/youtube-viewer#102]
Similar to this here:
https://github.com/rg3/youtube-dl/issues/6451

I'm getting lots of 403 Forbidden messages - I tried the listed solutions they used (deleting files in ~/.cache) to no avail.

This is with the latest youtube-viewer source under Arch Linux.

**Comment by trizen** [comment]
The version of youtube-viewer from community is a little bit out-of-date. Try to install `youtube-viewer-git` from AUR and also `youtube-dl-git`. (youtube-viewer uses youtube-dl to parse videos with encrypted signatures)

There was an important change regarding the parsing of videos with encrypted signatures in the version 3.0.8, which I guess fixed this issue. I tried all the examples from the youtube-dl issue and everything seems to play correctly.

Also, it's known that mplayer can't handle the HTTPS protocol and it may raise a `403 Forbidden` error. If the error comes from mplayer, try to use mpv instead.

**Comment by ahungry** [comment]
This was resolved by using mpv as recommended (forgot to respond back).
