### ISSUE TITLE
Cubieez

### ISSUE THREAD

**Issue by blauefuesse** [trizen/youtube-viewer#106]
Hi. I currently am running youtube-viewer on Cubietruck with latest Cubieez installed. 
I used Perl 5.22 to build youtube-viewer. I cannot use Mplayer to view videos though. I have tried to edit ~/.configs/youtube-viewer/youtube-viewer.conf to mplayer, with out luck. My ~/.mplayer/config states the following:
 vo=vdpau
vc=ffmpeg12vdpau,ffh264vdpau
fullscreen=yes
quiet=yes
ao=pulse
framedrop=yes
cache=8192
lavdopts=threads=2
ass=no
ass-font-scale=1.4
ass-color=FFFFFF00
ass-border-color=00000000
ass-use-margins=yes
ass-bottom-margin=50
spualign=2
subalign=2
subfont=/usr/share/fonts/TTF/DejaVuSans.ttf
subcp=cp1250

Any clues or experience on what is the issue?

Thanx

**Comment by blauefuesse** [comment]
PS: youtube-dl is installed. mplayer2 is installed. VLC is installed and works. mpv not installed.

**Comment by trizen** [comment]
mplayer is no longer supported, as it can't handle HTTPS streams. Use mpv or vlc instead.

**Comment by blauefuesse** [comment]
Hi. Great news, and not. :-) really liked Mplayer. Just installed MPV .. works fine! Is there a way to have the Terminal hidden, or set not to pop up when a Video is envoked in gtk-youtube-viewer ?

**Comment by blauefuesse** [comment]
PS: Thanx for this great tool !!

**Comment by trizen** [comment]
Hi. You're welcome. Currently, there is no way to hide the terminal, as it allows cancellation of a given task. However, by double-clicking a video result from gtk-youtube-viewer, no terminal will pop up.
