### ISSUE TITLE
no sound from mpv

### ISSUE THREAD

**Issue by myf** [trizen/youtube-viewer#107]
since the new one doesn't seem to support mplayer anymore I switched it to mpv. Then I found that most of the times there's no sound coming out from mpv. I wonder if anyone has the same problem. I have an rc file for mplayer that sets ao=pulse but doesn't really have any specific setting for mpv. I can download the video with :d[number] and play it with mpv from there.

**Comment by trizen** [comment]
One guess: maybe `mpv` misses some codecs for playing webm audio.

Also, make sure that `youtube-dl` is installed and try to delete the configuration files (located in ~/.config/youtube-viewer)

If the problem persists, try to add the following entry to `video_players` inside `youtube-viewer.conf`:

```perl
mpv_native => {
         arg => "--really-quiet *URL*",
         cmd => "mpv",
         fs => "--fullscreen",
         novideo => "--no-video",
         srt => "--sub-file *SUB*",
},
```

and change the value of `video_player_selected` from `"mpv"` to `"mpv_native"`.

**Comment by myf** [comment]
this one seems to work well, thanks!

my old youtube-viewer.conf file has the mpv configured this way
```perl
 mpv => {
                                 arg => "--really-quiet",
                                 audio => "--audio-file '%s'",
                                 cmd => "mpv",
                                 fs => "--fullscreen",
                                 novideo => "--no-video",
                                 srt => "--sub '%s'",
                               },
```

**Comment by trizen** [comment]
Ah, yes. The `sprintf()` format (`%s`) is no longer supported. A few versions ago, it was replaced with special tokens (see: `youtube-viewer -T` for the full list).

An updated config for `mpv` with support for 1080p, would be:
```perl
mpv => {
        arg     => "--really-quiet --title *TITLE*",
        audio   => "--audio-file *AUDIO*",
        cmd     => "mpv",
        fs      => "--fullscreen",
        novideo => "--no-video",
        srt     => "--sub-file *SUB*",
},
```
