### ISSUE TITLE
Running with smplayer

### ISSUE THREAD

**Issue by ufovsalien** [trizen/youtube-viewer#108]
I added smplayer to players list, but smplayer did not support adding external audio as argument. Only from GUI.
All videos except for videos with external audio play fine. If i specify audio as audio=>"*AUDIO*" video will stop working, and only audio will works. But smplayer can play youtube video just by adding youtube url, correctly set Title, and play video itself. Can we add smplayer support?
 smplayer => {
                                       arg => " -close-at-end -media-title *TITLE*",
                                       cmd => "smplayer",
                                       fs  => "-fullscreen",
                                       srt => "-sub *SUB*",

**Comment by trizen** [comment]
Yes. We can use `*URL*` to pass the YouTube URL to SMPlayer.

Example:
```perl
smplayer => {
            cmd => "smplayer",
            fs => "-fullscreen",
            srt => "-sub *SUB*",
            arg => "-close-at-end -media-title *TITLE* *URL*",
},
```

**Comment by ufovsalien** [comment]
Cool. Thanks.
