### ISSUE TITLE
Mplayer idea

### ISSUE THREAD

**Issue by blauefuesse** [trizen/youtube-viewer#109]
Hi. I have been giving the mplayer https issue some thought and came up with that ffmpeg can do https, and youtube-dl can get the vids etc, for example:
mplayer "ffmpeg://$(youtube-dl -f best -g https://www.youtube.com/watch?v=xCxHvNl9MmQ)"
If you do not intent to use this option in future versions, do you have an idea on how to add these lines to /home/USER/.config/youtube-viewer/gtk-youtube-viewer.conf ?
Mplayer is so easy to configure and works just fine on my cubietruck. mpv just sucks, even properly built from source :-/ mpv-build ... 
I would be soo greatful.
Cheers.

**Comment by trizen** [comment]
Hi,

Nice discovery! :-)

To use this with `youtube-viewer`, add the following entry to `video_players` in `~/.config/youtube-viewer/gtk-youtube-viewer.conf`:

```perl
ffmpeg => {
        cmd => "mplayer",
        arg => 'ffmpeg://$(youtube-dl -f best -g *URL*)',
        srt => "-sub *SUB*",
        fs => "-fs",
},
```

and set the value of `video_player_selected` from `"mplayer"` to `"ffmpeg"`.

**Comment by blauefuesse** [comment]
Wow, beautiful !! Thanx :-)

**Comment by blauefuesse** [comment]
It works !! :-) Yes!!
