### ISSUE TITLE
No videos are played with YouTube Viewer 3.1.9

### ISSUE THREAD

**Issue by shibumi** [trizen/youtube-viewer#110]
Hello,
YouTube Viewer 3.1.9 on archlinux is playing no videos. I can choose the video the video is loading for one second and then it's jumping into the 'select a video' menu again. There is no output. mplayer is installed. Do you have any idea how I can debug this better?

**Comment by blauefuesse** [comment]
Hi. Check out this solution:
https://github.com/trizen/youtube-viewer/issues/109

**Comment by trizen** [comment]
Hi shibumi.

For debugging, there is the `--debug` option, but it may not be very useful in this case. Currently, it will just display the command that it will execute to play the video with mplayer. You can copy the command and debug further on your own.

However, it is known that mplayer can't handle HTTPS streams, therefore I would suggest switching to mpv instead.

To use the `mpv` player, open the configuration file (`~/.config/youtube-viewer/youtube-viewer.conf`) and change the value of `video_player_selected` from `"mplayer"` to `"mpv"`.

Additionally, please consider installing `youtube-dl` as well to have support for videos with encrypted signatures.

**Comment by shibumi** [comment]
@blauefuesse 
If I follow your suggestion I get the following error:

```
Use of uninitialized value in join or string at /usr/bin/vendor_perl/youtube-viewer line 3346, <FIN> line 3.
sh: https://r9---sn-i5h7ln7z.googlevideo.com/videoplayback?pl=20&dur=90.965&sver=3&expire=1449344242&gir=yes&mime=video%2Fwebm&itag=248&signature=89C258F89191F2B5DDC659CEC6215F1C481CFCB5.40D18DEA262045BF9EFC8A38A8AA2073CA9EF725&ipbits=0&source=youtube&keepalive=yes&mt=1449322457&mv=m&ms=au&mm=31&mn=sn-i5h7ln7z&key=yt6&clen=24402521&requiressl=yes&lmt=1441957939513571&initcwndbps=1093750&id=o-AG-hXpiyvpL9TUq10vivwbDfW-xzO2_vESmwdOsfwr63&upn=8XvEkcsd9mA&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9407193%2C9408498%2C9408710%2C9415949%2C9416126%2C9416495%2C9417683%2C9418401%2C9419451%2C9420452%2C9420716%2C9421097%2C9422521%2C9422596%2C9422618%2C9423629%2C9423643%2C9423662%2C9423992%2C9424088%2C9424388%2C9424980&ip=88.71.86.140: No such file or directory
```
