### ISSUE TITLE
doesnt play with mplayer

### ISSUE THREAD

**Issue by Joseph65** [trizen/youtube-viewer#111]
im using gtk-youtube-viewer
doesnt play with mplayer
it plays fine with mpv
and the only reason to use mplayer instead of mpv its because is faster to play.

**Comment by blauefuesse** [comment]
Hi. Check this solution out. You ffmpeg or avconv though: https://github.com/trizen/youtube-viewer/issues/109

**Comment by trizen** [comment]
Unfortunately, mplayer is no longer supported by youtube-viewer as it can't handle HTTPS URLs.

A workaround this issue (found by @blauefuesse in #109) is to combine mplayer with ffmpeg and youtube-dl, resulting into:

```perl
ffmpeg => {
        cmd => "mplayer",
        arg => 'ffmpeg://$(youtube-dl -f best -g *URL*)',
        srt => "-sub *SUB*",
        fs => "-fs",
},
```

The above code needs to be placed into `~/.config/youtube-viewer/gtk-youtube-viewer.conf` inside the `video_players` section. After that, change the value of `video_player_selected` from `mplayer` to `ffmpeg`, so it will look like this:

```perl
...
  video_player_selected  => "ffmpeg",
  video_players          => {
        ffmpeg => {
                cmd => "mplayer",
                arg => 'ffmpeg://$(youtube-dl -f best -g *URL*)',
                srt => "-sub *SUB*",
                fs => "-fs",
        },
},
...
```

**Comment by trizen** [comment]
Adding `--no-ytdl` to the mpv command, makes it to load just as fast as MPlayer (https://github.com/trizen/youtube-viewer/commit/ec6899940ae9c76f779e93e1a510f6c50105a31e). Additionally, the support for MPlayer is back in 3.2.1 https://github.com/trizen/youtube-viewer/commit/077a952a9e3b24f0842a6e3449c0d0a62e184362. This assumes that ffmpeg is compiled with support for the HTTPS protocol.
