### ISSUE TITLE
Request: List Information with less Info

### ISSUE THREAD

**Issue by blauefuesse** [trizen/youtube-viewer#113]
I am looking at the option :i(nfo)=i,i   and this option spits out a lot of info.
Is there a listing option to list lesser information, i.e. something like this:
:turl=i,i   # Show only info -> Title and URL

Cheers and greets from Berlin
PS: this option request applies to youtube-viewer

**Comment by trizen** [comment]
There isn't currently any option for, unfortunately, but here's a trick to achieve something similar:

* start youtube-viewer with the following argument: `--extract='*TITLE*\n*URL*'`
* search for something and select a result

Now, instead of playing, youtube-viewer will only list the title and the url of the selected result. To actually play something, you'll need to say `:play=n` (which currently is broken, but I'm going to fix it in a moment).

**Comment by blauefuesse** [comment]
Thanx a million ;-)

**Comment by trizen** [comment]
You're welcome. Also, checkout the `--confirm` option, which may be useful to pair it with `--extract`.

**Comment by blauefuesse** [comment]
Hi! 
Is there a way to save search results found when using: youtube-viewer --extract='*TITLE*\n*URL*'  to a file for example in /tmp ?
Need the URLs for further use in a separate tool.
Greats from Berlin.
Cheers

**Comment by blauefuesse** [comment]
Good morning!
Here is an Example of what i want to achieve. 
![url-ytdl](https://cloud.githubusercontent.com/assets/14938400/14201329/786bb6ee-f7f1-11e5-8bb5-fa771be6c0a4.png)
I have a small bash script at the moment that i want to translate to python/gtk to download videos to .webm (video) or .webm (audio), last to be then converted to .ogg, with the help of youtube-dl and 
" youtube-viewers --extract='*TITLE*\n*URL*'  " option.
Cheers

**Comment by trizen** [comment]
Hi, blauefuesse.

I just added the `--extract-file=s` option, which should do the trick.
Example: `youtube-viewer slayer --extract='*TITLE*\n*URL*' --extract-file=info.txt`

For each selected video, it will append the extracted info into `info.txt`.

To automatically extract all the information for all 20 results, just add the option `--std-input=1..20`

Cheers. :)

**Comment by blauefuesse** [comment]
grand! the weather is soo beautiful today, i'll try it later. thanx :-)

**Comment by trizen** [comment]
Hehe, same here. The long awaited summer is almost here. You're welcome. :)
