### ISSUE TITLE
Cannot play from a video onwards...

### ISSUE THREAD

**Issue by beanaroo** [trizen/youtube-viewer#114]
Maybe I'm daft but I've been trying to figure it out for quite some time now.

I load up a playlist, it's a few pages long. I would like to play from a specific video onwards.
Is there a way to achieve this?

Something like `:play=17+ :anp` in user input mode or `--pp=s --start-video=37`in command line mode.

**Comment by trizen** [comment]
Hi beanaroo,

Currently this is not possible, but it's a nice feature request which will be added very soon.

Thanks!

**Comment by trizen** [comment]
The support for unbounded ranges has been added successfully.

In user input mode, the syntax is: `17..`, which will play all the videos, starting with the 17th video from the current page. (`:anp` is implied)

In command-line mode, `--pp=s --results=50 --std=input=37..` will do the same as above. One thing to take into account it's the fact that `37` is relative to the current page. For example, if `--results=20`, then we need to specify `--page=2`, and `--std-input=17..`, which will play the videos starting with the 37th absolute result.

A simpler hack in the command-line mode would be `--pp=s --results=1 --page=100`, will start playing all the videos, starting with the 100th result.

**Comment by beanaroo** [comment]
Goodness! I did not expect such a response. Tested and it works wonderfully. My German and Coding lessons are now streamlined. Allow me to purchase you a beverage.

Feel free to close this issue if complete.

**Comment by trizen** [comment]
Thank you :)
