### ISSUE TITLE
WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later.

### ISSUE THREAD

**Issue by leoj3n** [trizen/youtube-viewer#115]
Getting this error when launching GTK version from command line (on OS X):

~~~
2016-02-15 18:48:02.695 perl5.23.7[37332:186876] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
~~~

Looks related to:

https://github.com/ariya/phantomjs/issues/11612

But not sure how they "solved" the issue.

**Comment by trizen** [comment]
Not an `youtube-viewer` issue. The warning is triggered deep from the gtk2 system library (namely, from the `gdk/quartz/gdkscreen-quartz.c` source file).

See: 
* https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSScreen_Class/#//apple_ref/occ/instm/NSScreen/userSpaceScaleFactor
* http://fossies.org/linux/gtk+/gdk/quartz/gdkscreen-quartz.c#79

**Comment by leoj3n** [comment]
Very interesting, thanks @trizen
