### ISSUE TITLE
Error building gtk-youtube-viewer

### ISSUE THREAD

**Issue by CocoCocoAlx** [trizen/youtube-viewer#116]
Everything OK at clone the repository, all OK to install the program, but when seeking a video on Youtube, whenever pressed a key occurs an error that says: Can't locate object method "get_text" via package "Glib::Object::_Unregistered::GtkEntryBuffer" at ~/perl5/bin/gtk-youtube-viewer line 476. I don't know how to resolve that. Also, the videos can be viewed but can not be downloaded.

System: Ubuntu 12.04.5, all updated.

**Comment by trizen** [comment]
I suspect it's something wrong with perl-gtk2 package. Try to reinstall it or build the latest version from CPAN (`cpan Gtk2`)

Alternatively, try to install youtube-viewer from:

```console
sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get install youtube-viewer
```

Regarding the downloading of videos, a terminal is required which needs to be specied in the configuration. Also, `youtube-viewer` must exist in the `$PATH`.

**Comment by CocoCocoAlx** [comment]
I've reinstalled the libgtk2-perl through apt-get, but still got that error. On the other hand, this is that I get when execute cpan Gtk2:

CPAN: Storable loaded ok (v2.27)
Going to read '/home/ivanaty32/.cpan/Metadata'
  Database was generated on Wed, 17 Feb 2016 03:17:02 GMT
Running install for module 'Gtk2'
Running make for X/XA/XAOC/Gtk2-1.2498.tar.gz
CPAN: Digest::SHA loaded ok (v5.61)
CPAN: Compress::Zlib loaded ok (v2.033)
Checksum for /home/ivanaty32/.cpan/sources/authors/id/X/XA/XAOC/Gtk2-1.2498.tar.gz ok
CPAN: File::Temp loaded ok (v0.22)
CPAN: Parse::CPAN::Meta loaded ok (v1.4405)
CPAN: CPAN::Meta loaded ok (v2.120351)
CPAN: Module::CoreList loaded ok (v2.59)
---- Unsatisfied dependencies detected during ----
----          XAOC/Gtk2-1.2498.tar.gz         ----
    Glib [build_requires]
Running make test
  Make had some problems, won't test
  Delayed until after prerequisites
Running make install
  Make had some problems, won't install
  Delayed until after prerequisites
Running install for module 'Glib'
Running make for X/XA/XAOC/Glib-1.321.tar.gz
Checksum for /home/ivanaty32/.cpan/sources/authors/id/X/XA/XAOC/Glib-1.321.tar.gz ok

  CPAN.pm: Going to build X/XA/XAOC/Glib-1.321.tar.gz

Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-2.0' found
 at Makefile.PL line 58.
*** can not find package gobject-2.0 >= 2.0.0
*** check that it is properly installed and available in PKG_CONFIG_PATH
 at Makefile.PL line 58.
No 'Makefile' createdCPAN: YAML loaded ok (v0.77)
  XAOC/Glib-1.321.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- NOT OK
Running make test
  Make had some problems, won't test
Running make install
  Make had some problems, won't install
Running make for X/XA/XAOC/Gtk2-1.2498.tar.gz
Warning: Prerequisite 'Glib => 1.280' for 'XAOC/Gtk2-1.2498.tar.gz' failed when processing 'XAOC/Glib-1.321.tar.gz' with 'writemakefile => NO -- No 'Makefile' created
'. Continuing, but chances to succeed are limited.

  CPAN.pm: Going to build X/XA/XAOC/Gtk2-1.2498.tar.gz

Glib version 1.280 required--this is only version 1.241 at /usr/share/perl/5.14/Exporter/Heavy.pm line 106.
BEGIN failed--compilation aborted at (eval 12) line 1.

Checking if your kit is complete...
Looks good
MakeMaker FATAL: prerequisites not found.
    Glib 1.280

Please install these modules first and rerun 'perl Makefile.PL'.
Warning: No success on command[/usr/bin/perl Makefile.PL INSTALLDIRS=site]
  XAOC/Gtk2-1.2498.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- NOT OK
Running make test
  Make had some problems, won't test
Running make install
  Make had some problems, won't install
Could not read metadata file. Falling back to other methods to determine prerequisites.

I must run this as root? How I upgrade my GLib, if this was necessary?

**Comment by trizen** [comment]
```
No package 'gobject-2.0' found
at Makefile.PL line 58.
*** can not find package gobject-2.0 >= 2.0.0
```

**Comment by CocoCocoAlx** [comment]
Working! The libcairo-gobject-perl don't appears to exist, but I have installed the libcairo-gobject2 package on my system. I've installed the libglib2.0-dev, lsb-build-desktop3, python-gobject-2-dev and libcairo-gobject2 packages too, and run cpan Gtk2 again. I'm no longer having the problem with the keys, but now when I want to download a video, tells me that there was a problem creating the child process and the path to youtube-viewer program - ~/perl5/bin/youtube-viewer - does not exist (and it is true, it does not exist). How I can do to add that? Many thanks for the help! Greetings!

**Comment by trizen** [comment]
Open the configuration file of gtk-youtube-viewer (`~/.config/youtube-viewer/gtk-youtube-viewer.conf`) and change the value of `youtube_viewer` to the absolute path where `youtube-viewer` is installed.

Example:
```perl
  youtube_viewer => "/usr/bin/youtube-viewer",
```

If youtube-viewer exists in the `$PATH`, you can specify only its name, as:

```perl
  youtube_viewer => "youtube-viewer",
```
