### ISSUE TITLE
important not to install mpv from repo with Ubuntu

### ISSUE THREAD

**Issue by 22csnyder** [trizen/youtube-viewer#117]
Here is the message I was going to submit. I have fixed the problem but I think someone may ask you something similar in the future:

> To get it to work I had to go to preferences and change for the mpv player
> "--audio-file"  and   "--sub-file"
> to
> "--audiofile" and "--sub"
> 
> I would get an "error parsing commandline option" error otherwise, and "audio-file" and "sub-file" have no hits in the man pages for mpv.

It turns out the the problem is that the mpv version available in Ubuntu via apt-get is very old. I was also getting some strange VDPAU errors, though the audio would work after I made the corrections I mentioned above. After working on it this morning, it seems critical to NOT [install via apt-get](http://www.webupd8.org/2015/02/youtube-viewer-complete-youtube-client.html)
but instead to follow these instructions [here](https://github.com/mpv-player/mpv-build#instructions-for-debian-and-ubuntu)

**Comment by tukoz** [comment]
Alternatively use one of these

- Alin Andrei PPA: http://ppa.launchpad.net/nilarimogard/webupd8/
- Has latest mpv: http://ppa.launchpad.net/mc3man/mpv-tests/
- Has latest ffmpeg-3: http://ppa.launchpad.net/jonathonf/ffmpeg-3/
- Has latest (s)mplayer: https://launchpad.net/~rvm

These are well-known personal repositories; allow one to update to the latest versions straight from `apt` / `synaptic` / whatever (s)he uses.
