### ISSUE TITLE
how to: convert directly to mp4

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#118]
Hello Trizen,

thanks again for your super application! 

one question: 

how can modify .conf to make ffmpeg convert files when downloading  for example .webm content directly to mp4?

thanks

rich

**Comment by trizen** [comment]
Hi Rich,

You're very welcome. I'm glad you find it useful.

To automatically convert any downloaded file to mp4, set the configuration option `convert_to` from `undef` to `'mp4'`, like this:

```perl
  convert_to => 'mp4',
```

Cheers!

**Comment by mrkapqa** [comment]
Wow thanks Daniel so easy it Workshop wonders

Von meinem iPad gesendet

**Comment by mrkapqa** [comment]
Hello Daniel,

on OsX it does not find ffmpeg

     sh: ffmpeg: command not found

although i installed ffmpeg via MacPorts and it is executable in terminal.

downloaded a binary ffmpeg too but don't know how to bind it into 
youtube-viewer.


Thanks


Am 4/2/16 um 8:27 PM schrieb Daniel Șuteu:

**Comment by trizen** [comment]
Hi Rich,

Try to replace "ffmpeg" in the value of `convert_cmd`, with the absolute path to ffmpeg or the output of:

* `which ffmpeg`

Example:
```perl
convert_cmd  => "/usr/bin/ffmpeg -i *IN* *OUT*",
```

**Comment by mrkapqa** [comment]
daniel i installed ffmpeg with Homebrew and now its definitely 
functioning :)

isn't it possible to download directly as mp4?

can do that for example with greasemonkey + viewtube script by isebaro


thanks



Am 4/3/16 um 1:05 PM schrieb Daniel Șuteu:

**Comment by trizen** [comment]
Currently, there is no explicit way to tell youtube-viewer to prefer mp4 over webm, but I consider this is as a feature request.

However, there is an hack around this, involving `youtube-dl`:

* add in the configuration file the following entry in the `video_players` section:

```perl
mp4dl => {
           arg => "-f mp4 *URL*",
           cmd => "youtube-dl",
         },
```

* then execute youtube-viewer with the following argument: `--player=mp4dl`

Example:

```shell
$ youtube-viewer --player=mp4dl linux videos
```

Now, each selected video, instead of being played, will be downloaded in MP4 format with `youtube-dl`.

**Comment by mrkapqa** [comment]
now i can import directly into itunes and stream via homesharing / via 
bluetooth from to my ipad :)

Am 4/3/16 um 2:24 PM schrieb Daniel Șuteu:

**Comment by mrkapqa** [comment]
Hello Daniel,

can i also download directly into mp3?
it seems not to work with convert_cmd ffmpeg
   and                      convert_to "mp3"

thanks

richie

Zitat von Daniel Șuteu <notifications@github.com>:

**Comment by trizen** [comment]
Hi Richie,

Yes, this should be possible, using the `convert*` options, assuming `ffmpeg` is installed:

`$ youtube-viewer -d --convert-cmd='ffmpeg -i *IN* *OUT*' --convert-to=mp3`

Alternatively, this can be done by using a similar trick as above, by adding the following entry in `~/.config/youtube-viewer/youtube-viewer.conf`:

```perl
mp3dl => {
           arg => "--extract-audio --audio-format mp3 *URL*",
           cmd => "youtube-dl",
         },
```

...and executing youtube-viewer as:

`$ youtube-viewer --player=mp3dl linux videos`

Let me know if this works for you.

Regards,
Trizen

**Comment by mrkapqa** [comment]
hello daniel,

hope you are well.
i am back on linux - debian jessie - and found out that youtube-viewer 
is not so more good working with mpv as on wheezy -
i used to compile mpv on wheezy and afterwards install youtube-viewer 
and on wheezy i nearly never had problems after ifound out how to do that -
but today a program 4k downloader did not start so i tried to upgrade to 
jessie and trouble started with youtube-viewer.
mostly, after watching one video, the next searches wont show up or thd 
search tag wont be displayed and if i select number to play - nada.
also - the playback would stop if i skip forward (when playing the first 
sucessful result).
so i installed mpv from repo - problem solved, apparently.
problem came back soon - so i removed mpv - and made a fresh compile of 
mpv / according to the github suggestions. so mpv seems stable - i can 
skip through a track withouth problems.
could it be that due the fact that on wheezy i installed youtube-viewer 
via your wheezy.deb ... that this is not really compatible with jessie? 
i tried then to remove that deb and removed quite some perl packages 
that i am now missing and probably they are the cause for the 
misbehaviour? altough i compiled the new 3.2.4 that did not give me that 
packages back - and when i tried to reinstall 3.1.5. via the deb i just 
got installed one additional package but when i removed it previously 
there were 8-10 removed. could you please indicate the probable 
candidates so that i can re-install them manually to see if that solves 
the problem?
Otherwise i would have to reinstall wheezy and stick with it because i 
like your program so much !!!
thanks!

Daniel Șuteu wrote:

**Comment by mrkapqa** [comment]
Hello Daniel,

just forget my email,
i will startanew from wheezy tomorrow.
mpv is misbehaving again - i think wheezy will fit better the x220tablet 
from lenovo (very nice machine!)

thank you and good night

Daniel Șuteu wrote:
