### ISSUE TITLE
Contradictory license statements

### ISSUE THREAD

**Issue by UnitedMarsupials** [trizen/youtube-viewer#121]
The `share/gtk-youtube-viewer.glade` says:

> Written in Perl, Gtk2 and Glade under the **GPLv3**.

But `META.yml` says:

> `license:` **perl**

So, is gtk-youtube-viewer released under Perl's [Artistic License](http://dev.perl.org/licenses/artistic.html), or GNU Public License? Whichever it is, it would be better for the sources to agree... Thank you!

**Comment by trizen** [comment]
(gtk-)youtube-viewer is (and will always be) dual-licensed under the Artistic License and the GNU Public License, at your own choice. This has been now made clear in all its source files.

The `perl` license from `META.yml` means the following:

> The distribution may be copied and redistributed under the same terms as Perl itself (this is by far the most common licensing option for modules on CPAN). This is a dual license, in which the user may choose between either the GPL or the Artistic license.
