### ISSUE TITLE
gtk-youtube-viewer can not launch due to "Can't call method "set_active" " error

### ISSUE THREAD

**Issue by kensully** [trizen/youtube-viewer#125]
Hi,
First of all thank you for maintaining such a tool, it's very useful.
I am on Ubuntu 14.04.5 platform. Last year I installed and used `gtk-youtube-viewer`. Today I cloned this repo an reinstalled it. But it won't launch.

       $ /usr/bin/gtk-youtube-viewer
       [WARN] undefined object: comboboxtext8
       [WARN] undefined object: comboboxtext4
       [WARN] undefined object: comboboxtext9
       [WARN] undefined object: playlists_checkbox
       [WARN] undefined object: comboboxtext1
       [WARN] undefined object: comboboxtext7
       [WARN] undefined object: spinbutton3
       [WARN] undefined object: channel_name_save
       [WARN] undefined object: channel_id_save
       [WARN] undefined object: comboboxtext6
       [WARN] undefined object: comboboxtext13
       [WARN] undefined object: panel_user_entry
       [WARN] undefined object: comboboxtext3
       [WARN] undefined object: comboboxtext2
       [WARN] undefined object: channels_checkbox
       [WARN] undefined object: dash_checkbutton
       [WARN] undefined object: audio_only_checkbutton
       [WARN] undefined object: comboboxtext5
       [WARN] undefined object: videos_checkbox
       [WARN] undefined object: clear_list_checkbutton
       [Sat Oct  8 16:20:34 2016]: Can't call method "set_active" on an undefined value at /usr/bin/gtk-youtube-viewer line 749.
       Can't call method "set_active" on an undefined value at /usr/bin/gtk-youtube-viewer line 749.

How can I fix it?

Regards.
Kenn

**Comment by trizen** [comment]
Hi. I'm glad you find youtube-viewer useful.

From the error message, it seems that the file `gtk-youtube-viewer.glade` is located incorrectly. The problem may be related to the Perl directory where the libraries of (gtk-)youtube-viewer are installed. A possible fix would be to execute:

```shell
perl -MFile::ShareDir=dist_dir -E 'say dist_dir("WWW-YoutubeViewer")'
```

...and delete the directory that is printed by the above command.

**Comment by kensully** [comment]
Thanks a lot, that works! 

It's related to previous installation path, because 
      
     perl -MFile::ShareDir=dist_dir -E 'say dist_dir("WWW-YoutubeViewer")' 

printed 

    /usr/local/share/perl/5.18.2/auto/share/dist/WWW-YoutubeViewer

After I removed that directory it runs now.
Best regards.
