### ISSUE TITLE
Unable to play a video from youtube

### ISSUE THREAD

**Issue by blansky** [trizen/youtube-viewer#126]
> open('.cache/youtube-viewer/d03b50cf18f60e477b0e9152a7dd10bb', 'w'): Permission denied at /usr/local/lib64/perl5/5.22.2/WWW/YoutubeViewer.pm line 309.

I have this error each time I try to play a video.
The system i am using is gentoo.
I tried to install it from the official repos, but it was not working (i had  no video, and no error).
So I tried to install it from the source (git clone from github), now I am getting this error.

Any help will be appreciated.

H.

**Comment by trizen** [comment]
The cache directory seems to not be writable. Try to change it to another directory (such as `/tmp/`) on which you have writable permissions.

The configuration files are:

* `~/.config/youtube-viewer/youtube-viewer.conf`
* `~/.config/youtube-viewer/gtk-youtube-viewer.conf`

Change the `cache_dir` config value to:

```perl
cache_dir => "/tmp/youtube-viewer",
```

**Comment by blansky** [comment]
thanks you,

I am not getting the error above anymore, but i am still not getting any video.
I tried the to launch the application with the command below  
youtube-viewer --player=mpv --debug

I am getting this 

> -> Resolution: 720
> -> Video itag: 22
> -> Video type: video/mp4;+codecs="avc1.64001F,+mp4a.40.2"
> -> Command: /usr/bin/mpv --really-quiet --title Donald\ Trump\ Asks\ The\ Terminally\ Ill\ For\ A\ Huge\ Favor https\:\/\/r2\-\-\-sn\-oxq5u55\-cage\.googlevideo\.com\/videoplayback\?initcwndbps\=628750\&lmt\=1476015354926355\&pcm2cms\=yes\&expire\=1476038143\&requiressl\=yes\&mime\=video\%2Fmp4\&ipbits\=0\&ratebypass\=yes\&sparams\=dur\%2Cei\%2Cid\%2Cinitcwndbps\%2Cip\%2Cipbits\%2Citag\%2Clmt\%2Cmime\%2Cmm\%2Cmn\%2Cms\%2Cmv\%2Cpcm2cms\%2Cpl\%2Cratebypass\%2Crequiressl\%2Csource\%2Cupn\%2Cexpire\&upn\=cpzpRSNQvw8\&itag\=22\&id\=o\-AAX8AP6S4gQYvF\-dxj3xcyXXz3W8PESQNlhBxuLlbTcJ\&ei\=njn6V_2VOs78oQOinKbIDg\&ms\=au\&mt\=1476015997\&mv\=m\&dur\=534\.685\&source\=youtube\&pl\=24\&ip\=202\.38\.182\.4\&key\=yt6\&signature\=2451682B98181AB0557C1BD864444211C3EDEE55\.3448ECB07523A05F173079384FD85A6B577F9BBF\&mm\=31\&mn\=sn\-oxq5u55\-cage
> 

,and no video.
...

**Comment by trizen** [comment]
Is `mpv` installed?

**Comment by blansky** [comment]
yes, it is

> mpv 0.20.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
>  built on UNKNOWN
> ffmpeg library versions:
>    libavutil       54.31.100
>    libavcodec      56.60.100
>    libavformat     56.40.101
>    libswscale      3.1.101
>    libavfilter     5.40.101
>    libswresample   1.2.101
> ffmpeg version: 2.8.6
> 
>

**Comment by trizen** [comment]
Hmm. That's strange. Probably `https` support was not enabled on ffmpeg/mpv when it was built? (I'm just guessing).

I tried the command from your debug output and it works correctly here. Try to execute the same command locally, but first removing the "--really-quiet" option, to see what is really going on.

**Comment by blansky** [comment]
Thank you,
It`s working great after recompiling ffmpeg with openssl, gnutls enable.
