### ISSUE TITLE
not available on ppa anymore??

### ISSUE THREAD

**Issue by nuentoter** [trizen/youtube-viewer#127]
nuentoter@broke:~$ sudo apt-get install youtube-viewer
[sudo] password for nuentoter: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package youtube-viewer
nuentoter@broke:~$ 

i did add the web8 ppa

**Comment by trizen** [comment]
As far as I know, the PPA is still available. 

```console
sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get install youtube-viewer
```

See (at the bottom of the page): https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8/+index?batch=75&direction=backwards&start=450

**Comment by nuentoter** [comment]
yakkity is not in ppa yet, just got around to browsing webup8 directory

**Comment by nuentoter** [comment]
Built from git with lubuntu Yakkity and works like a charm!

**Comment by JuPlutonic** [comment]
Alin, can you update PPAs youtube-viewer to 0.3.8 and say if Y.V. works with Ubuntu's build-in perl?
