### ISSUE TITLE
simple terminal

### ISSUE THREAD

**Issue by ubone** [trizen/youtube-viewer#128]
Please include [st](http://st.suckless.org/) support for youtube-viewer.

**Comment by ubone** [comment]
recreated .config/youtube-viewer/gtk-youtube-viewer.conf has `terminal_exec => "-e '%s'",` instead of `terminal_exec => "-e %s",` which returns `child finished with error '256'`

**Comment by Narrat** [comment]
Could be a case for termite too, but I need to further look into that. (Having issues with termite and gtk-youtube-viewer).
One question though (without taking a deep look at the source). The terminal emulator discovery is done by exact matching? the string termit just checks for termit and not termite?

**Comment by trizen** [comment]
@Narrat - the terminal emulator discovery is done by using a predefined list of common terminal emulators. First terminal emulator from this list which is installed (i.e.: exists in `$PATH`) will be used by `gtk-youtube-viewer` as the default terminal. However, it can be changed later in the configuration file.

Here is the actual code: https://github.com/trizen/youtube-viewer/blob/master/bin/gtk-youtube-viewer#L694

Currently, `gtk-yotutube-viewer` does not check for `termite`; only for `termit`.
