### ISSUE TITLE
Is it possible to automatically play a video from related videos after video like in youtube?

### ISSUE THREAD

**Issue by fuloating** [trizen/youtube-viewer#130]
Hey,

I am wondering if it is some way possible to automatically play a video from related videos after video has played like on youtube website?

**Comment by trizen** [comment]
Automatically is not possible, but it's quite easy to it manually; after a search, inserting `:r=n -A` (where `n` is the number of a video), youtube-viewer will play all the related videos of the selected video `n`.

**Comment by fuloating** [comment]
cool thanks! I did 3 :r=3 -A and had it play the third track from search and then play its related list (i guess) after that. 

This is another thing but next thing I tried to look up if it is possible to go backwards and play the previous video I had just played, but I guess that comes too complicated. Seems I can play the next track by closing the video player but yeah..

**Comment by trizen** [comment]
Closing the player with CTRL+C, disables the `-A` option (works only with mpv and mplayer) and we can return back to the search results with the `:r` command. (in some cases, `:r` needs to be inserted twice)
