### ISSUE TITLE
Videos lose connection when pausing for a long time

### ISSUE THREAD

**Issue by eazar001** [trizen/youtube-viewer#132]
I'm not sure if this is expected behavior or not, but I notice that if I leave a video paused for a long time (i.e. > 10 minutes or so), the connection appears to drop so that when I resume playback, it will play for a few seconds and the video will terminate prematurely.

Is this expected behavior? If I can aid with debug logs or anything, let me know.

**Comment by trizen** [comment]
This is a known mplayer issue. It has been fixed in mpv.

**Comment by eazar001** [comment]
Thank you, changing the selected player to mpv worked just fine for me.
