### ISSUE TITLE
how to build --gtk on Mac?

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#136]
Hello , 

i successfully installed youtube-viewer on a macpro 4.1 with snow leopard (yay!!!) thanks to wonderful guys @macports who helped with proper options for mpv 

had to build with
sudo port install mpv
+audiocd+bundle+dvd+libarchive+network+opengl+osd+python27+rubberband+x11

then evoke mpv with
mpv --opengl-backend=x11

now i am wondering how to get youtube-viewer-gtk on the mac working cause i would like to sort videos properly and the gtk-version is more suitable therefore.

thanks - multumesq!

**Comment by trizen** [comment]
Hi,

First, you need the Gtk2 library (see: https://www.gtk.org/download/macos.php):
```console
brew install gtk+
```

then you can install (gtk-)youtube-viewer by executing:

```console
perl Build.PL --gtk
./Build installdeps
./Build test
sudo ./Build install
```

**Comment by mrkapqa** [comment]
thanks daniel,

i did already sudo port install gtk2

and install youtube-viewer with --gtk


but did not know yet how to evoke it as

gtk-youtube-viewer


:)

**Comment by trizen** [comment]
You're welcome. :)

**Comment by mrkapqa** [comment]
daniel, somehow the sorting "by: date" are not exact i think. 

how could i pass exacter sorting options for youtube-viewer?

for example, sort all videos from channel according to date
                    sort videos eg. "stewart swerdlow" by date

thanks

**Comment by trizen** [comment]
For youtube-viewer:

```console
youtube-viewer -u=stewartswerdlow
```

The results are automatically sorted by date (latest videos appear first).

The same thing can be achieved in gtk-youtube-viewer by switching to the "Channel" tab, changing the "Channel type" to "username" (at the bottom-right). Then, you can insert `stewartswerdlow` in the "Uploads" text-entry and press ENTER. This will display the latest videos from "stewartswerdlow".

Alternatively, if you want to search in the videos on a given channel and also sort them by date, you can say (in youtube-viewer):

```console
youtube-viewer --author=stewartswerdlow --order=date [keywords]
```

Same thing in gtk-youtube-viewer can be achieved by specifying a value for "From author" in the "Search" tab, which is the channel ID or the channel username, then selecting the "date" value for "Order by".

**Comment by mrkapqa** [comment]
hello Daniel,

hope you are well.

I am trying to install youtube-viewer on my Windows computer.


please see the error -

can you please indicate how to install via CPAN readline?

i tried but failed.


also installed ReadLine via Cygwin but somehow did not work as "Build 
installdeps" still searches for it.


thank you very much,

richard

Am 03.02.2017 um 21:31 schrieb Daniel Șuteu:
