### ISSUE TITLE
videos not opened in jessie with mpv-build

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#137]
hello daniel,

i have problem with youtube-viewer on jessie 64bit

videos just dont open; i have installed youtube-dl and the required packages i think

!/usr/bin/perl

# Youtube Viewer 3.2.5 - configuration file

our $CONFIG = {
  auto_captions           => 0,
  autohide_watched        => 0,
  cache_dir               => "/home/rich/.cache/youtube-viewer",
  captions_dir            => "/tmp",
  cats_region             => "us",
  clobber                 => 0,
  colors                  => 1,
  combine_multiple_videos => 0,
  confirm                 => 0,
  convert_cmd             => "ffmpeg -i *IN* *OUT*",
  convert_to              => undef,
  copy_caption            => 0,
  dash_mp4_audio          => 1,
  dash_support            => 1,
  debug                   => 0,
  download_and_play       => 0,
  download_in_parallel    => 0,
  download_with_wget      => 0,
  downloads_dir           => ".",
  fat32safe               => 0,
  fullscreen              => 0,
  get_captions            => 1,
  get_term_width          => 1,
  highlight_color         => "bold",
  highlight_watched       => 0,
  history                 => 0,
  history_file            => "/home/rich/.config/youtube-viewer/history.txt",
  history_limit           => 10000,
  hl                      => "en_US",
  http_proxy              => undef,
  interactive             => 1,
  keep_original_video     => 0,
  maxResults              => 20,
  order                   => undef,
  page                    => 1,
  publishedAfter          => undef,
  publishedBefore         => undef,
  remove_played_file      => 0,
  resolution              => "original",
  results_fixed_width     => 0,
  results_with_colors     => 0,
  results_with_details    => 0,
  safeSearch              => undef,
  skip_if_exists          => 0,
  srt_languages           => ["en", "es"],
  subscriptions_order     => "relevance",
  thousand_separator      => ",",
  video_filename_format   => "*FTITLE*.*FORMAT*",
  video_player_selected   => "mpv_native",
  video_players           => {
                               mplayer => {
                                 arg => "-prefer-ipv4 -really-quiet -title *TITLE*",
                                 audio => "-audiofile *AUDIO*",
                                 cmd => "mplayer",
                                 fs => "-fs",
                                 novideo => "-novideo",
                                 srt => "-sub *SUB*",
                               },
                               mpv => {
                                 arg => "--really-quiet --title *TITLE* --no-ytdl",
                                 audio => "--audio-file *AUDIO*",
                                 cmd => "/usr/local/bin/mpv",
                                 fs => "--fullscreen",
                                 novideo => "--no-video",
                                 srt => "--sub-file *SUB*",
                               },
                               vlc => {
                                 arg => "--quiet --play-and-exit --no-video-title-show --input-title-format *TITLE*",
                                 audio => "--input-slave *AUDIO*",
                                 cmd => "vlc",
                                 fs => "--fullscreen",
                                 novideo => "--intf dummy --novideo",
                                 srt => "--sub-file *SUB*",
                               },
                               mpv_native => {
         arg => "--really-quiet *URL*",
         cmd => "mpv",
         fs => "--fullscreen",
         novideo => "--no-video",
         srt => "--sub-file *SUB*",
},
                             },
  videoCaption            => undef,
  videoDefinition         => undef,
  videoDimension          => undef,
  videoDuration           => undef,
  videoLicense            => undef,
  videoSyndicated         => undef,
  youtube_video_url       => "https://www.youtube.com/watch?v=%s",
}

mpv is located in /usr/local/bin/mpv

there is no error shown in terminal, but video just wont play

=>> Select one or more videos to play (:h for help)
> 13

=>> Description
--------------------------------------------------------------------------------
One of the greatest reggae songs of Pressure (Y) Love you tonight !!
--------------------------------------------------------------------------------
* URL: https://www.youtube.com/watch?v=ZHr8-NRixL4
--------------------------------------------------------------------------------
                      =>> Pressure - Love You Tonight <<=

-> Channel   : davidyewd
-> ChannelID : UCPupkEZPNXEJlGJvmmkKWow
-> Definition: SD
-> Duration  : 03:17
-> Likes     : 279
-> Dislikes  : 3
-> Comments  : 15
-> Views     : 70,673
-> Published : 31 May 2009
--------------------------------------------------------------------------------

 1. pressure - love conquer all (by mistamuffin) [03:52]
 2. Pressure - Love Is (Official Lyric Video) (by NickoRebelMusic) [03:16]
 3. Pressure - Your Love (by Anthony Naraine) [03:55]
 4. Pressure - Love and Affection (by VP Records) [04:14]
 5. Pressure - Lost Without Your Love (by zojakworldwide) [04:25]
 6. Pressure - Love and affection (by Denino1234) [04:15]
 7. Pressure - Most Wanted - Ganjah - Love conquer all (Live in Paris APR 2010) (by Nyah Hazy) [06:36]
 8. Pressure-All Is Well (Love Potion Riuddim)HQ (by dancehallism) [04:44]
 9. Love Again -Kenya Eugene Feat. Pressure - Official Music Video (by KenyaHeartMusic) [04:11]
10. Pressure- Love And Affection (by krazyfookinbitch) [04:20]
11. Pressure - "Show LOVE" - Official Music Video (by igraderecords) [03:36]
12. Pressure Busspipe   Show LOVE (by KAMS YUPEN) [03:36]
13. Pressure - Love You Tonight (by davidyewd) [03:17]
14. Cool Under Pressure Ft Ghetto Ballerina-All My Love (by CoolUnderPressure1) [03:46]
15. Pressure buss pipe - love and affection lyrics (by Αντρεας Χρ) [04:12]
16. Pressure - Love and Affection (by Ferhat Cinar) [04:19]
17. pressure busspipe live in love (by cedM974) [06:06]
18. Pressure - Love and affection (by 12345vin) [04:20]
19. Pressure - Better When We Love (Mended Hearts Riddim) (by ika043) [04:26]
20. Mike Lawry & Pressure - "Reason I Love (Glory)" (Audio) (by MikeLawryTV) [04:08]

=>> Select one or more videos to play (:h for help)
> :q

**Comment by trizen** [comment]
Hello,

I see you're using `mpv_native` as the selected player.

Try to remove the `--really-quiet` option in the configuration file, so mpv will display the error (if any). 

Additionally, try to set the full path to mpv, as:

```perl
mpv_native    => {
                  arg => "*URL*",
                  cmd => "/usr/local/bin/mpv",
                  fs => "--fullscreen",
                  novideo => "--no-video",
                  srt => "--sub-file *SUB*",
                },
```

Also make sure youtube-dl is working.

**Comment by mrkapqa** [comment]
thanks Daniel, i had used a wrong mpv-build git checkout for libass that was for wheezy; build mpv now with other instrutions as shown here

https://nyxi.eu/compiling-mpv-on-debian.html#compiling-mpv-on-debian

and configured youtube-viewer 3.2.5 afterwards,

now it functions :)

**Comment by trizen** [comment]
That's good to know. :)
