### ISSUE TITLE
there is produced a zombie process for each played video

### ISSUE THREAD

**Issue by vasisualiy** [trizen/youtube-viewer#138]
Start any video, after the player-window closed there are a zombie process of player.

Clearly, after closing of gtk-youtube-viewer all of zombies are wiped out, but anyway, it could be fixed, I think.

**Comment by trizen** [comment]
Thank you for reporting this issue. It has been fixed here: https://github.com/trizen/youtube-viewer/commit/bdd29c8e5f319044b831ce751fdc7203165983bc
