### ISSUE TITLE
cli history doesn't work

### ISSUE THREAD

**Issue by icha1** [trizen/youtube-viewer#139]
console log:
Unknown method `ReadHistory' in Term::ReadLine::Perl at /usr/share/perl5/Term/ReadLine/Perl.pm line 121.

**Comment by trizen** [comment]
In order for CLI history to work, you have to install [Term::ReadLine::Gnu](https://metacpan.org/release/Term-ReadLine-Gnu).

Alternatively, take a look at: https://github.com/hanslub42/rlwrap
