### ISSUE TITLE
Perl or API problem on Archlinux ?

### ISSUE THREAD

**Issue by cirrusUK** [trizen/youtube-viewer#140]
I get this on 2 Archlinux installs
> youtube-viewer -SV                                                                                                        
[500 read timeout] Error occured on URL: https://www.googleapis.com/youtube/v3/channels?id=UChjPKH7dFtc2EtLwrqznZFg&key=foobarfoorbarfoobarX3U3imqfoobarfoobarfoobar&part=contentDetails
Can't use an undefined value as a HASH reference at /usr/share/perl5/vendor_perl/WWW/YoutubeViewer/Subscriptions.pm line 125.
[1]    9921 exit 255   youtube-viewer -SV

IDK if a perl problem or another API change
perl version :  5.24.1-1

**Comment by trizen** [comment]
It's an API issue. A workaround has been commited here: https://github.com/trizen/youtube-viewer/commit/dcc5d1c27c31024801648d6cae1f5d5aa22cef11

I will tag a new version soon. Meanwhile, consider installing youtube-viewer-git or gtk-youtube-viewer-git from the AUR.

**Comment by cirrusUK** [comment]
regards trizen & thanks for this splendid code :xd 🥇

**Comment by trizen** [comment]
Version 3.2.6 has been released, fixing this issue.
