### ISSUE TITLE
Turning off proxy

### ISSUE THREAD

**Issue by notramo** [trizen/youtube-viewer#142]
I have exported environment variables (https_proxy, http_proxy), but I don't want to use this proxy with youtube-viewer. If I launch gtk-youtube-viewer from terminal, running 'unset https_proxy http_proxy' before it solves my problem, but I often launch it via dmenu_run. That would be good, if there was an option to not to use proxy.

**Comment by trizen** [comment]
The `env_proxy` config-option has been added [here](https://github.com/trizen/youtube-viewer/commit/18faa9674e4a6aa47243b214cc990fc0e562392d). When it's set to `0`, it will not use proxy defined in environment variables. By default, it has a value of `1`. Changing its value, requires restarting the application.
