### ISSUE TITLE
can't download video -

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#143]
hello ,

i just installed 3.2.6 on a older macbookpro with perlbrew 5.16; it works fine with mpv (via macports)
but i cannot download , it gives error

Error in option spec: "colorful||colourful|C!"

any hint?

thanks - multumesq!

**Comment by trizen** [comment]
Hi,

Thanks for reporting this issue. There was a typo in the `colorful` command-line option.

Please install the latest commit.

**Comment by mrkapqa** [comment]
thank you daniel, i incurred again in this error on osx 10.7.5 using these instructions

http://blog.johnkrauss.com/installing-youtube-viewer/

doing so i get perl 5.16 which works very fine but when i download i get the colorful error.


building mpv via macports gave me perl5.24 but i deactivated it because i was not able to reconcile it with youtube-viewer.

**Comment by trizen** [comment]
Make sure to download and install the latest git version from: https://github.com/trizen/youtube-viewer/archive/master.zip

**Comment by mrkapqa** [comment]
thank you very much,
that did it!

awesome!


Zitat von Daniel Șuteu <notifications@github.com>:
