### ISSUE TITLE
mplayer - which version needed?

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#144]
hello ,

i succesfully installed youtube-viewer on powermac g5 but did recur onto tigerbrew to get a mplayer build installed 

neu-neus-power-mac-g5:youtube-viewer-3.2.6 neuneu$ mplayer
MPlayer 1.2-4.2.1 (C) 2000-2015 MPlayer Team

the video windows does not come up so i suppose this version is not new enough for https:// streaming ?

thanks,
richie

**Comment by trizen** [comment]
Yes, most likely, the version of MPlayer is too old to support the HTTPS protocol. Try to remove the `-really-quiet` argument from the config file of youtube-viewer, in order to see the actual error message from mplayer.

**Comment by mrkapqa** [comment]
ja, you were right

MPlayer 1.2-4.2.1 (C) 2000-2015 MPlayer Team
Can't init Apple Remote.

Playing https://r4---sn-fpoq-hm2z.googlevideo.com/videoplayback?pl=18&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&source=youtube&initcwndbps=862500&upn=DbdsSp-QgYw&keepalive=yes&id=o-AJQVm1B_LCpCgSNXjb_AEm9Qqyg6LuvRrssjC-IB7zK4&expire=1492125426&ip=151.62.198.246&lmt=1449568504321753&pcm2cms=yes&ei=krLvWOqnCMPzWuX8l_gO&dur=255.964&mt=1492103731&mv=m&ms=au&mm=31&mn=sn-fpoq-hm2z&itag=248&gir=yes&clen=66307909&key=yt6&mime=video%2Fwebm&ipbits=0&requiressl=yes&signature=107320CB65C5B5FAFD70325C50909CFAA4CF2871.A684E6E2967E4EBE937C7280C100AA14B383073D&ratebypass=yes.
libavformat version 56.40.101 (internal)
https protocol not found, recompile FFmpeg with openssl, gnutls,
or securetransport enabled.
Failed to open https://r4---sn-fpoq-hm2z.googlevideo.com/videoplayback?pl=18&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&source=youtube&initcwndbps=862500&upn=DbdsSp-QgYw&keepalive=yes&id=o-AJQVm1B_LCpCgSNXjb_AEm9Qqyg6LuvRrssjC-IB7zK4&expire=1492125426&ip=151.62.198.246&lmt=1449568504321753&pcm2cms=yes&ei=krLvWOqnCMPzWuX8l_gO&dur=255.964&mt=1492103731&mv=m&ms=au&mm=31&mn=sn-fpoq-hm2z&itag=248&gir=yes&clen=66307909&key=yt6&mime=video%2Fwebm&ipbits=0&requiressl=yes&signature=107320CB65C5B5FAFD70325C50909CFAA4CF2871.A684E6E2967E4EBE937C7280C100AA14B383073D&ratebypass=yes.


Exiting... (End of file)

**Comment by mrkapqa** [comment]
any chance that i can fix this myself?
