### ISSUE TITLE
Play in mpv with ytdl hooks by passing youtube links unmodified

### ISSUE THREAD

**Issue by MMR-Burhan** [trizen/youtube-viewer#145]
Is it possible to just pass the youtube address to mpv like
`mpv https://youtu.be/1ekZEVeXwek`
I have ytdl hooks configured for mpv and would like to use them. How to achive that ?
For the above mentioned youtube link , subtitle does not load and name looks [weird](http://imgur.com/kCloAPm) in youtube-viewer.
Now if run directly than [this](http://imgur.com/AwMLbvE).

**Comment by trizen** [comment]
This is possible by adding a new entry in the `video_players` section inside the configuration file of youtube-viewer.

Something like this:
```perl
mpv_native    => {
                  arg => "--really-quiet *URL*",
                  cmd => "mpv",
                  fs => "--fullscreen",
                  novideo => "--no-video",
                  srt => "--sub-file *SUB*",
                },
```

Then change the value of `video_player_selected` to `mpv_native`.

**Comment by MMR-Burhan** [comment]
Thanks for such quick reply. It'd be really helpful if you can merge and populate manpage.

What is the reason to add `novideo => "--no-video",` inside mpv_native ?

And `srt => "--sub-file *SUB*",` works half the time for me. If coupled with mpv_native sometimes 1 sub loads twice(one with ytdl, other from youtube-viewer) and if used with normal mpv half the times sub doesn't show.

**Comment by trizen** [comment]
You're welcome. Regarding the `--no-video` option, it is passed to `mpv` when the `--novideo` option is passed to youtube-viewer.
