### ISSUE TITLE
Failed to find share dir for dist 'WWW-YoutubeViewer' at /usr/bin/vendor_perl/gtk-youtube-viewer line 56

### ISSUE THREAD

**Issue by MMR-Burhan** [trizen/youtube-viewer#146]
Installed with this [arch](https://www.archlinux.org/packages/community/any/youtube-viewer/) package. cli works fine. For gui at first it showed me 

```
Can't locate File/ShareDir.pm in @INC (you may need to install the File::ShareDir module) (@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at /usr/bin/vendor_perl/gtk-youtube-viewer line 37.
BEGIN failed--compilation aborted at /usr/bin/vendor_perl/gtk-youtube-viewer line 37.

```
Then after installing `perl-file-sharedir` ( should have been atleast optional dependency for  [this](https://www.archlinux.org/packages/community/any/youtube-viewer/) )
`gtk-youtube-viewer` show me 

`Failed to find share dir for dist 'WWW-YoutubeViewer' at /usr/bin/vendor_perl/gtk-youtube-viewer line 56`

**Comment by trizen** [comment]
Install `gtk-youtube-viewer` or `gtk-youtube-viewer-git` from the AUR or report an issue [here](https://bugs.archlinux.org/?project=5&cat%5B%5D=33&string=youtube-viewer).

**Comment by MMR-Burhan** [comment]
Thanks. Issue fixed from arch side.
