### ISSUE TITLE
Video download doesn't work with GUI

### ISSUE THREAD

**Issue by notramo** [trizen/youtube-viewer#149]
No messages in the warning log.
Download working from command line.
Youtube-dl is up to date.

**Comment by trizen** [comment]
Check the values of `terminal` and `terminal_exec` in `~/.config/gtk-youtube-viewer.conf`.

For the `sakura` terminal emulator, the correct values are:
```perl
terminal      => "/usr/bin/sakura",
terminal_exec => "-e '%s'",
```

Also make sure the value of `youtube_viewer` is set properly to the output of `which youtube-viewer`:

```perl
youtube_viewer => "/usr/bin/youtube-viewer",
```

**Comment by notramo** [comment]
Seems like these are OK, but it doesn't work.
gtk-youtube-viewer.conf: http://sprunge.us/AQPD

**Comment by trizen** [comment]
For the `st` terminal emulator, change the value of `terminal_exec` to:

```perl
terminal_exec => "-e %s",
```

**Comment by notramo** [comment]
It works. Thanks.
