### ISSUE TITLE
Option to read full description

### ISSUE THREAD

**Issue by notramo** [trizen/youtube-viewer#150]
That would be good, if there would be an option to read the full description of the video (in both youtube-viewer, and gtk-youtube-viewer).
':i=' only prints the first few line of the description, and the gtk-youtube-viewer details window also shows only the first few line.
When downloading from gtk-youtube-viewer, youtube-viewer prints the full description of the video in the terminal.

**Comment by trizen** [comment]
Good suggestion!  `(gtk-)youtube-viewer` now retrieves the full description of each video.

**Comment by jano2358** [comment]
is this not optional? seems a bit annoying when the description is long

**Comment by trizen** [comment]
When no extra-information is needed, the `--no-video-info` option can be used. (https://github.com/trizen/youtube-viewer/commit/7116c45de0ee4b39cf2e3b6e0dd0988025c02b6d)

**Comment by jano2358** [comment]
thanks! but I was talking about gtk-youtube-viewer
I tried to add it in the last line of the config file as:
`youtube_viewer_args                 => ["--no-video-info"]`
with and without brackets and I still have full descriptions when I hover over a video on the list, any other option?

**Comment by trizen** [comment]
Currently, there is no equivalent option for gtk-youtube-viewer.
