### ISSUE TITLE
No search panel shown

### ISSUE THREAD

**Issue by notramo** [trizen/youtube-viewer#156]
Sometimes, the border between the search results, and the search settings panel is fully on the right side of the window, causes that the search panel not shown.

**Comment by trizen** [comment]
I don't understand this issue. Can you elaborate a little bit?

**Comment by notramo** [comment]
There is a border between the search results, and the search panel, where you can set the search options. You can drag it with the mouse, and move. Sometimes it seems like if it was moved fully to the right side of the window, howewer it wasn't. In this case, the search panel not shown.

**Comment by trizen** [comment]
Hmm.. There was one more issue about this, but I'm not sure how it can be fixed, as I'm not able to reproduce it. See https://github.com/trizen/youtube-viewer/issues/131

**Comment by notramo** [comment]
I didn't found that issue, so it is a duplicate of #131. Sorry.
But what about putting a text to the results panel, pointing to the border?
