### ISSUE TITLE
CPAN availability:(In Ubuntu Xenial after update to Perl 5.26.0 got issues with Y.V.)

### ISSUE THREAD

**Issue by JuPlutonic** [trizen/youtube-viewer#161]
**`Attempt to reload LWP/UserAgent.pm aborted.
Compilation failed in require at ~/perl5/lib/perl5/WWW/YoutubeViewer.pm line 211.
afterwards got this:
501 Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)]:`**
Got :
Y.V. -V is **3.2.7**
Perl 5.26.0
LWP::UserAgent 6.26
LWP::Protocol::https 6.07
Ubuntu 16.04.2 64bit 
#####
Tried to update to 3.2.8.
All modules had updated with `cpan -u` except this one:
`Could not fetch authors/id/W/WW/WWW/YoutubeViewer` [see:](https://gist.github.com/JuPlutonic/2c8ab4a6f6ec934e4cecdd18843ab84d)

So the issue not about the **error**, it is about availability of module in CPAN repo.
PS: If you not affiliate with author WWW, please let me know what to do, because I'm not familiar with perl / perl community

**Comment by trizen** [comment]
The library [WWW::YoutubeViewer](https://github.com/trizen/youtube-viewer/tree/master/lib/WWW) is not available on the CPAN (and it will never be).

**Comment by rwp0** [comment]
> The library [WWW::YoutubeViewer](https://github.com/trizen/youtube-viewer/tree/master/lib/WWW) is not available on the CPAN (and it will never be).

@trizen Sorry but why not relaese on CPAN, is there a reason you can detail?

Otherwise, thanks for the software!

**Comment by trizen** [comment]
@rwp0  I think the main reason is that the  `WWW::YoutubeViewer` library does not have a stable API. It's subject to change at anytime. Therefore, it's not appropriate to release on CPAN. And it's also not well-documented, nor well-designed.

CPAN is meant for well-designed and well-documented libraries that are, more-or-less, backwards compatible with previous versions.

**Comment by rwp0** [comment]
Thank you for sharing your thoughts, and I respect your decision as the author.

> CPAN is meant for well-designed and well-documented libraries that are, more-or-less, backwards compatible with previous versions.

But I don't think so, nor found any document on the requirement of code/distro perfection for CPAN entry.

I think releasing on CPAN could enhance `youtube-viewer`'s visibility, and ease of installation for users.

Thanks again!

**Comment by trizen** [comment]
Regarding the ease of installation, `youtube-viewer` can be installed from GitHub just as easily as it could be from the CPAN:

```console
cpanm -v --sudo https://github.com/trizen/youtube-viewer/archive/refs/heads/master.zip
```

**Comment by rwp0** [comment]
Oh that's good to know 👍

8 fev 2023, Ç. 18:43 tarixində Trizen ***@***.***> yazdı:

**Comment by rwp0** [comment]
> cpanm -v --sudo https://github.com/trizen/youtube-viewer/archive/refs/heads/master.zip

Is it possible to install the --gtk version with this way (ie. runnig `cpanm` on GH archive)?
