### ISSUE TITLE
--downl-play playing local videos

### ISSUE THREAD

**Issue by blkob** [trizen/youtube-viewer#162]
Is --downl-play even supposed to play local videos? If so I can't really get it to work.
If it isn't can this functionality even be achieved? Seems a bit counterintuitive to download a video then have it still play in streaming mode.
For actually playing the video I use mpv.

**Comment by trizen** [comment]
I'm not able to test this functionality right now, but it should work in combination with the `-d` flag.

Basically, when `-d` and `--downl-play` options are both specified, youtube-viewer will download a selected video locally, then will play it with the selected video player.

**Comment by blkob** [comment]
I've tried that already and it seems to not work (I checked the network traffic and also the mpv title doesn't show a local file). I did -d --downl-play (and it downloads the video) but it doesn't actuall play the local file.

**Comment by trizen** [comment]
Thanks. There was indeed a bug in the `--downl-play` option, which should be fixed now.
