### ISSUE TITLE
Not a HASH reference at /usr/bin/youtube-viewer line 3105

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#163]
hello ,

today i tried to install youtube-viewer on ubuntu using your wheezy-deb after a failed attempt with 3.2.9 (because system perl is apparently to low with 5.14.2 and it required 5.16).

after installation i get this error

Not a HASH reference at /usr/bin/youtube-viewer line 3105

Thanks

**Comment by trizen** [comment]
This issue has been fixed in version 3.2.9.

See: https://github.com/trizen/youtube-viewer/commit/15b5629ea94804a06e06e43f4610a68e9a5dd162, https://github.com/trizen/youtube-viewer/commit/7872b5828f659df3c758276bdbeb7fc303e8ae24.
