### ISSUE TITLE
audio stops near the end

### ISSUE THREAD

**Issue by jampow** [trizen/youtube-viewer#164]
The audio stops working about some seconds to the end of the video. What could I do to solve this?

I'm using arch linux
perl 5.26.1
youtube viewer 3.3.1

I runned with `--debug` flag, but nothing was logged when the sound stoped

**Comment by trizen** [comment]
I never had this issue. One suggestion would be to try to change the video player, as it may possibly be an issue with the video player you're using. I recommend `mpv` or `mpv-light` from the AUR.

To see the actual error message produced by the video player (if any) remove the `--quiet` or `--really-quiet` argument inside the configuration file of `youtube-viewer`.

**Comment by criztovyl** [comment]
I also experience this issue.

[Here's a log gist](https://gist.github.com/criztovyl/8550e2881197ab417d21fa28a9b02ecc) with `-really-quiet` removed from `mplayer`.

**Comment by trizen** [comment]
`[tls @ 0x561571b20140]The specified session has been invalidated for some reason.`

Can you reproduce this issue with `mpv` as well?

**Comment by criztovyl** [comment]
No, I will go with `mpv` then.
