### ISSUE TITLE
Prevent terminal window from opening and checkbok for multi select enqueue videos

### ISSUE THREAD

**Issue by potholiday** [trizen/youtube-viewer#167]
Most of the time I use `gtk-youtube-viewer` to play music from youtube directly. When i select `audio only`  or `play enqueue video` option `gtk-youtube-viewer` also opens a terminal window with the video/audio. I dont want this terminal window to be opened and how to prevent it from doing this?

I also want to create a custom playlist and found `enqueue` is the best way to do this in `gtk-youtube-viewer`. It would be better if we have multi-checkbox to select videos together and then `play enqueue video` or have a way to `ctrl+select videos` from list and then `play enqueue video` 

system Ubuntu 14.04

**Comment by trizen** [comment]
There is a hack available for preventing the terminal window to be opened, by setting the following two options in the configuration file of `gtk-youtube-viewer`:

```perl
  terminal      => "",
  terminal_exec => "%s",
```

However, keep in mind that you will no longer be able to stop the audio from playing, unless you manually kill the mpv process that plays the sound.

Regarding your second request, I will consider in the future adding a multi-checkbox to select/deselect videos. It would be a nice feature to have.

Meanwhile, we have `CTRL+E`, which enqueues a selected video.

Thanks for the suggestion!

**Comment by potholiday** [comment]
Is it not possible to add a play/pause/stop button in the gui itself. That would be easier to control the videos or audios.

**Comment by trizen** [comment]
That would require quite a lot of work, unfortunately, as we don't have a built-in system that controls the video player that is the playing the audio/video from YouTube. So, not possible at the time.

**Comment by potholiday** [comment]
@trizen This is just a suggestion; when we close `gtk-youtube-viewer` it should also close the terminal (not the player itself) window also. This will stop the audio and video.
