### ISSUE TITLE
Channel Uploads Order

### ISSUE THREAD

**Issue by criztovyl** [trizen/youtube-viewer#169]
If you browse to a channel using `--channels` and then selecting one I miss a way to browse the uploads. It seems like you currently show the channels main page, which in most cases shows all uploads, but not all.
Try searching for channel `songstowearpantsto` (`Andrew Huang (by Andrew Huang)`) for example and compare to https://youtube.com/user/songstowearpantsto/uploads

Thx!

**Comment by trizen** [comment]
I'm not sure if I understand correctly your issue, but after selecting a channel from `--channels`, youtube-viewer will show the latest videos uploaded to that channel (newest first).

If you want to view channel's playlist, you can try `:p1` in videos context.

Example:

```text
$ youtube-viewer --channels songstowearpantsto

 1. ANDREW HUANG                                       ANDREW HUANG [19 Oct 2006]
 2. Songs to Wear Pants To - Topic                 Songs to Wear Pa [18 Aug 2017]
...

=>> Select a channel (:h for help)
> 1

 1. Good Run with no VFX                                      ANDREW HUANG  04:24
 2. Good Run - Behind the scenes!                             ANDREW HUANG  05:47
...

=>> Select one or more videos to play (:h for help)
> :p1

 1. THE SEASONS                                        ANDREW HUANG [04 Aug 2017]
 2. COLLABS                                            ANDREW HUANG [04 May 2017]
 3. PRODUCTION & MUSIC THEORY                          ANDREW HUANG [18 Oct 2016]
...

=>> Select a playlist (:h for help)
>
```

which is equivalent with:

```text
$ youtube-viewer -up songstowearpantsto

 1. THE SEASONS                                        ANDREW HUANG [04 Aug 2017]
 2. COLLABS                                            ANDREW HUANG [04 May 2017]
 3. PRODUCTION & MUSIC THEORY                          ANDREW HUANG [18 Oct 2016]
...

=>> Select a playlist (:h for help)
>
```

(`-up` is for user playlists, given a YouTube username. Use `-cp` for channel playlists, given a channel ID)

Does this answer your question?

**Comment by criztovyl** [comment]
> [...]  after selecting a channel from --channels, youtube-viewer will show the latest videos uploaded to that channel (newest first).

My problem is that for Andrew Huang its not (all) the latest uploads. Compare the output of `youtube-viewer` and the Uploads tab on youtube.com.

I will upload a screenshot to visualize what my problem is :)

**Comment by criztovyl** [comment]
Screenshot~s~ below, but it looks like just the order is mixed up.
In example 6 from yt-v is 4 at YT. 
Is this a know issue I have to get along with? ^^
<hr/>
yt-v output:

```
 1. Sample Swap Challenge with Andrew Applepie! (by ANDREW HUANG) [08:28]
 2. Good Run with no VFX (by ANDREW HUANG) [04:24]
 3. Good Run - Behind the scenes! (by ANDREW HUANG) [05:47]
 4. The instrument I've secretly worked on for 13 years (by ANDREW HUANG) [07:29]
 5. PLEASE EXPAND YOUR DEFINITION OF MUSIC (by ANDREW HUANG) [07:13]
 6. Andrew Huang - Good Run (Official Music Video) (by ANDREW HUANG) [04:24]
 7. MASHUPS: How They Work & Why We Love Them (by ANDREW HUANG) [05:27]
 8. That song you really wanted to hear! (by ANDREW HUANG) [05:02]
 9. SONG CHALLENGE: TECH THROUGH THE AGES (by ANDREW HUANG) [02:32]
10. The ONE thing every artist NEEDS to know (by ANDREW HUANG) [08:36]
11. Reading my old cringey lyrics and SETTING THEM ON FIRE (by ANDREW HUANG) [10:02]
12. Weird music test you have to try! (by ANDREW HUANG) [06:29]
13. IT'S HERE (by ANDREW HUANG) [06:52]
14. MUSIC PRODUCER CHOOSE YOUR OWN ADVENTURE (by ANDREW HUANG) [02:16]
15. One of the best musicals ever written (by ANDREW HUANG) [03:15]
16. A MILLION (by ANDREW HUANG) [05:43]
17. Why is the OP-1 so expensive? (by ANDREW HUANG) [04:44]
18. Sigma ft. Birdy | Find Me | Cover by Andrew Huang & Peter Hollens (by ANDREW HUANG) [03:40]
19. The best song of the year and why it works so well (by ANDREW HUANG) [08:56]
20. I met Lady Gaga (and cried) (by ANDREW HUANG) [05:18]
```
Uploads:
![bildschirmfoto vom 2017-11-18 13-32-07](https://user-images.githubusercontent.com/2174918/32980350-ea7b0e76-cc64-11e7-88cf-3a6edeca694e.png)

**Comment by trizen** [comment]
Well, youtube-viewer displays the results in the order provided by the YouTube API. So maybe it's an YouTube API issue?

**Comment by criztovyl** [comment]
Do you use API v3?
I think saw a feed URLs in the source code, but I'm not sure.
But the feeds have the right order, so most likely it's an API issue.
