### ISSUE TITLE
Roughly 50% of videos just refuse to play/download

### ISSUE THREAD

**Issue by MitchWeaver** [trizen/youtube-viewer#173]
Issue: title

How to reproduce: Search for a video. Enter a number. It then connects to the video, shows the title/description etc, then instantly exits and reprints the results page. Nothing is played or downloaded.

I can't find any logic as to why some videos work and some don't, its infuriating.

Anybody else having this same problem?

**Comment by trizen** [comment]
Videos with encrypted signatures are supported only when `youtube-dl` is installed.

**Comment by MitchWeaver** [comment]
I have youtube-dl installed?

Maybe I'm missing some kind of ./configure flag to enable it? I installed it manually
