### ISSUE TITLE
perlbrew + mpv-build > youtube-viewer does not open video

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#176]
Hello ,

i installed youtube-viewer via perlbrew on debian wheezy 64bit

perlbrew install perl5.16
perlbrew switch perl5.16

previously i had coompiled mpv via mpv-build helperscript (version 0.26),
but because of changes in recent mpv i had to pass the following option

echo --disable-drm >> mpv_options

besides youtube-viewer , mpv plays video just fine, it seems.

did i do something wrong with the perlbrew?

[config.txt](https://github.com/trizen/youtube-viewer/files/1505928/config.txt)

**Comment by trizen** [comment]
Make sure that the `mpv` is actually working. 

To check for that, execute `mpv [youtube-url]`, for some YouTube URL.

Also, for videos with encrypted signatures, `youtube-dl` is needed. (see: https://github.com/trizen/youtube-viewer/issues/173)

**Comment by mrkapqa** [comment]
thank you , 
it says
 mpv https://www.youtube.com/watch?v=s4kzfVkHhNg
Playing: https://www.youtube.com/watch?v=s4kzfVkHhNg
Failed to recognize file format.


Exiting... (Errors when loading file)


so this libdrm is needed?

**Comment by trizen** [comment]
Probably you will need to enable support for `https` URLs, either in `mpv` or `ffmpeg`.

See also: https://github.com/trizen/youtube-viewer/issues/126#issuecomment-252485103, https://github.com/trizen/youtube-viewer/issues/111

**Comment by mrkapqa** [comment]
i will ask for help to do so,
 it uesed to work previously, so i don't where the error lies

mpv 0.26.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Nov 26 16:49:11 CET 2017
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4

**Comment by trizen** [comment]
Hopefully, you got it working eventually. Closing this now...
