### ISSUE TITLE
Dependencies still not met, after `perl Build installdeps` --- OpenBSD

### ISSUE THREAD

**Issue by MitchWeaver** [trizen/youtube-viewer#180]
title

screenshot:
![Image](https://0x0.st/sXWZ.png)

After installing it manually through cpan, all is working well. Just thought I'd let you know.

**Comment by trizen** [comment]
Thanks for the report.

[Unicode::GCString](https://metacpan.org/release/Unicode-LineBreak) is considered an optional dependency. If it is installed, then the `-W` option will became available in `youtube-viewer`, which will align the results in a fixed-width format. By default, the `-W` option is not used, which means that the `Unicode::GCString` module is not really required.
