### ISSUE TITLE
How to display Playlists on Channel?

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#181]
Hello ,

i would like to display the playlists of a a channel in the terminal in order to select one to play . How could i achieve this?

i start with

youtube-viewer

--channel sirius-eng.net

1

but then it shows the videos in select order , but i would like to get to the "playlists"

Thank you very much.

**Comment by mrkapqa** [comment]
ok, found out:

:p1

**Comment by mrkapqa** [comment]
another question: 

how can i force the playlist to open as maximized windows?

Thank you very much.

**Comment by mrkapqa** [comment]
sometimes, however it would say:

--channel emian miro
Option channel requires an argument
[!] Error in command-line arguments!

**Comment by trizen** [comment]
Hi,

When searching for channels, the argument you are looking for is `--channels` (plural), followed by the search keywords.

```console
youtube-viewer --channels "emian miro"
```

The argument `--channel` (singular) is used for listing the latest videos from a channel ID:

```console
youtube-viewer --channel 'UC9g1-0gt2HxI10jdI7yEhkA'
```

Let me know if this answers your question.

**Comment by mrkapqa** [comment]
thank you,
the error was on my side as i wrote --channel instead of --channels,
yes, i did answer the question. happy new year!

**Comment by mrkapqa** [comment]
i have another question ,

how could i download eg. 

1-13 -d

but with middle quality instead of best?


thanks

**Comment by trizen** [comment]
Try the following command:

```
:d=1-13 --res=480p
```

**Comment by mrkapqa** [comment]
thank you,

i forgot that i need mp4 format for playing back on ipod touch 1st gen (up to 640p)

so i did your hack 

     
However, there is an hack around this, involving youtube-dl:

    add in the configuration file the following entry in the video_players section:

mp4dl => {
           arg => "-f mp4 *URL*",
           cmd => "youtube-dl",
         },

    then execute youtube-viewer with the following argument: --player=mp4dl

Example:

$ youtube-viewer --player=mp4dl linux videos

Now, each selected video, instead of being played, will be downloaded in MP4 format with youtube-dl.




is there a possibility to select here the resolution of mp4 ?
