### ISSUE TITLE
Changed username; mkdir Permission denied at /usr/bin/youtube-viewer line 528

### ISSUE THREAD

**Issue by DrDonkey** [trizen/youtube-viewer#182]
I changed pc username few days ago, tried to run youtube-viewer today, then I got the following error as output.
`mkdir /home/OldUserName: Permission denied at /usr/bin/youtube-viewer line 528.`
And tried looking into `/usr/bin/youtube-viewer` and line 528 has 
` or warn "[!] Can't create dir '$CONFIG{cache_dir}': $!";`
I tried looking for ways to change cache_dir in bash, but no luck.

**Comment by criztovyl** [comment]
I think it's configured in `.config/youtube-viewer/youtube-viewer.conf` (not sure if exactly .conf, but there should only be one file :) )

**Comment by DrDonkey** [comment]
Oh man, I looked at .config early and even opened the youtube-viewer folder then there I only saw garbage, no conf files.
And here after reading your comment there it was smiling and and chilling inside the youtube-viewer folder.
I got it, thank you.
