### ISSUE TITLE
How to set resolution that I want to play the video from search result.

### ISSUE THREAD

**Issue by DrDonkey** [trizen/youtube-viewer#183]
After searching for a video, how do you select videos and specify a resolution to play the video.

**Comment by criztovyl** [comment]
to play the first video with 1080p, use `1 --resolution=1080p` :)

**Comment by DrDonkey** [comment]
Man that was fast.
What are other available options?
Are they like 144p and 240p and so on?

**Comment by DrDonkey** [comment]
And also can you specify different resolution for different selection?

**Comment by criztovyl** [comment]
try `youtube-viewer --help`, it should tell you more. :)

**Comment by DrDonkey** [comment]
the --resolution is not even mentioned in the help portion.

**Comment by DrDonkey** [comment]
Actually they are. I was looking at wrong location.
Thank you so much again.
Such a dumb.
