### ISSUE TITLE
Can we add support for playing the first N video results?

### ISSUE THREAD

**Issue by D12EA177E12** [trizen/youtube-viewer#185]
Currently we have the following options --all!, --backwards!, --shuffle!, and --std-input (which allows the selection of a particular result).

I'd like youtube-viewer to play the first N video results.

**Comment by criztovyl** [comment]
IIRC, if you searched for a video, `1-10` should play the first ten videos. (`10-1` would play them in reverse order and `8 4 7 5 1 3 9 2 6 10` in exactly that order)
Does that suit your needs?

**Comment by D12EA177E12** [comment]
Oh rats. I thought multi-selection is done using a comma separated list. Thanks Christoph, it works as desired.

**Comment by trizen** [comment]
Alternatively, bellow is an example for playing the first 10 results from every page of results, given a search keyword:
```console
youtube-viewer linux --std-input="1..10 :anp"
```

Combining this with `--shuffle`, it will play 10 random results from every page. :)
