### ISSUE TITLE
How can I configure youtube-viewer to reproduce the lowest quality possible.

### ISSUE THREAD

**Issue by crstcoolv** [trizen/youtube-viewer#186]
I use youtube-viewer mostly as a music player and  isn't so smart spend a lot of band for just to listen the sound, so I was looking for a way to set it to play the worst quality because it seems this is playing always the best that it finds(most of the time hd).

I there a flag or config that do the trick ?

**Comment by trizen** [comment]
See the `--resolution` option. It recognizes various resolutions, including `240p`, `144p` and `audio`.

If no video portion is needed, you can use `--resolution=audio`, which (if possible) will load only the audio portion of the video, which is considerably smaller than the video itself.
