### ISSUE TITLE
Does youtube-viewer execute any JavaScript?

### ISSUE THREAD

**Issue by anchev** [trizen/youtube-viewer#187]
Hello,

I have just found this interesting software and I am willing to try it on openSUSE Leap 42.3.

However I am concerned about the Spectre and Meltdown vulnerabilities and the possibility for mischief they create for JavaScript coming from websites. So I am browsing the web with JS completely disabled. Still I have been looking for a way to search/watch youtube videos without JS. I have been using mps-youtube but just a text interface is not enough as it seems.

My question is: Does youtube-viewer execute any JavaScript? (i.e. is it safe for what I am looking for) Also does it store any cookies (I don't want to be tracked through cookies)

Forgive me for asking here but I couldn't find any forum or mailing list. If there is a more appropriate page to ask this, please share a link to it. Thanks!

**Comment by trizen** [comment]
Hello,

As long as you `youtube-dl` is not installed (which `youtube-viewer` uses to play videos with encrypted signatures), no JavaScript code is executed.

Regarding the storage of cookies, `youtube-viewer` does not use cookies. However, if you connect to your YouTube account through OAuth 2.0, you can be tracked by Google, as any request is directly connected to your YouTube/Google account.

Google may use other ways for tracking users. One obvious way is by IP address.

See also: https://github.com/trizen/youtube-viewer/issues/184

**Comment by anchev** [comment]
Thank you @tritzen. Yes, I am aware of the filter bubble and the other privacy issues, thanks for sharing anyway.

I have just uninstalled `youtube-dl` from YasT. However I see another `youtube-dl` available through `pip`:
```
[~]: pip list --format=columns | grep youtube                                                                                                               
mps-youtube      0.2.7.1  
youtube-dl       2018.1.21
```
Do I need to get rid of that too?

For downloading videos so far I have been using [avideo](https://notabug.org/GPast/avideo). I also have mpv, mplayer, vlc and smplayer installed. Do these work in conjunction youtube-viewer? Or are you aware of any JS/cookie issues related to them?

**Comment by trizen** [comment]
>Do I need to get rid of that too?

Yes, I think you have to remove `youtube-dl` from the pip list as well. To check if `youtube-dl` has been successfully uninstalled, the output of:
```console
which youtube-dl
```

should be:

```
youtube-dl not found
```

>[...] mpv, mplayer, vlc and smplayer installed. Do these work in conjunction youtube-viewer?

Yes, all this players are supported by `youtube-viewer`, but `mpv` is probably the one that is preferred more in conjunction with `youtube-viewer`.


>[...] are you aware of any JS/cookie issues related to them?

It is known that `mpv` uses `youtube-dl` to stream videos from various websites, so you should be aware of that.

By default, `youtube-viewer` executes `mpv` with the `--no-ytdl` argument, which disables the `youtube-dl` preprocessing.

Not sure about the other players nor if they use cookies or not.

**Comment by anchev** [comment]
Thank you. I have uninstalled `youtube-dl` from `pip` too.
Can youtube-viewer be configured to use `avideo` in place of `youtube-dl`?

BTW I sent an email to smplayer's developer and he answered:

> SMPlayer does run a little piece of javascript code in order to play YouTube videos. If you don't want use use javascript then you can go to Preferences -> Network and set the option "support for video sites" to "mpv + youtube-dl". In that case SMPlayer will use an external application (youtube-dl) to get the video address. I think that external application doesn't use javascript.
SMPlayer doesn't use cookies.

**Comment by trizen** [comment]
No problem.

> Can youtube-viewer be configured to use avideo in place of youtube-dl?

If `avideo` is compatible with `youtube-dl`, you should be able to link `youtube-dl` to `avideo`.

Example:

```
sudo ln -s /usr/bin/avideo /usr/bin/youtube-dl 
```

**Comment by anchev** [comment]
I tried what you suggest as a link but it gives an error and the video doesn't play:
```
[~]: youtube-viewer "https://www.youtube.com/watch?v=LatorN4P9aA"
2017.9.27
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/avideo/extractor/youtube.py", line 1183, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.4/site-packages/avideo/extractor/youtube.py", line 1114, in _extract_signature_function
    raise ExtractorError("Youtube's DRM has prevented this software from obtaining the video URL", expected=True)
avideo.utils.ExtractorError: Youtube's DRM has prevented this software from obtaining the video URL
 (caused by ExtractorError("Youtube's DRM has prevented this software from obtaining the video URL",)); please report this issue on https://notabug.org/GPast/avideo/wiki/bug . Make sure you are using the latest version; see  https://notabug.org/GPast/avideo/wiki/update  on how to update. Be sure to call avideo with the --verbose flag and include its complete output.

=>> Description
... // shortened by me
-> Views     : 43,318,025
-> Published : 26 Feb 2010
------------------------------------------------------------------------------------------------------------------------------------------------------------
do_connect: could not connect to socket
connect: No such file or directory

=>> Search for YouTube videos (:h for help)
> 
```
It seems related to:

https://notabug.org/GPast/avideo/issues/5

**Comment by trizen** [comment]
> Youtube's DRM has prevented this software from obtaining the video URL

As the maintainer of `avideo` says [here](https://notabug.org/GPast/avideo/issues/5#issuecomment-5423), the error is intentional.

> As a consequence, it's currently impossible to download those videos with DRM using avideo.

**Comment by anchev** [comment]
Yes, exactly. DRM sucks.
Thank you for your help!
