### ISSUE TITLE
Problems with installing of dependencies

### ISSUE THREAD

**Issue by anchev** [trizen/youtube-viewer#188]
Hi,

I am trying to install the software on openSUSE Leap 42.3.

Looking at the required dependencies in the docs I installed through YaST the following packages:
```
perl-JSON
perl-Test-LWP-UserAgent
perl-File-ShareDi
```
But I see there are still missing ones:
```
[/tmp/download/youtube-viewer]: perl Build.PL 
Checking prerequisites...
  recommends:
    *  LWP::UserAgent::Cached is not installed
    *  Mozilla::CA is not installed

Checking optional features...
fixed_width_support....disabled
  requires:
    ! Unicode::GCString is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Run 'Build installdeps' to install missing prerequisites.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'WWW-YoutubeViewer' version 'v3.3.3'
```
The first missing one is kind of strange because I actually have installed what I found about "useragent" and perl in YaST:
```
[/tmp/download/youtube-viewer]: rpm -q perl-Test-LWP-UserAgent
perl-Test-LWP-UserAgent-0.030-4.1.noarch
```
Is that not it?

For `Mozilla::CA` I can't seem to find any relevant package in YaST. Searching for `perl*mozilla*` shows me `perl-Mozilla-LDAP package` which I suppose is not the same. For `perl*gcstring*` YaST shows me only `perl-Unicode-LineBreak` and `perl-biber` neither of which seems relevant. Generally I would prefer to have the relevant dependencies installed as packages through YaST so that they can updated properly during system updates. I don't know if that would be possible if it is done through perl command line (is it ?). But as it seems there was no such option I tried the perl way:
```
# ./Build installdeps
Checking optional dependencies:
Install Mozilla::CA? [y ]y
Install LWP::UserAgent::Cached? [y ]y

CPAN.pm requires configuration, but most of it can be done automatically.
If you answer 'no' below, you will enter an interactive dialog for each
configuration option instead.

Would you like to configure as much as possible automatically? [yes] n
CPAN build and cache directory? [/root/.cpan] 
Download target directory? [/root/.cpan/sources] 
Directory where the build process takes place? [/root/.cpan/build] 
Store and re-use state information about distributions between
CPAN.pm sessions? [no] 
Directory where to store default options/environment/dialogs for
building modules that need some customization? [/root/.cpan/prefs] 
Always commit changes to config variables to disk? [no] ^C
```
Here I interrupted the process because I am not planning to use the program as root but I am willing to use it as normal user. So I assumed that storing info in `/root/.cpan` (for purpose I am unaware of) might be not suitable.

Could someone please help me up so that I don't mess up anything? So far I have never installed a perl application like this.

**Comment by trizen** [comment]
The modules [Mozilla::CA](https://metacpan.org/pod/Mozilla::CA) and [LWP::UserAgent::Cached](https://metacpan.org/pod/LWP::UserAgent::Cached) are not really required, only recommended, meaning that `youtube-viewer` can work without them.

`perl-Unicode-LineBreak` is indeed [Unicode::GCString](https://metacpan.org/pod/Unicode::GCString), so you can install it.

It is possible to install/upgrade the installed Perl modules using the `cpan` tool:

```
# cpan
> install Foo::Bar
> upgrade
```

However, this method is not generally recommended.

If `Mozilla::CA` and `LWP::UserAgent::Cached` are not available in the YaST repositories, don't worry about them.

**Comment by anchev** [comment]
Thank you. I successfully installed it without the recommended packages. However when I run it, then search for some videos, then try to play one of them, I am getting errors:
```
[~]: gtk-youtube-viewer 
[Tue Feb 20 20:05:28 2018]: WARNING **: Invalid borders specified for theme pixmap:
        /usr/share/themes/Breeze/gtk-2.0/../assets/line-h.png,
borders don't fit within the image at /usr/bin/gtk-youtube-viewer line 3074.
[Tue Feb 20 20:05:37 2018]: Can't exec "youtube-dl": No such file or directory at /usr/lib/perl5/site_perl/5.18.2/WWW/YoutubeViewer.pm line 761.
do_connect: could not connect to socket
connect: No such file or directory
```
I suppose that is related to the removal of `youtube-dl` discussed [here](https://github.com/trizen/youtube-viewer/issues/187#issuecomment-366989633).

What should I do?

And a second question: how does one perform a clean uninstall of the program? (as I have never installed through perl scripting until now and I don't know)

**Comment by anchev** [comment]
> Without youtube-dl, videos with encrypted signatures cannot be played.

What are "videos with encrypted signatures"? Do I understand correctly that the previous advise about removing `youtube-dl` actually means crippled functionality, i.e. that I am enforced to run proprietary JS from youtube and cannot watch particular videos without that? I hope you can explain.

The command which you suggest outputs:
```
[~]: youtube-viewer "https://www.youtube.com/watch?v=80N-dyGIkTE"

=>> Description
------------------------------------------------------------------------------------------------------------------------------------------------------------
Description (English / Deutsch)
In this Lecture, recorded on February 14, 2017, Richard Stallman ist talking about free software, your freedom and your privacy.

Richard Stallman spricht in diesem Vortrag, aufgenommen am 14. Februar 2017 in Köln, über die Themen freie Software, Freiheit und Privatsphäre.

----------------------------------------­­-----------------

Our website / Unsere Website:
https://call-a-tux.de

Twitter: 
https://www.twitter.com/callatux

Facebook:
http://www.facebook.com/callatux

----------------------------------------­­-----------------

License (Creative Commons CC-BY-ND):
This work is licensed under the Creative Commons Attribution-NoDerivatives 4.0 International License. To view a copy of this license, visit
http://creativecommons.org/licenses/by-nd/4.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
------------------------------------------------------------------------------------------------------------------------------------------------------------
* URL: https://www.youtube.com/watch?v=80N-dyGIkTE
------------------------------------------------------------------------------------------------------------------------------------------------------------
                               =>> Richard Stallman - Free Software, Your Freedom, Your Privacy | Cologne | Lecture | 4K <<=

-> Channel   : Call a Tux
-> ChannelID : UChWkip5hwo-Vo20r_FMQB3Q
-> Definition: HD
-> Duration  : 01:49:03
-> Likes     : 60
-> Dislikes  : 2
-> Comments  : 27
-> Views     : 3,148
-> Published : 07 Mar 2017
------------------------------------------------------------------------------------------------------------------------------------------------------------
do_connect: could not connect to socket                                                                                                                     
connect: No such file or directory                                                                                                                          
                                                                                                                                                            
=>> Search for YouTube videos (:h for help)                                                                                                                 
>
```
and opens mplayer in which I can watch the video. I don't understand what the `do_connect` line and the following one is telling me.

**Comment by trizen** [comment]
> What are "videos with encrypted signatures"?

To put simply, videos with encrypted signatures are videos with extra protection, trying to prevent people from downloading and/or streaming them. To bypass this, `youtube-dl` executes a little bit of non-free JavaScript in order to decode the address of the video.

> [...] removing youtube-dl actually means crippled functionality, i.e. that I am enforced to run proprietary JS from youtube and cannot watch particular videos without that?

Yes, that is correct. You will not be able to watch this kind of videos without `youtube-dl`. This is the trade-off, unfortunately.

> I don't understand what the do_connect line and the following one is telling me.

It's an warning message from MPlayer.

**Comment by anchev** [comment]
Thank you @tritzen. Your help is much appreciated.

**Comment by trizen** [comment]
You're welcome.
