### ISSUE TITLE
Unable to watch a lot of videos. Error:  ==> 403 Forbidden (1s) [403 Forbidden] Error occured on URL

### ISSUE THREAD

**Issue by hinojojojo** [trizen/youtube-viewer#189]
I have found quite a lot of videos which the program is unable to play. When trying to play them, the program simply makes you pick another video. When trying to download them, the program gives a large url followed by "Error:  ==> 403 Forbidden (1s) [403 Forbidden] Error occured on URL" and then again the same url.
What is this problem? is there a way to actually playing those videos in youtube-viewer?

**Comment by trizen** [comment]
Installing `youtube-dl` should fix the issue, as it is used internally by youtube-viewer to resolve the URLs of videos with DRM protection.

**Comment by hinojojojo** [comment]
Wow, perfect!
