### ISSUE TITLE
How to play only audio?

### ISSUE THREAD

**Issue by ZaxonXP** [trizen/youtube-viewer#190]
I saw that there is an option `audio_only`, but I got an error when I try to set it up from within the `YouTube-viewer`:

`Unknown option: audio_only`

Is there a way to download only audio?

**Comment by trizen** [comment]
Try `--resolution=audio`. However, this works only for videos that have an audio portion separated from the video portion.

**Comment by ZaxonXP** [comment]
Works! Thanks!

Most of YT videos has a separated audio stream.

Is there a way to list all the possible formats for the video/audio streams?

**Comment by trizen** [comment]
> Is there a way to list all the possible formats for the video/audio streams?

Not yet, unfortunately, but one can use `youtube-dl` for this purpose:

```console
youtube-dl --list-formats [URL]
```

**Comment by ZaxonXP** [comment]
OK. It would be nice to add it to to_do list. :)

**Comment by trizen** [comment]
I will think about it. Thanks!
