### ISSUE TITLE
load subscription videos, not channels

### ISSUE THREAD

**Issue by alekksander** [trizen/youtube-viewer#191]
please let us see newest videos from our channels as seen on:
https://www.youtube.com/feed/subscriptions

**Comment by trizen** [comment]
Since YouTube API v3, subscription videos are no longer provided by YouTube through their API.

See also: https://stackoverflow.com/questions/19640796/retrieving-all-the-new-subscription-videos-in-youtube-v3-api

A somewhat equivalent feature (but very inefficient) is currently implemented in the CLI version only: 

```console
youtube-viewer -SV
```

**Comment by vanyasem** [comment]
It doesn't matter that it's inefficient. What matters is that it's there. I vote for it to be added in the GUI version.

**Comment by TheBready** [comment]
I made me a .desktop with youtube-viewer -SV -A -f, but it seems some videos are missing. Only the newest video of a channel is listed. 
How can I add them all?  
Is there a way to mark them as viewed on youtube?

**Comment by HawaiinPizza** [comment]
> I made me a .desktop with youtube-viewer -SV -A -f, but it seems some videos are missing. Only the newest video of a channel is listed.
> How can I add them all?
> Is there a way to mark them as viewed on youtube?

Second I'm having the same issue. I'll try to input subscription number using -SV 2 or -SV:2 but it won't work. I wish there was an example of how to run both -SV and -S, but I couldn't find it

**Comment by IvyCox** [comment]
@trizen, can your make sort subscriptions by upload?
Or is there a way to use "unread"? (I don't know what it's and `man youtube-viewer` didn't help) If yes, than how.
And how does the command `youtube-viewer -SV`, why not all videos in the list? For example, some video uploaded 25 minutes ago and it's not listed. Or there is no video between the videos..

(via Google Translate)

**Comment by trizen** [comment]
@IvyCox To see how `-SV` works under the hood, take a look [here](https://github.com/trizen/youtube-viewer/blob/34744f73fa45e15c08fa340d975e6a937c0cc193/lib/WWW/YoutubeViewer/Subscriptions.pm#L97..L195).

It uses the `subscriptions_order` config-option, which can have either one of the following values:

- alphabetical – Sort alphabetically.
- relevance – Sort by relevance.
- unread – Sort by order of activity.

(see also: https://developers.google.com/youtube/v3/docs/subscriptions/list)

It then gets the list of subscribed channels in the sorted order specified above. Then for each channel, it gets the newest uploaded video and checks if it's recent enough (less than 3 days old). 

Once enough recent videos are collected (at most 50, where the value is given by  `--results=n`), these are the subscription videos.

As it can be seen, in most cases, not all the subscribed channels are checked. That would take a very long time.

Therefore, some videos may be missing. Also if a channel uploaded more than two videos in the last 3 days, only the most recent one is shown.

**Comment by TheBready** [comment]
Is there a solution available to list all new videos yet?
