### ISSUE TITLE
MPV's "--save-position-on-quit" flag not working

### ISSUE THREAD

**Issue by Yousuf-Khurshid** [trizen/youtube-viewer#195]
I can't seem to be able to get youtube-viewer to remember the progress I've made on a video once I've quit. I tried setting the flag on the configuration file (both MPV's own and youtube-viewer's) but to no avail. I even tried removing the --no-ytdl flag on youtube-viewer.conf. I double checked to see if launching a video through mpv and vanilla youtube-dl worked correctly and it did.

**Comment by trizen** [comment]
Please see: https://github.com/trizen/youtube-viewer/issues/145

**Comment by Yousuf-Khurshid** [comment]
Ah sorry, I really need to improve my searching skills on this site. That did the trick!

Might be a good idea to add this as a native feature though since I can imagine it will become more popular as Youtube's paradigm continues to shift more towards long videos.

Anyway, thank you for the help and your excellent program.
