### ISSUE TITLE
Can't change videoplayer

### ISSUE THREAD

**Issue by mauudev** [trizen/youtube-viewer#197]
I can't change the videoplayer, i don't want to use VLC to play videos, i changed this on preferences but it still using VLC on the GUI and the CLI youtube-viewer... I'm using Arch Linux

**Comment by trizen** [comment]
The video player can be changing by modifying the value of `video_player_selected` in the "Preferences" window.

Bellow is an example for setting the VLC player:

```perl
video_player_selected => "vlc",
```

For setting VLC in the CLI version as well, edit the configuration file: 

- `~/.config/youtube-viewer/youtube-viewer.conf`

**Comment by mauudev** [comment]
it's works thanks
