### ISSUE TITLE
"-F" not working

### ISSUE THREAD

**Issue by Pro-Prietary** [trizen/youtube-viewer#200]
This is probably my fault. I've deleted my "Favorites" folder because apparently 5000-ish videos is the cap for Youtube. I've remade a fresh, new Favorites folder, but now both on the GUI version and CLI version of youtube-viewer outputs

`
[404 Not Found] Error occured on URL: https://www.googleapis.com/youtube/v3/playlistItems?key=[...]&maxResults=20&part=contentDetails,snippet&playlistId=FLLjamopeOltl5OT2fLo2Wgg&prettyPrint=false&regionCode=US
`

**Comment by trizen** [comment]
Try the following option to see if it includes the "Favorites" playlist:

```console
youtube-viewer --up=mine
```

Alternatively, try the `--pid` id:
```console
youtube-viewer --pid=playlistID
```

...where `playlistID` is the ID of the "Favorites" playlist.

I don't know if there is a better way, other than, maybe, recreating the "Favorites" playlist back, it that is possible.
