### ISSUE TITLE
feature request: SOCK proxy support

### ISSUE THREAD

**Issue by postadelmaga** [trizen/youtube-viewer#202]
Hi,
I live in china and here youtube is blocked by GFW.
Usually Shadowsocks is what people uses to access blocked services.
Shadowsocks creates a local SOCKS5 proxy.

For the above reason I wonder if someone can add this proxy option to this nice software.

right now you can workaround this limitation using proxychains but when I try to play a video I got this error from VLC:
"Timers cannot be stopped from another thread"

Thanks

**Comment by trizen** [comment]
Hi. I just released version 3.3.4 of `youtube-viewer` which has support for SOCKS5 proxy using the [LWP::Protocol::socks](https://metacpan.org/pod/LWP::Protocol::socks) Perl module.

This can be set in the configuration file as:

```perl
http_proxy => "socks://localhost:8080",
```

See also: https://github.com/trizen/youtube-viewer/issues/194

**Comment by postadelmaga** [comment]
cool thanks
