### ISSUE TITLE
Ubuntu 18.04 PPA issue

### ISSUE THREAD

**Issue by Fef0** [trizen/youtube-viewer#203]
Hi, I tried to add your PPA in Ubuntu 18.04 but once I run apt-get update it throws a 404 Not Found Error on your PPA.
Any idea why?

**Comment by trizen** [comment]
Hi! Have you tried running `sudo apt-get update` after adding the repository?

The steps are:

```console
sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get install youtube-viewer
```

**Comment by Fef0** [comment]
Yes, I wrote the wrong command on my first message and now I corrected it. Anyway the error appears when I run apt-get update, that's why it's so weird to me
