### ISSUE TITLE
won't load videos / ubuntu 14.04.01

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#205]
hello trizen,

i am back on linux on a amd computer

did install youtube-viewer 3.3.4 but it would not playback the videos the installed player is mpv (self-built).

any clues?

Thank you!

**Comment by trizen** [comment]
Hello Richard,

Does playing videos with mpv work?

For example:

```
mpv [youtube-url]
```

If not, please write here the error message, and we'll try to find a solution.

Alternatively, try to install `youtube-dl`, as many videos have encrypted signatures and `youtube-viewer` alone cannot play them.

**Comment by mrkapqa** [comment]
Hello Daniel, thank you, it says

Failed to recognize file format.


i have installed libgnutls28 instead of libgnutls and fglrx driver instead of amdgpu.

**Comment by mrkapqa** [comment]
do most always install youtube-dl from their homepage since i know it would often not play withouth it.

**Comment by mrkapqa** [comment]
found the solution here:


had to downgrade youtube-dl via pip, then it worked


https://github.com/mpv-player/mpv/issues/4728#issuecomment-320725058

**Comment by trizen** [comment]
I'm glad you got it working. I assume we can close this issue then...
