### ISSUE TITLE
Crash upon running with mpv fullscreen

### ISSUE THREAD

**Issue by ryanmusante** [trizen/youtube-viewer#207]
Crash during run when window is minimized and than brought back to fullscreen.

`kernel: mpv/vo[2645]: segfault at 100009594 ip 000056117d6a4edf sp 00007fea5bbabfc0 error 4 in mpv[56117d5a1000+1cb000]`

Options set in gtk-youtube-viewer:

`arg   => "--profile=gpu-hq --hwdec=vdpau --video-sync=display-resample --really-quiet --title *TITLE* --no-ytdl",`

**Comment by trizen** [comment]
This seems to be an mpv issue. Please report it to the developers of mpv instead.
