### ISSUE TITLE
Not working after upgrade Mint 18.3 to 19

### ISSUE THREAD

**Issue by amartin83** [trizen/youtube-viewer#214]
After upgrade from Mint 18.3 to 19 youtube-viewer and gtk-youtube-viewer doesn't work anymore.
When run from terminal:
youtube-viewer 
Can't locate WWW/YoutubeViewer.pm in @INC (you may need to install the WWW::YoutubeViewer module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/bin/youtube-viewer line 138.
BEGIN failed--compilation aborted at /usr/bin/youtube-viewer line 138.

It could be due to Mint moving to GTK-3 while GTK-youtube-viewer uses GTK-2?

**Comment by trizen** [comment]
Try reinstalling the application.

**Comment by amartin83** [comment]
Thanks for a quick response.

In deed, it helped:
sudo aptitude purge youtube-viewer
sudo aptitude install youtube-viewer
and tada, it's working again - thanks mate!

**Comment by trizen** [comment]
No problem.
