### ISSUE TITLE
How to configure different results list layout?

### ISSUE THREAD

**Issue by ZaxonXP** [trizen/youtube-viewer#218]
Upgraded to latest 3.4.1 and I would like to set up different look for rsult list in terminal view.

Currently I have the following:

`<nr>. <title> (<channel name>) [<time>]`

and it is not aligned as you have in the example screenshot:

https://user-images.githubusercontent.com/614513/32416613-c3daa6a6-c254-11e7-9739-ed7bf93d188c.png

How can I change the layout? Which tokens can I use for configuration (the same as for extraction)?

Regards,
Piotr

**Comment by trizen** [comment]
Added support for this feature [here](https://github.com/trizen/youtube-viewer/commit/69a3ab332c298444f8a1478b7a43dfe1264cb6ba), as this was previously not possible.

When `custom_layout` is set `1`, `youtube-viewer` will use the format specified by `custom_layout_format` to format each result.

There is support for colors by either using color escapes:

```perl
  custom_layout           => 1,
  custom_layout_format    => "*NO*. \e[1;34m*TITLE*\e[0m (*AUTHOR*) (*RATING*) [*TIME*]\\n",
```

or by using the [Term::ANSIColor](https://metacpan.org/pod/Term::ANSIColor) module:

```perl
use Term::ANSIColor;

our $CONFIG = {
# ...
  custom_layout           => 1,
  custom_layout_format    => "*NO*. ${\color('bold blue')}*TITLE*${\color('reset')} (${\color('green')}*AUTHOR*${\color('reset')}) (*RATING*) [*TIME*]\\n",
# ...
}
```

The screenshot was taken using the `-W` option, which prints the results in a fixed-width format (this option requires [Unicode::LineBreak](https://metacpan.org/release/Unicode-LineBreak) or [Text::CharWidth](https://metacpan.org/release/Text-CharWidth)).

**Comment by ZaxonXP** [comment]
I took the latest code and installed it. I can use custom layout. However the -W option does nothing to me (I have Unicode::LineBreak and Text::CharWidth installed). Any ideas why it does not work?

**Comment by ZaxonXP** [comment]
I checked my config file `~/.config/youtube-viewer/youtube-viewer.conf` and I found that `results_with_colors` was already set to `0`. I set `results_fixed_width` to `1` as you suggested, but that did not change anything (still the display is not aligned as on your screenshot). What else could I check?

**Comment by trizen** [comment]
Check also your `youtube-viewer` alias. It should not contain `-C` as it also conflicts with `-W`.

Another thing would be to try to temporary remove the configuration file of `youtube-viewer` to see if it works with the default configuration, providing the `-W` argument.

**Comment by trizen** [comment]
Currently, it is not possible to use `custom_layout` and `-W` together, unfortunately.

**Comment by ZaxonXP** [comment]
Can  you please add it in the future version?

**Comment by trizen** [comment]
I will consider it, but can't promise.

**Comment by ZaxonXP** [comment]
What I would like to get is the following layout:
`%2d.[%06d] <author> <title>` where the first is 2 digit number, then duration in 00:00:00 format, then fixed width author, then the title.

My problem is that the author is not getting fixed width if I use custom layout. Could you point me out which parts of the code display the result list, so I could change the code in my local installation?

I found some code in line 2613, but after changing it I do not see any effect.

**Comment by trizen** [comment]
Check the code between the lines 3381 and 3403.

https://github.com/trizen/youtube-viewer/blob/master/bin/youtube-viewer#L3381..L3403

**Comment by ZaxonXP** [comment]
Thank you! For now I managed what I want (just reorder some columns).

**Comment by trizen** [comment]
You're welcome. I close this for now.
