### ISSUE TITLE
GtK-Youtube-Viewer # Video Quality

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#223]
Hello ,

i use GTK Youtube Viewer on a EeePC with slower processor and it functions well,

however, when i try to playback some video, they are too-high-quality for smooth playback.

There is an option in the search fields, where  i could select "Video Definition" from any to High or Standard.

If i would select "Standard" in the hope that playback would be smooth, it changes the search results, and previously shown hits no longer appear.

What i would need is to tell MPV to playback say as standard mode only in 480p, could you please help me achieve that?

Thank you

**Comment by trizen** [comment]
Hi,

This can be achieved by changing the video resolution, either in the configuration file or in the GUI.

Also consider setting the config `prefer_mp4` to a true value. This may improve the video decoding performance, assuming hardware acceleration is available.

**Comment by mrkapqa** [comment]
i tried add the option

                                       option => "--ytdl-format=bestvideo[height<=?480]+bestaudio/best",

would not channge anything

**Comment by mrkapqa** [comment]
Thank you, now i found the option §Video resolution, 

will look into the hardware acceleration issue later.
