### ISSUE TITLE
[Feature Request] Adding other sites to youtube-viewer ?

### ISSUE THREAD

**Issue by johnny-mac** [trizen/youtube-viewer#226]
Hello, I was wondering if there's a wiki or any relevant information that could help me add other websites to this program, I would like to build support in youtube-viewer for minds.com, gab.ai, bitchute.com, stream.me and D-Live :)

**Comment by trizen** [comment]
Hi. This is not going to happen, unfortunately.

But feel free to create a new program with a different name, based on `youtube-viewer` and add support for more websites.
