### ISSUE TITLE
(youtube-quality-on-the-fly)(request) integration with script jgreco

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#227]
Hello Trizen,

 continue using youtube-viewer with mpv and it is a great experience!

lately i found this script

https://github.com/jgreco/mpv-youtube-quality

which works very well (i am on low-end adsl) but not in conjunction with youtube-viewer

when i try to evoke it from within youtube-viewer , it would not find any youtube-quality to select from.

is there a way to make these two compatible?

**Comment by trizen** [comment]
Hi! Try adding the following player entry in the configuration file:

```perl
  video_player_selected  => "mpv_native",
  video_players => {

        # ...
        mpv_native    => {
                  arg => "--really-quiet *URL*",
                  cmd => "/usr/bin/mpv",
                  fs => "--fullscreen",
                  novideo => "--no-video",
                  srt => "--sub-file *SUB*",
                },
        #...
  },
```

**Comment by mrkapqa** [comment]
Wow, thank you, really impressive! It works as a treat! 
 (sorry for my late reply)
In the meantime my Internet went from 7Mbps to 20Mbps, but still very useful :)

Happy Christmas to you!

**Comment by trizen** [comment]
You're welcome! :)
