### ISSUE TITLE
Renaming the bin-files

### ISSUE THREAD

**Issue by swedebugia** [trizen/youtube-viewer#230]
Hi
I am working on improving this package in guix. Right now it is packaged as is and pulls in gtk and a lot of crap.

We generally try to destinguish between cli and gui applications and when they differ a lot in size we create 2  packages. One with the gui: e.g. "octave" and one lightweight with only the cli "octave-cli".

Would you consider renaming your bin-files according to this?
youtube-viewer -> youtube-viewer-cli
gtk-youtube-viewer -> youtube-viewer

**Comment by trizen** [comment]
No.
