### ISSUE TITLE
The "-n" parameter should play an audio only stream

### ISSUE THREAD

**Issue by pitsi** [trizen/youtube-viewer#232]
Dear maintainer.

Intro
As you will probably know, youtube offers a variety of streams for each video, with some being audio only, e.g the ones marked as "audio only" here
http://paste.debian.net/1057874/

Sometimes I use youtube-viewer like so

`youtube-viewer -n -s --pp=someplaylistidhere`

in order to play a youtube playlist with songs, shuffled and with no video. The problem is that youtube-viewer still downloads the video + audio version of each stream, using more bandwidth, but only plays the audio. That extra bandwidth usage translates to slower page loading times on my browsers or youtube-viewer lagging when playing that simple audio stream, because one of the apps hogs the bandwidth 
Changing the resolution variable in ~/.config/youtube-viewer/youtube-viewer.conf from 720p to 480p makes that "bandwith hogging" less noticeable, but it is still present.

So, I would like to suggest  the -n option to choose an audio only stream, preferably the m4a one, and help me save tons of that precious bandwidth.

**Comment by trizen** [comment]
You can use `--resolution=audio`.

See also: #190, #186.

**Comment by ZaxonXP** [comment]
There is also `-a` switch to directly select audio.
