### ISSUE TITLE
How do you order the videos by time?

### ISSUE THREAD

**Issue by DrDonkey** [trizen/youtube-viewer#238]
I do(in the terminal):
pink floyd order=time

error pops up saying [!] Invalid value <"time"> for option <order>

I tried using this month, this week, but i can't figure out.

**Comment by DrDonkey** [comment]
Crap, my bad dev. I thought this month, this week were order arguments.
Totally newbie move without searching.

**Comment by DrDonkey** [comment]
How do you filter "this week" videos only?

**Comment by trizen** [comment]
To search only for videos uploaded in the last 7 days,  you can use `--within=7d`.

For last month: `--within=1m`.
For last two years: `--within=2y`.

**Comment by DrDonkey** [comment]
Wow, thank you so much.
