### ISSUE TITLE
Live video doesn't work, does it?

### ISSUE THREAD

**Issue by DrDonkey** [trizen/youtube-viewer#243]
I am using mpv with youtube-viewer.
Everything is flawless but recently I tried watching live streaming with youtube-viewer, but it says
`[!] No streaming URL has been found...`

**Comment by trizen** [comment]
Thanks for reporting. Fixed in the above commit.

**Comment by DrDonkey** [comment]
wow. Thank you so much.

**Comment by DrDonkey** [comment]
Two kinds of live videos:
```
5. 24/7 Lofi Hiphop Radio - Beats to Study/Game/Relax (00:00) 7clouds
6. lofi hip hop radio - beats to sleep/chill to (LIVE) ChilledCow
```

5th video throws the following error:
```
> 5
ERROR: This live stream recording is not available.
[!] No streaming URL has been found...
```
Whereas 6th runs without any problem.

**Comment by trizen** [comment]
That stream is not available on YouTube either: https://www.youtube.com/watch?v=6KVjo36lrSw

**Comment by DrDonkey** [comment]
> That stream is not available on YouTube either: https://www.youtube.com/watch?v=6KVjo36lrSw

The same channel has the live stream which is available. https://www.youtube.com/watch?v=KC3sfZBmn-o

**Comment by trizen** [comment]
> Also why it lists the video then?

They are included in the YouTube search results, but I guess it makes sense to filter them out (https://github.com/trizen/youtube-viewer/commit/d9d6bf18adc74c9eedae9069a79a4f5ee6f27b35).

But https://www.youtube.com/watch?v=KC3sfZBmn-o works in youtube-viewer, no?
