### ISSUE TITLE
How to select a video definition?

### ISSUE THREAD

**Issue by max-kov** [trizen/youtube-viewer#246]
It seems that youtube-viewer is choosing to play 4k video if it is available, which my laptop cannot handle. Any way of changing the video definition?

**Comment by trizen** [comment]
See the `--resolution=<...>` option, or set the preferred `resolution` in the configuration file.

Supported resolutions are:

```
original, 2160p, 1440p, 1080p, 720p, 480p, 360p, 240p, 144p, audio
```

**Comment by max-kov** [comment]
Thanks!
