### ISSUE TITLE
ffmpeg filename handling (red herring: "No protocol not found")

### ISSUE THREAD

**Issue by philippera** [trizen/youtube-viewer#247]
Hello and thank you for this useful program.
I tried to download the youtube video called "Spacemacs: Magit staging and commit basics" with default settings. At the end of the 2 downloads (1 pure video + 1 pure audio) I got printed:
```
2019-04-21 14:13:32 (26.0 KB/s) - ‘Spacemacs: Magit staging and commit basics - natNUgnh_no - audio.webm’ saved [7036590/7036590]

[*] Merging into MKV...
Spacemacs: Magit staging and commit basics - natNUgnh_no - audio.webm: Protocol not found
Did you mean file:Spacemacs: Magit staging and commit basics - natNUgnh_no - audio.webm?
```
The first thing that came to mind was that the filenames contain special characters and indeed that is the problem.
I used ffmpeg to reproduce the problem like so:
```
$ ffmpeg -i Spacemacs:\ Magit\ staging\ and\ commit\ basics\ -\ natNUgnh_no.webm -i Spacemacs:\ Magit\ staging\ and\ commit\ basics\ -\ natNUgnh_no\ -\ audio.webm -c copy output.mkv
```
It gives the same error message ("...Protocol not found..."). 
If I rename the files to something sensible like video.webm and audio.webm then the ffmpeg command works fine.
It's probably just a matter of quoting the filenames or something similar but I have no experience in perl so I'm not proposing a fix here.

**Comment by trizen** [comment]
Thanks for finding and reporting this issue. Fixed in the above commit.

Alternative fix would be to set `fat32safe => 1` in the configuration file.
