### ISSUE TITLE
[ffmpeg] tls: The TLS connection was non-properly terminated.

### ISSUE THREAD

**Issue by ZaxonXP** [trizen/youtube-viewer#248]
youtube-viewer 2019.04.24

When I do the command: `youtube-viewer --resolution=audio https://www.youtube.com/watch?v=26T7NEUpYAo`

I get the following:
```
[ffmpeg] tls: The TLS connection was non-properly terminated.
Failed to recognize file format.
```
But if I do this directly with mpv:
```
mpv https://www.youtube.com/watch?v=26T7NEUpYAo
```
Then I get the playback. Also if I do the `youtube-viewer -3 https://www.youtube.com/watch?v=26T7NEUpYAo` then I get the playback.

Is there anything I can do to have a playback for the audio only with youtube-viewer?

Regards,
Piotr

**Comment by trizen** [comment]
I cannot confirm this issue. It may be a local issue with ffmpeg.

**Comment by ZaxonXP** [comment]
@trizen : Could you please share your `ffmpeg --version` info? 

I am trying to compile `ffmpeg` from sources, but so far I could not find a right set of configure options in order to eliminate this problem.

Regards,
Piotr

**Comment by trizen** [comment]
Sure:

```console
ffmpeg version n4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181127
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
```

It's the `ffmpeg` from the Arch Linux repo: https://www.archlinux.org/packages/extra/x86_64/ffmpeg/

The PKGBUILD that was used to build `ffmpeg` can be found at: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/ffmpeg

**Comment by ZaxonXP** [comment]
Despite the fact that I tried many ways to compile the ffmpeg I got not version which would allow me to solve my issue. So I did some more checks.

1) With the current version of `youtube-viever 3.5.4` if I do the followng:
```
youtube-viewer --resolution=audio https://www.youtube.com/watch?v=26T7NEUpYAo
```
then I get
```
Failed to recognize file format.
```
2) If I do the following:
```
mpv --ytdl-format 'bestaudio[ext=m4a]' --msg-level=ffmpeg=no https://www.youtube.com/watch?v=26T7NEUpYAo
```
I have a correct playback of audio stream without any warnings displayed on the screen.

3) However if I configure `youtube-viewer` in such a way:
```
                                mpv => {
                                 arg => "--title *TITLE* --ytdl=yes --msg-level=ffmpeg=no",
                                 audio => "--ytdl-format 'bestaudio[ext=m4a]' --msg-level=ffmpeg=no --audio-file *AUDIO*",
                                 cmd => "mpv",
                                 fs => "--fullscreen",
                                 novideo => "--no-video",
                                 srt => "--sub-file *SUB*",
                               },
```
Then I still getting this `Failed to recognize file format` and no playback. 

Is there a way to configure `youtube-viewer` in such way that it will allow me to play these not-properly terminated streams?

**Comment by trizen** [comment]
Try:

```perl
                  mpv_audio => {
                                 arg => "--title *TITLE* --ytdl-format 'bestaudio[ext=m4a]' --msg-level=ffmpeg=no *URL*",
                                 cmd => "mpv",
                                 fs => "--fullscreen",
                                 novideo => "--no-video",
                                 srt => "--sub-file *SUB*",
                               },
```

**Comment by ZaxonXP** [comment]
OK, This is working. The only downside is that I will need to specify `--player=mpv_audio` for such problematic streams.

In the configuration file I see that there is option `video_player_selected` but NO `audio_player_selected`, which would be useful when the `--resolution=audio` is specified. 

Could you add `audio_player_selected` option in the one of future releases?

**Comment by trizen** [comment]
It's also possible to set:

```perl
                        mpv => {
                                 arg => "--title *TITLE* *URL*",
                                 cmd => "mpv",
                                 fs => "--fullscreen",
                                 novideo => "--no-video",
                                 srt => "--sub-file *SUB*",
                               },
```

and pass `--no-video` to youtube-viewer when no video is needed.

**Comment by ZaxonXP** [comment]
Will this stream the audio stream only or video stream without displaying video?

**Comment by trizen** [comment]
Will stream video + audio, but without displaying video.

To stream only the audio portion, it's possible to pass `--append-arg="--ytdl-format 'bestaudio[ext=m4a]'"` to youtube-viewer, which will be passed to mpv.

But, I think it's easier to just create a player entry with the right options and change the player with `--player=[...]` whenever appropriate.

**Comment by ZaxonXP** [comment]
I did that for my local scripts. However I thought that it could be useful to have the `auido-player-selected` config option and use it when the `--resolution=audio` is used. 

For me it works, but maybe it is something to consider. :)

Thanks for helping!
