### ISSUE TITLE
Special tokens have escape characters

### ISSUE THREAD

**Issue by ReekyMarko** [trizen/youtube-viewer#250]
Having `--media-title "*TITLE*"` in my mpv launch command gives a `\` before every space, for example:`You\ won't\ believe\ all\ these\ escape\ characters`

**Comment by trizen** [comment]
This is because special tokens are auto-quoted. In your example, you have to remove the quotes around `*TITLE*`.

**Comment by ReekyMarko** [comment]
What if I want to use multiple special tokens together, like `*AUTHOR* - *TITLE*`?

**Comment by trizen** [comment]
Try preceding each space with two backslahes: `*AUTHOR*\\ - \\ *TITLE*`

**Comment by ReekyMarko** [comment]
Works now, thanks a lot!
