### ISSUE TITLE
Dies with "Can't "continue" outside a when block at /usr/bin/vendor_perl/youtube-viewer line 3733, <FIN> line 4."

### ISSUE THREAD

**Issue by jolmg** [trizen/youtube-viewer#251]
You can replicate with:

    $ youtube-viewer

    =>> Search for YouTube videos (:h for help)
    > *

    [!] No video results!

    =>> Select one or more videos to play (:h for help)
    > 1-
    Can't "continue" outside a when block at /usr/bin/vendor_perl/youtube-viewer line 3733, <FIN> line 2.
    $

**Comment by trizen** [comment]
Thanks for reporting.
