### ISSUE TITLE
Problem using Invidious as youtube URL

### ISSUE THREAD

**Issue by BurnyBoi** [trizen/youtube-viewer#252]
I am trying to play youtube videos using Invidious with the local=true parameter, which allows me to play them directly from invidio.us without having to touch googlevideo.com.  In order to do this, I set youtube_video_url in the config file to "https://invidio.us/watch?v=%s&local=true&autoplay=1&nojs=1". I also disabled DASH playback since this is not supported when playing directly from invidio.us. However, I noticed when selecting a video from youtube-viewer, I get output like this:

```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
* URL: https://invidio.us/watch?v=dQw4w9WgXcQ&local=true&autoplay=1&nojs=1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                          =>> Rick Astley - Never Gonna Give You Up (Video) <<=

-> Channel   : RickAstleyVEVO
-> ChannelID : UC38IQsAvIsxxjztdMZQtwHA
-> Category  : Music
-> Definition: HD
-> Duration  : 03:33
-> Likes     : 3,810,399
-> Dislikes  : 169,044
-> Comments  : 591,721
-> Views     : 560,364,787
-> Published : 25 Oct 2009
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Playing: https://r4---sn-ab5l6n67.googlevideo.com/videoplayback?id=o-AEVETMi1wEVcUx7QQ0-ECbi1y83yEr4BZzeRTpauC89-&itag=18&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-ab5l6n67%2Csn-p5qs7ned&ms=au%2Conr&mv=m&pl=24&ei=XKzdXK6MMJGkhgbwuKKwDA&gcr=us&initcwndbps=1782500&mime=video%2Fmp4&gir=yes&clen=15915462&ratebypass=yes&dur=212.091&lmt=1544406936248308&mt=1558031383&fvip=4&beids=9466588&c=WEB&txp=5531432&ip=4.79.1.1&ipbits=0&expire=1558053052&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cgcr%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&key=yt8&signature=928B21303FF6C3651ED81C47E57633BDE2B36887.15B887DD90DDF670063C8BDA0C736412C82598AD
 (+) Video --vid=1 (*) (h264 640x360 25.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
```

Somehow, between youtube-viewer printing that URL line and playing the video with mpv, the google video URL ends up getting passed into mpv. This doesn't seem to be the fault of mpv, since I can just do`mpv https://invidio.us/watch?v=dQw4w9WgXcQ&local=true&autoplay=1&nojs=1` from the terminal and it works as expected. Any idea why youtube-viewer is doing this? I can understand that youtube-viewer probably wasn't designed for this, but it doesn't seem to just be passing the URL directly to mpv like I would expect.

**Comment by trizen** [comment]
Hi. Please see: https://github.com/trizen/youtube-viewer/issues/227, https://github.com/trizen/youtube-viewer/issues/145, https://github.com/trizen/youtube-viewer/issues/109.

**Comment by BurnyBoi** [comment]
That worked. Thanks!
