### ISSUE TITLE
"Play in terminal" does not work

### ISSUE THREAD

**Issue by hubitor** [trizen/youtube-viewer#255]
"Play in terminal" wasn't working with the default option of mplayer, so I modified the option to mpv like this:
`video_player_selected               => "mpv",`
but it still doesn't work (no sound or no video at all), although when I start youtube-viewer from a terminal like this:
`$ youtube-viewer --player=mpv`
or
`$ youtube-viewer --player=vlc`
it does work.
As if the setting does not affect the terminal.

**Comment by trizen** [comment]
Hi. In order for this to work, you have to set `terminal` and `terminal_exec` in the Preferences window.

Example: for `tilix`, the correct values are:

```perl
  terminal       => "/usr/bin/tilix",
  terminal_exec  => "-e '%s'",
```

Additionally, the `youtube_viewer_args` option species a list of arguments to be passed to `youtube-viewer` when executed from `Play in terminal`.

For example, to pass the `--player=mpv` argument to `youtube-viewer`, set:

```perl
youtube_viewer_args => ['--player=mpv'],
```

Please let me know if this fixes your issue.

**Comment by hubitor** [comment]
Thanks for the quick reply!
The last setting fixed the issue!
