### ISSUE TITLE
Manpage

### ISSUE THREAD

**Issue by xxssmaoxx** [trizen/youtube-viewer#256]
I know that is probably not a critical feature, but I would really appreciate a manpage instead of piping the result of `youtube-viewer -h` into `less`. Especially when I don't remember the exact name  of an option which I know that exists and I need to search for it.

**Comment by trizen** [comment]
You know that it's possible to search while in `less`, right?

**Comment by xxssmaoxx** [comment]
That was the purpose of piping into `less`.

**Comment by trizen** [comment]
Great. Issue fixed.
