### ISSUE TITLE
In prompt, ctrl+h doesn't act as backspace.

### ISSUE THREAD

**Issue by roket1428** [trizen/youtube-viewer#257]
ctrl+j works perfectl as return/enter but ctrl+h prints its value (^H). Could you please fix it?

**Comment by trizen** [comment]
From [GNU Readline / Wikipedia](https://en.wikipedia.org/wiki/GNU_Readline):

> Ctrl+h : Deletes the previous character (same as backspace).

Make sure you have the [Term::ReadLine::Gnu](https://metacpan.org/pod/Term::ReadLine::Gnu) Perl module installed and this keybind will work.

If you're looking for the help message, input `:h` followed by ENTER.

**Comment by roket1428** [comment]
BTW, will you make a script like youtube-dl in perl? If you could it would better (than any kind of python shit). :)
