### ISSUE TITLE
Extract DRM videos from invidious

### ISSUE THREAD

**Issue by arankaren** [trizen/youtube-viewer#258]
I'm not an expert in perl but for videos that require youtube-dl you could bring it from https://invidio.us

code extracted from `lib/WWW/YoutubeViewer.pm`

```
use JSON;
use Data::Dumper;
use LWP::Simple;

sub _get_formats_from_ytdl {

    my ($videoID) = @_;
    # my ($self, $videoID) = @_;

    my $content = get("https://invidio.us/api/v1/videos/${videoID}?fields=formatStreams");

    my @array;
    my $ref = decode_json( $content ) // return;

    if (ref($ref) eq 'HASH' and exists($ref->{formatStreams}) and ref($ref->{formatStreams}) eq 'ARRAY') {
        foreach my $format (@{$ref->{formatStreams}}) {
            if (exists($format->{type}) and exists($format->{url})) {

                push @array,
                  {
                    itag => $format->{itag},
                    url  => $format->{url},
                    type => $format->{type},
                  };
            }
            print $format->{url};
        }
    }

    #return @array;
}

_get_formats_from_ytdl('TxAtgcNFGfk');
```

output:

```
https://r3---sn-ab5szn7z.googlevideo.com/videoplayback?expire=1562757467&ei=-3QlXcb_CNrGhwbC6o4w&ip=2604%3Aa880%3A400%3Ad1%3A%3A92a%3Ab001&id=o-AJNw3o7J1-xSxrcrkJ1LxqEC_knKglIHbyUq3NX8wUgr&itag=18&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-ab5szn7z%2Csn-ab5l6n67&ms=au%2Crdu&mv=m&mvi=2&pl=49&pcm2=yes&gcr=us&initcwndbps=126250&mime=video%2Fmp4&gir=yes&clen=23883497&ratebypass=yes&dur=327.726&lmt=1537305106544723&mt=1562735794&fvip=3&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cgcr%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAMGzIORxsHR8JT0R7HYcSGzkuVdC3ZzFRslGjTsZPcgjAiEAxIeY9u0w35NpiefreqZY7y-zOpQG8fxBElMlRZ0K5ww%3D&host=r3---sn-ab5szn7z.googlevideo.com&sig=ALgxI2wwRQIhAIACT905b3YYm7lwTaZk52mDYBOSRYOyxTLWR0Vbj4XmAiBGj4zOZjceZsNdwxYBDc-iYfhdobNmm0Z701HcQooFyQ==
```

^ is a test, with that you would get the YT URL without youtube-dl

**Please** could do this implementation without using youtube-dl. Or in the last case you could help me how to add this change

**Comment by trizen** [comment]
Thank you for your suggestion. 

I will consider implementing this as a configuration option disabled by default, which users (that are willing to share the video IDs with invidio.us) can enable, but the implementation which uses "youtube-dl" will still be used by default.

Notes:
1. The API documentation of invidio.us is available at: https://github.com/omarroth/invidious/wiki/API
2. For videos with audio/video on split URLs, the `adaptiveFormats` needs to be used. (e.g.: https://invidio.us/api/v1/videos/j5-yKhDd64s?fields=formatStreams,adaptiveFormats&pretty=1)

However, it's unclear at the moment how reliable invidio.us is or will be in the future.

**Comment by arankaren** [comment]
> However, it's unclear at the moment how reliable invidio.us is or will be in the future.

It's true I had not thought about that.

As a third option invidious I find it the best 😄

**Comment by trizen** [comment]
Support for invidio.us has been added in https://github.com/trizen/youtube-viewer/commit/0cd9a5414513d18213d8fe460c533b7107b56ebc.

In my tests, I discovered a few videos for which invidious fails, but youtube-dl succeeds.
One such video is: https://invidio.us/watch?v=Dsp_8Lm1eSk

**Comment by arankaren** [comment]
> Support for invidio.us has been added in [0cd9a54](https://github.com/trizen/youtube-viewer/commit/0cd9a5414513d18213d8fe460c533b7107b56ebc).
> 
> In my tests, I discovered a few videos for which invidious fails, but youtube-dl succeeds.
> One such video is: https://invidio.us/watch?v=Dsp_8Lm1eSk

when I put the option --invidious does not work 

I've tried with:` youtube-viewer --invidious`

**Comment by trizen** [comment]
There was indeed something missing. Should be fixed now. Thanks for testing and reporting this issue.
