### ISSUE TITLE
$info{status} always returns ok in videos with DRM

### ISSUE THREAD

**Issue by arankaren** [trizen/youtube-viewer#259]
`$info{status}` always returns `ok` in videos with DRM, the conditional should return `fail` in videos with DRM.

`lib/WWW/YoutubeViewer.pm:672`

```
if (!@streaming_urls or $info{status} =~ /fail|error/i) {
    @streaming_urls = $self->_get_formats_from_ytdl($videoID);
}
# output status with videoID "Zi_XLOBDo_Y"
print ('Hello, this is the status value: ' . $info{status}); 
```
Any ideas?

**Comment by trizen** [comment]
We're not in control of `$info{status}`. It is set by YouTube and it usually equals `fail` when the video is private/deleted or it requires 18+ years to watch.

Trying with youtube-dl in this situations, is just a last resort thing that we can do before giving up.
