### ISSUE TITLE
(kde vs gnome) Download not functioning

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#262]
Hello ,

i am using the latest version 3.5.4 and i noticed that the download function would normally function on gnome but it seems not active on kde desktop.
gtk-youtube-viewer was built with libpango1.0-dev and libgtk2.0-dev.

Thanks!

**Comment by trizen** [comment]
Hi. Make sure the terminal is configured properly in the configuration file of gtk-youtube-viewer.

**Comment by mrkapqa** [comment]
replacing "xterm" with "konsole" solved the issue, thanks!
