### ISSUE TITLE
playing a video from related videos followed by a video from related videos of the new video

### ISSUE THREAD

**Issue by fuloating** [trizen/youtube-viewer#263]
Hey, I am revisiting the https://github.com/trizen/youtube-viewer/issues/130 

The solution given in that issue was to use the :r=n -A to play the related videos of the video 'n'. 

That's all good and so on for a bit, but it lacks the variety that is brought with the original youtubes behaviour, where the next video that is going to be played in the "autoplay" mode is the top related video of the video that is currently playing and not the next song in the first videos related videos list (:r=n -A)

How can I work about to get the youtube behaviour?

**Comment by trizen** [comment]
Hi. Please check the newly added `--autoplay` option.

**Comment by fuloating** [comment]
This is so good that I have started to use youtube-viewer more once again. Already very satisfied, but pretty much every time I play a video with youtube-viewer I am using the autoplay flag. Most of the times I run yw <search> and then :autoplay=n. (yw is an alias in my shell). I noted the random_autoplay option in the configuration file, was wondering if there could be an option to have autoplay on by default, so I wouldn't need to write so many chars every time, or if there was a shorthand for the --autoplay flag. All good as is though!

**Comment by trizen** [comment]
Thanks for the feedback. I'm glad you find it useful. There is an (undocumented) alias available as `:ap=n` to mean `:autoplay=n`.

I will consider adding an option which automatically starts the autoplay mode once a video is selected for playing, pretty much like YouTube does when "Autoplay" is enabled.
