### ISSUE TITLE
MPRIS title element not video title

### ISSUE THREAD

**Issue by georgepestell** [trizen/youtube-viewer#264]
I use playerctl to get the current media track's title. It uses MPRIS elements and with youtube-viewer it just displays a whole string of text. It would be good if it just showed the title of the video

Here is the current title that is set for mpv:
mpv   xesam:title               webm&gir=yes&clen=103286435&dur=584.583&lmt=1542147798498091&mt=1564655820&fvip=4&keepalive=yes&c=WEB&txp=5432432&sparams=expire,ei,ip,id,aitags,source,requiressl,mime,gir,clen,dur,lmt&sig=ALgxI2wwRgIhAPyFOcZRIYJocIExMKquPjs1VPIkIrt28kuxnKJv3gluAiEAr5hci5ipZ6xBgtrRPBfvaY04TxeSvHwSdK47DC0PqGk=&lsparams=mm,mn,ms,mv,mvi,pl,initcwndbps&lsig=AHylml4wRAIgeo-944ErZ5Tav5zx2alGGxbPKGxXgQ9H3GwxOiTOYKkCIBb5TCS-0s1wl5wJp0OOt7R8Xole3mcQfCZ7c0CC1KOi

**Comment by trizen** [comment]
I can't reproduce this issue.

```console
$ youtube-viewer --no-interactive --extract '*TITLE*' 'https://www.youtube.com/watch?v=HX8bihEe3nA'
```

Are you sure `youtube-viewer` is used and not `youtube-dl`?

**Comment by georgepestell** [comment]
I'm using youtube-viewer with the command playerctl metadata

**Comment by trizen** [comment]
Check if `mpv [URL]` displays the title of an YouTube video. It it doesn't, then it's an `youtube-dl` issue.

**Comment by georgepestell** [comment]
Hi, thank you. mpv [URL] shows the title working normally. youtube-viewer shows a long string of text as the title
