### ISSUE TITLE
GTK: Linux Mint videos not working, error while trying VLC

### ISSUE THREAD

**Issue by PATRYK45353** [trizen/youtube-viewer#268]
Like in topic. I double click on a video and VLC turns on for less than a second with error and then turns off. I even do not have time to do a screenshot. I am new with Linux, Linux Mint is my first system. How do I fix this?

**Comment by trizen** [comment]
It may be a problem with VLC. Try the MPV player to see if it works.

To check if there is indeed a problem with VLC, check if passing an YouTube URL to VLC works:

```console
vlc [youtube-url]
```

Also, make sure you have `youtube-dl` installed.

To debug this, try setting `debug => 1` in the configuration file of `gtk-youtube-viewer`, then execute `gtk-youtube-viewer linux` from a terminal. By double-clicking a video, you should see in the terminal the vlc command that is executed.
