### ISSUE TITLE
Results set to 1 with -A plays more than I video.

### ISSUE THREAD

**Issue by ZaxonXP** [trizen/youtube-viewer#269]
Using 3.5.7

`youtube-viewer -A --results=1 -C --use-colors --player=mpv_audio --resolution=audio  "Chris Lake featuring Emma Hewitt - Carry Me Away"`

My understanding was that this will play only 1 song and exit. Instead it plays all the found results.
Is this a bug then?

Regards,
Piotr

**Comment by trizen** [comment]
This is not a bug. It's a feature. which plays all the results, including results from the next pages.

To play only the first result, use `--std-input=1` (which can be any valid STDIN input).
