### ISSUE TITLE
Start video from specific position

### ISSUE THREAD

**Issue by mrfuggy** [trizen/youtube-viewer#270]
Add option to start video from specific position in seconds. I mean command line key.
Is it possible to start video from specific position?

There is the problem with the VLC player. When rewinding (jump), the audio continues from the beginning, and the video freezes.
After switch user or lock screen, playback does not continue. Black screen is displayed.

youtube-viewer cli 3.5.5
xfce 4.14
vlc 3.0.8

**Comment by trizen** [comment]
This is not something of general interest. Sorry...

**Comment by mrfuggy** [comment]
Sorry. I think it would be a useful option for anyone else to skip part of a very long video.

**Comment by trizen** [comment]
You can jump anywhere after the video starts.
