### ISSUE TITLE
Please allow shuffling for playlists

### ISSUE THREAD

**Issue by pitsi** [trizen/youtube-viewer#271]
In short, please undo commit 1d341456c9d0d1c254a5001df1a26af9e3cc35fe .

I sometimes use youtube-viewer like so
`youtube-viewer --resolution=audio -s --pp=PLP8IMexx9lmgVbvhe6dOAvoQCSwmtP8Kx`
so the above commit break it and it will force me to change its usage to something like 
`mpv --shuffle --no-video https://www.youtube.com/playlist?list=PLP8IMexx9lmgVbvhe6dOAvoQCSwmtP8Kx`

If that gives you less maintance for youtube-viewer, keep it and I will make an alias for the above...

Thank you in advance.

**Comment by trizen** [comment]
Videos from playlists are still being shuffled. Only the playlists are not shuffled anymore (e.g. when searching for playlists with the `-p` option).

The `-pp` option is not affected.

**Comment by pitsi** [comment]
Thank you then :)
