### ISSUE TITLE
[Feature request] History of videos watched

### ISSUE THREAD

**Issue by pianoslum** [trizen/youtube-viewer#272]
Thanks for the nice program!
I couldn't figure out how watched videos can be stored over different sessions, i.e. that after restarting, y-v such videos are still marked as bold.
I found 'history' in the config file, but apparently that's only for the search history.
Any chance to implement this or am I missing something?

**Comment by trizen** [comment]
Thanks for the feature request. This is now implemented in the commit https://github.com/trizen/youtube-viewer/commit/02def284b20ab1e6e90b4947cb0ded50c483cbcc.

**Comment by pianoslum** [comment]
Well that was... fast!
Cheers :)
