### ISSUE TITLE
(kde,gtk) youtube-viewer-gtk not installing properly

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#273]
Hello ,

i have problem with installing the youtube-viewer-gtk.

on kde , it is not installing properly. 
it says it has installed, but it is not found when evoked.

hope to have installed the proper dependencies.

Thanks

**Comment by trizen** [comment]
Try:

```console
perl Build.PL --gtk
sudo ./Build installdeps
sudo ./Build install --install_path script=/usr/bin
````

**Comment by mrkapqa** [comment]
thanks, i am sorry, it was my error.

was thinking of evoking it by "youtube-viewer-gtk" instead of "gtk-youtube-viewer".

everything ok.

Thank you very much.

**Comment by trizen** [comment]
Ok. No problem. :)
