### ISSUE TITLE
SOLVED: Video freezes indefinitely after four seconds of any live stream

### ISSUE THREAD

**Issue by sawyer07** [trizen/youtube-viewer#276]
Stream used to freeze 4 seconds into any Youtube live video stream. This issue persisted through several versions of youtube-viewer, including most recent build. Normal videos would play fine, but live streams would always permanently freeze, and always after playing four seconds into the video according to the timestamp.

Resolution: I had to upgrade MPV to version 0.29 and this resolved the issue. I didn't find any online paper trail of this issue, so I am providing it now. While this is obviously specific to MPV, I could not confirm that this specific issue was appearing outside the context of using youtube-viewer. **Please mark closed** and thanks for your beautiful work!

**Comment by trizen** [comment]
Thanks for the info. Indeed, when something breaks, upgrading to the latest version of `youtube-dl` and `mpv` may fix the issue.
