### ISSUE TITLE
[Feature request] Change filters while in program

### ISSUE THREAD

**Issue by pianoslum** [trizen/youtube-viewer#279]
As far as I can see, filters (like order, author, etc.) can only be applied as program arguments as startup.
Sometimes it makes sense to change the filters while you're using the program, i.e. repeat the current search but order by date.

My suggestion would be that for each filter (e.g. --order=date) a equivalent in the program (e.g. :order=date) exists.

**Comment by trizen** [comment]
Any command-line argument can also be applied in interactive mode. However, the filtering-related options require a new search.

Example:

```
% youtube-viewer linux

...original results here...

=>> Select one or more videos to play (:h for help)
> --order=date linux

...results ordered by date here...

```

**Comment by pianoslum** [comment]
ok, I didn't know that - thanks :)
