### ISSUE TITLE
Port to perl-gtk3?

### ISSUE THREAD

**Issue by bavier** [trizen/youtube-viewer#284]
I'm wondering if there are any plans to port youtube-viewer to perl-gtk3?  According to a [recent debian bugreport](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942135) their perl-gtk2 package is being phased out.

I've done some maintenance on the [GNU Guix](https://guix.gnu.org) package for youtube-viewer and have recently had to deal with perl-gtk2 failing a test when built with gdk-pixbuf 2.39+.  The [upstream bugreport](https://gitlab.gnome.org/GNOME/perl-gtk2/issues/3) has not seen any attention, so I don't know what an appropriate solution would be to get our youtube-viewer back in action.

Anyhow, I don't mean this to sound like too much FUD; just wondering if moving to perl-gtk3 has been thought about yet.

**Comment by trizen** [comment]
It may happen in the near future. Thanks for addressing this.

Hopefully, perl-gtk3 is mature enough to support all the current features of gtk-youtube-viewer.
