### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by crides** [trizen/youtube-viewer#285]
Hi, the login for the commandline app is not working. By following [this link](https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=923751928481.apps.googleusercontent.com&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&scope=https://www.googleapis.com/auth/youtube.force-ssl) provided by the commandline app by using `:login`, but after I enter the accout information, Google tells me:

> Sign in with Google temporarily disabled for this app
>
>This app has not been verified yet by Google in order to use Google Sign In.

**Comment by trizen** [comment]
From Google:
> External apps that request sensitive or restricted user data must first be verified by Google. This process may take 4-6 weeks. In addition, if you selected restricted scopes, you'll need to go through an independent security review, which can cost USD $15k-$75k.

For now, only 100 users can sign-in (already at 100/100).

I'm not sure yet if to send the app for review.

**Comment by apetresc** [comment]
The best way around this (that most similar apps use) is to allow the user to register their own API project in their own GCP accounts, and set the `client_id` and `client_secret` somewhere a config or source file. That way each user has their own rate limit and signup quota of 100 users.

Is something like that currently possible with youtube-viewer? Where are the client tokens stored?

**Comment by trizen** [comment]
Added support for changing the client ID and client secret values in https://github.com/trizen/youtube-viewer/commit/3292f49c55c054bb39a58a68e0b02284357fef33.

Can someone test this to see if it actually works? Thanks!

**Comment by apetresc** [comment]
I will test momentarily :)

**Comment by apetresc** [comment]
Okay confirmed - it works just fine! From both `youtube-viewer` and `gtk3-youtube-viewer` I was able to access and modify subscriptions, which is all the evidence I need.

(Actually, slightly unrelated question - I know I can use `:subscribe=i` from the CLI client to _add_ a subscription, but I can't figure out how to just view videos from my subscriptions in the CLI, the way I can with `gtk3-youtube-viewer` by using "My Panel". Any hints?)

**Comment by trizen** [comment]
Thank you very much for testing! A new version will be tagged soon.

For viewing subscriptions in the CLI version, try:

```
$ youtube-viewer -S     # subscription channels
$ youtube-viewer -SV    # subscription videos (slow)
```

See also: https://github.com/trizen/youtube-viewer/issues/191

**Comment by escondida** [comment]
Trizen, I've added a note to the official Arch package that, on install or upgrade, requests that users who are able create their own credentials and references README.md.

**Comment by DL6AKU** [comment]
I cannot create OAuth 2.0 credentials because in the OAuth consent screen I cannot check internal because I am not a g-suite user? What am I doing wrong here?

![Screenshot_20200228_113913](https://user-images.githubusercontent.com/19741431/75541938-191c6a00-5a1f-11ea-99e2-afa36fc8d7e6.png)

**Comment by trizen** [comment]
The User Type should be External.
