### ISSUE TITLE
Gapless playback?

### ISSUE THREAD

**Issue by ZaxonXP** [trizen/youtube-viewer#286]
Will this ever be possible for the playlists?

Regards,
Piotr

**Comment by trizen** [comment]
I'm afraid not. Sorry.

**Comment by ZaxonXP** [comment]
I found some idea in case you would consider to implement such functionality in the future.

Using MPV player you can run it with `--input-ipc-server=/tmp/soc1` parameter. Then you can control such process using this socket file like:
```
 echo '{ "command": ["set_property", "pause", false] }' | socat - /tmp/soc1
```
This will unpause the player. So my idea is following:

1) youtube-viewer will run 2 mpv players in a socker mode in background (1 unpaused and 2 paused).
2) first mpv will play directly as soon as it will cache the stream.
3) the second will be run in a `--pause`` mode, so it will cache the content.
3) now `youtube-viewer` will monitor the 1'st mpv process and when it is finished, then it will unpause the 2'nd mpv player.
4) `youtube-viewer` will spawn another mpv in pause mode with the next record from the playlist.
5) go to step 3 or exit if there is no more records in the playlist.

What do you think about such idea? Is this visible to be implemented?

Kind regards,
Piotr

**Comment by ZaxonXP** [comment]
Here is some sample Bash script which can play the music album without gaps (uses mpv player):

```
#!/bin/bash

# Gaples playback of the audio album
# Example for: Various Super Eurobeat Vol 011 Extended Version

ids=(9Ft-PEj0kW0 Bl7rp1FXGEU KRZDp9j-Lro YL-2YgNNtd8 Qto-IouTZkI uwp_HTHzkMg YBnJxTetxEg a7jCXOF61QE)

soc1=/tmp/soc1
soc2=/tmp/soc2

touch $soc1 $soc2

#---------------------------------------
get_pause() {
    if [[ $1 == 0 ]]; then
        echo ""
    else
        echo "--pause"
    fi
}

#---------------------------------------
get_soc() {
    if [[ $(( $1 % 2 )) == 1 ]]; then
        echo $3
    else 
        echo $2
    fi
}

#---------------------------------------
for (( i=0; i < ${#ids[*]}; i++ )); do

    socket=$( get_soc $i $soc1 $soc2 )
    pause=$( get_pause $i )
    id=${ids[$i]}

    mpv --input-ipc-server="$socket" --no-video $pause "https://www.youtube.com/watch?v=$id" & 
    pids[$i]=$!

    if [[ $i > 0 ]]; then
        prev_idx=$(($i - 1))
        prev_pid=${pids[$prev_idx]}

        tail --pid=$prev_pid -f /dev/null
        echo '{ "command": ["set_property", "pause", false] }' | socat - $socket
    fi
done

rm $soc1 $soc2
```
It would be nice if `youtube-viewer` could also do this. :)

**Comment by ZaxonXP** [comment]
Dear @trizen,

Some idea in this topic. What if `youtube-viewer` would have gapless playback option and in the configuration file user would have to specify the program/script which will handle that playback?  
Let say `:g 1-` would get the list of records and store it in the temporary file, then execute specific command with that file. What do you think about it?

You could utilize the [scripts](https://github.com/ZaxonXP/youtube-viewer-scripts) I developed.
