### ISSUE TITLE
"Watch Later" playlist is not visible.

### ISSUE THREAD

**Issue by ZaxonXP** [trizen/youtube-viewer#289]
When showing own playlist when I am logged in to my YT account I do not see the "Watch Later" playlist. Is there a reason for this? It would be nice to see that list and be able to add/remove videos to/from it. Is this possible to add in the future version of `youtube-viewer`?

Kind regards,
Piotr

**Comment by trizen** [comment]
The "Watch Later" and "Watch History" playlists can no longer be retrieved using the YouTube API.

See: https://developers.google.com/youtube/v3/revision_history (September 15, 2016):
