### ISSUE TITLE
(version 3.1.5) [x_x] No streaming URL has been found...

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#298]
Hello ,

on an older computer running debian wheezy64bit  i installed a 0.25v of mpv , latest youtube-dl , and 3.1.5v of youtube-viewer via your provided .deb for wheezy.

it would install and find search results both in gtk-youtube-viewer and youtube-viewer,

but upon playing the error would come up (in youtube-viewer terminal)

[x_x] No streaming URL has been found...

do i need to install another dependency or what could i be missing?

upon installing of the .deb the following packages were installed

libdata-dump-perl (1.21-1) libparams-util-perl (1.07-1)
libfile-sharedir-perl (1.00-0.1) 
libterm-readline-gnu-perl (1.20-2+b1) 
youtube-viewer (3.1.5-wheezy) 

Thank you very much!

**Comment by trizen** [comment]
Version 3.1.5 is very old. Try installing the current version of youtube-viewer, which is 3.7.2.

**Comment by mrkapqa** [comment]
I tried to use Perlbrew for installing newer versions like 5.20.3, 
5.28.2 or so, but they all would fail
like

Test Summary Report
-------------------
../cpan/Time-Local/t/Local.t                                     (Wstat: 
512 Tests: 187 Failed: 2)
   Failed tests:  6, 12
   Non-zero exit status: 2
Files=2653, Tests=1157528, 1124 wallclock secs (102.60 usr 10.51 sys + 
603.10 cusr 54.99 csys = 771.20 CPU)
Result: FAIL
make: *** [test_harness] Fehler 2

**Comment by trizen** [comment]
Try this:

```
perlbrew install --ld --64all -Doptimize='-march=native -O3 -pipe -fno-plt' -j 2 --noman --notest --thread --multi perl-5.30.1
```

**Comment by mrkapqa** [comment]
this resulted in


rich@test-PC:~/Programme/mpv-build$   tail -f
~/perl5/perlbrew/build.perl-5.30.1.log

and I got the following output:

cc: error: unrecognized command line option ‘-fno-plt’
I can't compile the test program.
(The supplied flags or libraries might be incorrect.)

You have a BIG problem.  Shall I abort Configure [y]
Ok.  Stopping Configure.
##### Brew Failed #####

**Comment by trizen** [comment]
Try to tweak the command until it works. Start by removing `-fno-plt`.

Do Ubuntu packages work on Debian? If so, try:

```
sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get install youtube-viewer
```

**Comment by mrkapqa** [comment]
Thanks!

leaving away -fno-plt did the trick!

It compiled succesfully perl-5.30.1 and after switching perl version the
youtube-viewer would build!
very nice!

The Ubuntu packages quite often do install also on Debian, more easily
viceversa.
One has only to make sure that the repository names are changed
accordingly , eg. after enabling the repository with

sudo add-apt-repository ppa:nilarimogard/webupd8


on Debian after

Sudo apt-get update it would complain of error when fetching sources.
One then has to start package manager like Synaptic

sudo synaptic

and change there the package sources from eg. "wheezy" to "precise"
					 or  "jessie" to "trusty" et.cetera.


this repository nilarimogard is very useful but youtube-viewer i think
started only with "trusty" eg "jessie" or bit below and not with wheezy
or precise, also the mpv is quite easily not found packaged for these
Debian/Ubuntu versions (one exception is

sudo add-apt-repository ppa:pali/pali

which includes an early version of mpv for ubuntu precise)



Did use this repository

**Comment by mrkapqa** [comment]
However, from little experience i would say it is safer to not install 
Ubuntu packages on Debian, unless otherwise stated, or only if done by 
rather experienced user.

**Comment by mrkapqa** [comment]
only issue left is that the download function is not responsive in gtk-youtube-viewer.
if fucntions in youtube-viewer, but gtk-youtube-viewer is more elegant when it comes to download due to the easier sorting options :)

**Comment by mrkapqa** [comment]
Thanks!

The download function inside gkt-youtube-viewer has been re-enabled by adapting inside the Gtk-youtube-viewer the line that links to youtube-viewer with the youtube-viewer inside the perlbrew folder
eg.

  youtube_viewer              => "/home/rich/perl5/perlbrew/perls/perl-5.30.1/bin/youtube-viewer",

**Comment by mrkapqa** [comment]
Hello Daniel,

#is it possible to adapt the above Perlbrew command also for a 32Bit Linux?

on Lubuntu 12.04 it would throw error.

**Comment by trizen** [comment]
Hello @mrkapqa,

Try:

```console
perlbrew install -Doptimize='-march=native -O3 -pipe' -j 2 --noman --notest --thread --multi perl-5.30.1
```

**Comment by mrkapqa** [comment]
Thank you very much,

the error i get is

  GNU nano 2.2.6 File: ...e/rich/perl5/perlbrew/build.perl-5.30.1.log           

Auto-guessed '5.30.1'
No patch utility found
patching Configure
##### Brew Failed #####

**Comment by trizen** [comment]
`No patch utility found` -- this implies that the `patch` utility is not installed. Try:

```console
sudo apt-get install patch
```

**Comment by mrkapqa** [comment]
thank you!

this has been solved! on debian it was not needed, but on lubuntu 12.04 there was no "patch" installed by default, hence the error.
