### ISSUE TITLE
client_id creation is cumbersome

### ISSUE THREAD

**Issue by skuzzymiglet** [trizen/youtube-viewer#299]
To log in, I have to create an OAuth2 client id which means I have to create an app, a consent screen and get it verified. Is there an easier way to do this?

**Comment by trizen** [comment]
It should work even if the app is not verified, but it will be limited to a maximum number of 100 users that are allowed to log-in using the same client id/secret values, which should not be an issue for personal use.

An easier way around this would be to borrow these values from someone that already created them and is willing to share.

In other words, a group of 100 people (that trust each other and are willing to cooperate) need only one client id.
