### ISSUE TITLE
PGP key & release signing

### ISSUE THREAD

**Issue by escondida** [trizen/youtube-viewer#302]
Hi, trizen! Thanks for signing the latest release tags.

Where can I get your public key? It doesn't seem to be in any keyserver known to gpg --recv-keys, and I don't see it on your github profile page.

Also (just to be difficult), would you be willing to to [upload release signatures][1] so that the tarball can be verified independently of the git tag?

Cheers, and thanks as always for your work.

[1]: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by trizen** [comment]
Hi. Thank you for your report.

This should now work:
```
$ gpg --recv-keys D0A443C703A3A056
```

Also added a release signature to the latest commit.

If any other changes are needed, please let me know at any time.

Thanks again! Cheers!

**Comment by escondida** [comment]
Excellent! Thank you very much.

**Comment by languitar** [comment]
Would you mind adding your key also to https://keys.openpgp.org/? That's were people were directed towards after the latest attacks against keyserver a few years ago.

**Comment by trizen** [comment]
Done: https://keys.openpgp.org/search?q=ABB8BBAA2E279767774149B7D0A443C703A3A056

**Comment by mb720** [comment]
When installing from [AUR](https://aur.archlinux.org/packages/youtube-viewer/) with `aura -A youtube-viewer`, I got those errors:

    One or more PGP signatures could not be verified!
    youtube-viewer-3.9.6.tar.gz ... FAILED (unknown public key D0A443C703A3

Importing the key with

    gpg --recv-keys D0A443C703A3A056

fixed this.

I wonder if this manual import of keys can be avoided, to make it easier for other users to install youtube-viewer.
