### ISSUE TITLE
[403 Forbidden] Error occurred on URL

### ISSUE THREAD

**Issue by alreadyhasbean** [trizen/youtube-viewer#303]
whenever I search something up I receive this error, it's also providing me with this 

Use of uninitialized value in numeric gt (>) at /usr/share/perl5/vendor_perl/WWW/YoutubeViewer/Utils.pm line 213.

So I'm thinking that there's something wrong in my part, though I did try re-installing leading me still to the same results.

**Comment by pitsi** [comment]
I get that too!
```
$ youtube-viewer -s --pp=PLQhjdOS7F73qcQBmW_SpRNEOGd4xkbssX
[403 Forbidden] Error occurred on URL: https://www.googleapis.com/youtube/v3/videos?id=Lrs9-HJJhv8,w6tvIB25c2Y,z_DixvwljJw,-MD6hl45F1I,kTEeuxx7Rn8,QUdbV-ZQTEM,mPAC2zD47dc,yapEQs5tr1k,WT8bPou98cU,UBizKcExcug,v-Ga94SOV-Y,zW3qhddG5gY,3ZPgQqYRV5M,79EUbn1NJIM,DE9_Y1nzPYg,HnGu6Y9q09w,Gk8usUldmhM,jXwknnku948,Xxbccy1eME4,Bj4OYcL_i7s&key=[...]&maxResults=20&part=contentDetails,statistics,snippet&prettyPrint=false
```
As mentioned on kodi's forums for the youtube addon, it seems that youtube has deleted some api keys, so now an update to anything that plays content from youtube is mandatory :(
https://forum.kodi.tv/showthread.php?tid=348464&pid=2925102#pid2925102

**Comment by trizen** [comment]
Apparently the quota limit of 25,000,000 queries per day (!) has been reached.

![f](https://user-images.githubusercontent.com/614513/74805223-2d5bbb00-52eb-11ea-8c31-10db58968b07.png)

Looking at the usage graphs, it seems that someone abused the provided API key:

![a](https://user-images.githubusercontent.com/614513/74805238-364c8c80-52eb-11ea-80fa-55ea04bf18de.png)
![b](https://user-images.githubusercontent.com/614513/74805242-38aee680-52eb-11ea-9572-8dc7ba427321.png)
![c](https://user-images.githubusercontent.com/614513/74805247-3a78aa00-52eb-11ea-8974-2a61a2d7c29d.png)
![d](https://user-images.githubusercontent.com/614513/74805250-3c426d80-52eb-11ea-89cf-475af25379ef.png)
![e](https://user-images.githubusercontent.com/614513/74805253-3d739a80-52eb-11ea-9cee-d717cc943037.png)

That's why is recommended to create your own API key, as described in the [README.md](https://github.com/trizen/youtube-viewer#logging-in) file.

If this continues, I will permanently disable the provided API key!

**Comment by pitsi** [comment]
I do not want to sound mean, but the same 403 error pops up in other apps that play content from youtube, e.g. on mps-youtube, on which I will file an issue later on, it says this
`Youtube Error 403: Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=422897895433
`
So it is not just your key, it is any dev's key. If not, what is the chance of 3 similar apps to stop working all at once?

**Comment by trizen** [comment]
Snippet of the output of `perl -MLWP::ConsoleLogger::Everywhere /usr/bin/youtube-viewer test`:

```
.---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------.
| Text                                                                                                                                                                                                                                        |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| {                                                                                                                                                                                                                                           |
|     error => {                                                                                                                                                                                                                              |
|         code    => 403,                                                                                                                                                                                                                     |
|         errors  => [                                                                                                                                                                                                                        |
|             [0] {                                                                                                                                                                                                                           |
|                 domain       => "usageLimits",                                                                                                                                                                                              |
|                 extendedHelp => "https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=923751928481",                                                                                                        |
|                 message      => "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtub- |
| e.googleapis.com/quotas?project=923751928481",                                                                                                                                                                                              |
|                 reason       => "dailyLimitExceeded",                                                                                                                                                                                       |
|             },                                                                                                                                                                                                                              |
|         ],                                                                                                                                                                                                                                  |
|         message => "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.- |
| com/quotas?project=923751928481",                                                                                                                                                                                                           |
|     },                                                                                                                                                                                                                                      |
| }                                                                                                                                                                                                                                           |
'---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------'

```

which shows that the quota limit has been reached. The API is currently not deleted nor disabled.

**Comment by pitsi** [comment]
I see. I will try playing with youtube-viewer later on and see if the issue persists.
Btw, I have been using youtube-viewer for the last 5+ years and the key issue has not happened once.

**Comment by pitsi** [comment]
It worked now!
I just tested it here, on 10.15am at gmt+2, which is 0.15am pacific time and it just worked as it used to. And the same applies to mps-youtube, so it saves me from an issue report there.
I have also made my own api keys just in case.

However, is there a way to know what are the new limits the api has applied, e.g queries per day?

**Comment by trizen** [comment]
OK. Good. It may have been an YouTube bug after all.

A new API key is by default limited to 10,000 queries per day. If I remember correctly, the limits increase automatically once they are reached, up to some point. After that, you have to apply for more quota, which may or may not be granted.

To limits of a personal API key can be checked at (after selecting a project):
https://console.cloud.google.com/apis/api/youtube.googleapis.com/quotas

**Comment by pitsi** [comment]
And it just happened again here, but this time there is an extra line about a library of youtube-viewer
```
$ youtube-viewer -s --pp=PL4LWsX5B3wwGjLvLdvXotbmpp5T_raFF2
[403 Forbidden] Error occurred on URL: https://www.googleapis.com/youtube/v3/playlistItems?key=[...]&maxResults=20&part=contentDetails,snippet&playlistId=PL4LWsX5B3wwGjLvLdvXotbmpp5T_raFF2&prettyPrint=false
Use of uninitialized value in numeric gt (>) at /home/user/lib/WWW/YoutubeViewer/Utils.pm line 224.

**Comment by trizen** [comment]
The default API key of youtube-viewer is now disabled. See https://github.com/trizen/youtube-viewer/issues/308

**Comment by pitsi** [comment]
I see. Well f*** you google!
