### ISSUE TITLE
[Feature request] Show the latest available videos from the channel list

### ISSUE THREAD

**Issue by Khomyak-sibiryak** [trizen/youtube-viewer#304]
Currently, you need to manually go to each channel to check the latest available videos for saved channels. This will be a problem if you have many channels that you need to check.

In this case, the option that displays the last available video for each channel on the main page can save time.

**Comment by linuxenko** [comment]
It would be even better if it worked without logging in into the youtube account.

**Comment by slavikator** [comment]
I actually trying to find out the way to list videos like here: https://www.youtube.com/feed/subscriptions

Must be the same that you are referring to in this request.

**Comment by trizen** [comment]
A similar feature has been added in version 3.9.0 as "Menu -> Subscription videos" in the Gtk3 version, and `-ls` in the CLI version.

Relevant commits: https://github.com/trizen/youtube-viewer/commit/6b72a9aac6617d8e4a7f053acd0b4d62153fa7a2 and https://github.com/trizen/youtube-viewer/commit/6137ee3cfecb552b8e83fc1a65797c689d6afb19.

It uses the list of YouTube channels defined in `~/.config/youtube-viewer/youtube_users.txt`
