### ISSUE TITLE
(lubuntu19.10) gtk3-youtube-viewer:5017): GLib-GIO-CRITICAL **: 21:13:32.645: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#305]
Hello ,

i just built youtube-viewer and gtk-youtube-viewer today on a laptop running lubuntu 19.10 64bit.

the youtube-viewer seems to function flawless,
the gtk-youtube-viewer however would not play video; download would function.

this is the error in terminal

gtk3-youtube-viewer:5017): GLib-GIO-CRITICAL **: 21:13:32.645: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
2020.02.16

here are the options

**Comment by mrkapqa** [comment]
{
  audio_only                  => 0,
  auto_captions               => 0,
  cache_dir                   => "/home/m/.cache/youtube-viewer",
  captions_dir                => "/tmp",
  clear_search_list           => 1,
  clear_text_entries_on_click => 0,
  comments_order              => "time",
  comments_width              => 80,
  dash_mp4_audio              => 1,
  dash_segmented              => 1,
  dash_support                => 1,
  debug                       => 0,
  default_notebook_page       => 1,
  downloads_dir               => ".",
  entry_completion_limit      => 10,
  env_proxy                   => 1,
  fullscreen                  => 0,
  get_captions                => 1,
  history                     => 1,
  history_file                => "/home/m/.config/youtube-viewer/history.txt",
  history_limit               => 100000,
  hl                          => "en_US",
  hpaned_position             => 420,
  hpaned_width                => 250,
  http_proxy                  => undef,
  mainw_centered              => 0,
  mainw_fullscreen            => 0,
  mainw_maximized             => 0,
  mainw_size                  => "700x459",
  maxResults                  => 10,
  prefer_av1                  => 0,
  prefer_fork                 => 0,
  prefer_mp4                  => 0,
  publishedAfter              => undef,
  publishedBefore             => undef,
  recent_history              => 10,
  regionCode                  => undef,
  remember_session            => 1,
  remember_session_max        => 10,
  resolution                  => "best",
  save_titles_to_history      => 0,
  show_thumbs                 => 1,
  srt_languages               => ["en", "es"],
  terminal                    => "qterminal",
  terminal_exec               => "-e '%s'",
  thousand_separator          => ",",
  thumbnail_type              => "medium",
  tooltip_max_len             => 512,
  tooltips                    => 1,
  use_invidious_api           => 0,
  video_player_selected       => "mpv",
  video_players               => {
                                   mplayer => {
                                     arg   => "-prefer-ipv4 -really-quiet -title *TITLE*",
                                     audio => "-audiofile *AUDIO*",
                                     cmd   => "mplayer",
                                     fs    => "-fs",
                                     srt   => "-sub *SUB*",
                                   },
                                   mpv => {
                                     arg   => "--really-quiet --title=*TITLE* --no-ytdl",
                                     audio => "--audio-file=*AUDIO*",
                                     cmd   => "/usr/local/bin/mpv",
                                     fs    => "--fullscreen",
                                     srt   => "--sub-file=*SUB*",
                                   },
                                   smplayer => {
                                     arg => "-close-at-end -media-title *TITLE* *URL*",
                                     cmd => "smplayer",
                                     fs  => "-fullscreen",
                                     srt => "-sub *SUB*",
                                   },
                                   vlc => {
                                     arg   => "--quiet --play-and-exit --no-video-title-show --input-title-format=*TITLE*",
                                     audio => "--input-slave=*AUDIO*",
                                     cmd   => "vlc",
                                     fs    => "--fullscreen",
                                     srt   => "--sub-file=*SUB*",
                                   },
                                 },
  videoDimension              => undef,
  videoEmbeddable             => undef,
  videoLicense                => undef,
  videoSyndicated             => undef,
  web_browser                 => undef,
  youtube_channel_url         => "https://www.youtube.com/channel/%s",
  youtube_playlist_url        => "https://www.youtube.com/playlist?list=%s",
  youtube_users_file          => "/home/m/.config/youtube-viewer/youtube_users.txt",
  youtube_video_url           => "https://www.youtube.com/watch?v=%s",
  youtube_viewer              => "/usr/local/bin/youtube-viewer",
  youtube_viewer_args         => [],
}

**Comment by mrkapqa** [comment]
mpv is built with vaporsynth and should not be problem as it functions in youtube-viewer

 mpv --version
mpv 0.32.0-131-g6726b7a1ba Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Thu Feb 20 19:30:05 CET 2020
FFmpeg library versions:
   libavutil       56.41.100
   libavcodec      58.71.100
   libavformat     58.38.101
   libswscale      5.6.100
   libavfilter     7.76.100
   libswresample   3.6.100
FFmpeg version: N-96786-ga07b19d9af

**Comment by trizen** [comment]
See https://unix.stackexchange.com/questions/490871/lubuntu-g-is-dbus-connection

**Comment by mrkapqa** [comment]
i thought it is being built with gtk2+ as i had installed libgtk2.0-dev libpango1.0-dev
but from the error in terminal
it seems gtk-youtube-viewer is evoked with gtk3^?

**Comment by mrkapqa** [comment]
Thanks, 

`sudo apt-get purge fcitx-module-dbus`

solved it, for now.

**Comment by trizen** [comment]
Starting with version [3.7.0](https://github.com/trizen/youtube-viewer/releases/tag/3.7.0), the Gtk3 version is preferred when `gtk-youtube-viewer` is executed.

The Gtk2 version is available as `gtk2-youtube-viewer`, but is considered deprecated and soon will be removed.
