### ISSUE TITLE
Unable to Parse theme 'noone" is not a valid color name'

### ISSUE THREAD

**Issue by HirschBerge** [trizen/youtube-viewer#311]
Running on Arch linux. When starting` gtk-youtube-viewer` i get this:

```
(gtk3-youtube-viewer:112034): Gtk-WARNING **: 21:17:46.073: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name
undefined value for mandatory argument 'uri' encountered at /usr/bin/gtk3-youtube-viewer line 1498.
undefined value for mandatory argument 'uri' encountered at /usr/bin/gtk3-youtube-viewer line 1498.
```

I tried running `sudo perl -MCPAN -e 'CPAN::Shell->install(q{List::Util})' ` from another threat, but that does not seem to have helped.

**Comment by trizen** [comment]
Fixed in https://github.com/trizen/youtube-viewer/commit/d6b081bb6f8cc8ac66e3ea03e2f27a45d4441ed8. Sorry about that.
