### ISSUE TITLE
gtk2 error in ubuntu20.04

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#313]
hello ,

today i updated to ubuntu 20.04 development lts edition.

gtk-youtube-viewer would have problem building;

`Test Summary Report
-------------------
t/GdkPixbuf.t                    (Wstat: 256 Tests: 112 Failed: 1)
  Failed test:  44
  Non-zero exit status: 1
Files=228, Tests=5065, 32 wallclock secs ( 1.26 usr  0.40 sys + 25.61 cusr  4.56 csys = 31.83 CPU)
Result: FAIL
Failed 1/228 test programs. 1/5065 subtests failed.
make: *** [Makefile:3679: test_dynamic] Error 255
  XAOC/Gtk2-1.24993.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports XAOC/Gtk2-1.24993.tar.gz
`

i installed additionally

> libterm-readline-gnu-perl

> libcanberra-gtk-module libcanberra-gtk3-module libgtk2.0-dev libgtk3.0-cil-dev libgtk2.0-cil-dev

**Comment by trizen** [comment]
This is a known issue of Gtk2. Try to install Gtk3 instead.

**Comment by mrkapqa** [comment]
python3 is already the newest version (3.8.2-0ubuntu1).
python3-minimal is already the newest version (3.8.2-0ubuntu1).
python3-dev is already the newest version (3.8.2-0ubuntu1).

libgtk3-perl is already the newest version (0.036-2).
libgtk3.0-cil is already the newest version (2.99.3-4).
libgtk3.0-cil-dev is already the newest version (2.99.3-4).


`apt-cache search gtk3
gir1.2-dbusmenu-gtk3-0.4 - typelib file for libdbusmenu-gtk3-4
gir1.2-lokdocview-0.1 - GTK3 widget wrapping LibreOffice functionality - introspection
gstreamer1.0-gtk3 - GStreamer plugin for GTK+3
gtk-3-examples - example files for GTK 3
ibus-gtk3 - Intelligent Input Bus - GTK3 support
libavahi-ui-gtk3-0 - Avahi GTK+ User interface library for GTK3
libavahi-ui-gtk3-dev - Development headers for the Avahi GTK+ User interface library
libcanberra-gtk-common-dev - simple interface for playing event sounds (GTK+ shared development files)
libcanberra-gtk3-0 - GTK+ 3.0 helper for playing widget event sounds with libcanberra
libcanberra-gtk3-dev - simple interface for playing event sounds (GTK+ 3 development files)
libcanberra-gtk3-module - translates GTK3 widgets signals to event sounds
libdbusmenu-gtk3-4 - library for passing menus over DBus - GTK+ version
libdbusmenu-gtk3-dev - library for passing menus over DBus - GTK+ version developement files
libglib-object-introspection-perl - Perl bindings for gobject-introspection libraries
libgtk-3-0 - GTK graphical user interface library
libgtk3-perl - Perl bindings for the GTK+ graphical user interface library
liblibreofficekitgtk - GTK3 widget wrapping LibreOffice functionality
libreoffice-gtk3 - office productivity suite -- GTK+ 3 integration
libreofficekit-data - common data for LOKDocView
python3-aptdaemon.gtk3widgets - Python 3 GTK+ 3 widgets to run an aptdaemon client
vim-tiny - Vi IMproved - enhanced vi editor - compact version
appmenu-gtk3-module - GtkMenuShell D-Bus exporter (GTK+3.0)
clearlooks-phenix-theme - GTK3 port of Clearlooks theme
connman-gtk - fully-featured GUI for ConnMan with systray support
cyclograph-gtk3 - route altimetry plotting application - GTK3 interface
darkblood-gtk-theme - dark GTK2/GTK3/Metacity theme
darkcold-gtk-theme - dark GTK2/GTK3/Metacity theme
darkfire-gtk-theme - dark GTK2/GTK3/Metacity theme
darkmint-gtk-theme - dark GTK2/GTK3/Metacity theme
eiskaltdcpp-gtk - EiskaltDC++ GUI based on GTK+
fcitx-frontend-gtk3 - Flexible Input Method Framework - GTK+ 3 IM Module frontend
fcitx5-frontend-gtk3 - GTK3 IM Module for fcitx5
freeciv-client-extras - Civilization turn based strategy game (miscellaneous extras)
freeciv-client-gtk - Civilization turn based strategy game (GTK+ client)
freeciv-client-gtk3 - Civilization turn based strategy game (GTK 3 client)
freeciv-client-sdl - Civilization turn based strategy game (SDL client)
gambas3-gb-gtk3 - Gambas GTK+3 component
gambas3-gb-gui - Gambas graphical toolkit selector
gcin - GTK+ based input method for Chinese users
gcin-gtk3-immodule - GTK3 input method module with gcin as backend
gir1.2-spiceclientgtk-3.0 - GTK3 widget for SPICE clients (GObject-Introspection)
gnome-twitch - GNOME Twitch app for watching Twitch.tv streams without a browser or flash
golang-github-gotk3-gotk3-dev - Go bindings for GTK3
gsimplecal - lightweight GUI calendar application
gtk3-engines-breeze - Transitional package for KDE's Breeze
gtk3-engines-unico - Unico Gtk+ 3 theme engine
gtk3-im-libthai - GTK+ 3 Input Method Module using LibThai
gtk3-nocsd - Disable Gtk+ 3 client side decorations (CSD)
gtkpod - manage songs and playlists on an Apple iPod
gtkpod-data - architecture-independent files for gtkpod
gtkpod-dbg - debugging symbols for gtkpod
gummi - simple LaTeX editor with live preview
hime - GTK+ based input method for Chinese users
hime-gtk3-immodule - GTK3 input method module with HIME as backend
libappmenu-gtk3-parser-dev - GtkMenuShell to GMenuModel parser (GTK+3.0 development files)
libappmenu-gtk3-parser0 - GtkMenuShell to GMenuModel parser (GTK+3.0)
libcaribou-gtk3-module - Configurable on screen keyboard with scanning mode (GTK+ 3.0 module)
libgarcon-gtk3-1-0 - menu library for Xfce (GTK3 library)
libgarcon-gtk3-1-dev - Development files for garcon-gtk3
libghc-gi-dbusmenugtk3-dev - DBusMenu-GTK3 bindings
libghc-gi-dbusmenugtk3-doc - DBusMenu-GTK3 bindings; documentation
libghc-gi-dbusmenugtk3-prof - DBusMenu-GTK3 bindings; profiling libraries
libghc-gtk3-dev - binding to the Gtk+ graphical user interface library
libghc-gtk3-doc - binding to the Gtk+ graphical user interface library; documentation
libghc-gtk3-prof - binding to the Gtk+ graphical user interface library; profiling libraries
libgirara-gtk3-3 - library for minimalistic user interfaces (shared libraries)
libgoocanvas2-perl - Perl bindings for the goocanvas-2.0 widget using Glib::Object::Introspection
libgtk3-nocsd0 - Library to disable Gtk+ 3 client side decorations (CSD)
libgtk3-simplelist-perl - Perl simple interface to GTK+ 3's complex MVC list widget
libgtk3-webkit2-perl - WebKit2 bindings for Perl
libgtk3.0-cil - CLI binding for the GTK+ 3.0 toolkit
libgtk3.0-cil-dev - CLI binding for the GTK+ toolkit 3.0
libgwengui-gtk3-0 - Gwenhywfar GUI implementation for GTK3
libgwengui-gtk3-dev - Gwenhywfar GUI implementation for GTK3 (development files)
libinfgtk-0.7-0 - infinote-based collaborative editing (Gtk widgets)
liblablgtk3-ocaml - OCaml bindings to Gtk+ version 3 (runtime)
liblablgtk3-ocaml-dev - OCaml bindings to Gtk+ version 3 (development files)
liblablgtk3-ocaml-doc - OCaml bindings to Gtk+ version 3 (documentation)
libreoffice-gtk - transitional package for LibreOffice gtk2 backend
libspice-client-gtk-3.0-5 - GTK3 widget for SPICE clients (runtime library)
libspice-client-gtk-3.0-dev - GTK3 widget for SPICE clients (development files)
libunity-gtk3-parser-dev - GtkMenuShell to GMenuModel parser
libunity-gtk3-parser0 - GtkMenuShell to GMenuModel parser
libwxbase3.0-0v5 - wxBase library (runtime) - non-GUI support classes of wxWidgets toolkit
libwxgtk-media3.0-gtk3-0v5 - wxWidgets Cross-platform C++ GUI toolkit (GTK 3 media library runtime)
libwxgtk-media3.0-gtk3-dev - wxWidgets Cross-platform C++ GUI toolkit (GTK 3 media library development)
libwxgtk-webview3.0-gtk3-0v5 - wxWidgets Cross-platform C++ GUI toolkit (GTK 3 webview library runtime)
libwxgtk-webview3.0-gtk3-dev - wxWidgets Cross-platform C++ GUI toolkit (GTK 3 webview library development)
libwxgtk3.0-gtk3-0v5 - wxWidgets Cross-platform C++ GUI toolkit (GTK 3 runtime)
libwxgtk3.0-gtk3-dev - wxWidgets Cross-platform C++ GUI toolkit (GTK 3 development)
libxfce4panel-2.0-4 - Xfce4 panel library (GTK3 variant)
libxfce4panel-2.0-dev - Xfce4 panel library (development files for GTK3 variant)
maliit-inputcontext-gtk3 - Maliit GTK+ 3 input method module
mcomix - GTK+ image viewer for comic books
monodoc-gtk3.0-manual - compiled XML documentation for GTK# 3.0
packagekit-gtk3-module - Install fonts automatically using PackageKit
paperwork-gtk - Paperwork is a personal document manager - GTK3 frontend
paperwork-gtk-l10n-de - Gui for paperwork-backend - German localization
paperwork-gtk-l10n-en - Gui for paperwork-backend - French localization
paperwork-gtk-l10n-es - Gui for paperwork-backend - Spanish localization
paperwork-gtk-l10n-fr - Gui for paperwork-backend - English localization
paperwork-gtk-l10n-uk - Gui for paperwork-backend - Ukrainian localization
python-wxgtk3.0 - Python interface to the wxWidgets Cross-platform C++ GUI toolkit
python-wxgtk3.0-dev - Development files for wxPython
quodlibet - audio library manager and player for GTK3
ruby-gtk3 - GTK+ 3 bindings for the Ruby language
spacefm - Multi-panel tabbed file manager - GTK2 version
spacefm-common - Multi-panel tabbed file manager - common files
spacefm-gtk3 - Multi-panel tabbed file manager - GTK3 version
syncthing-gtk - GTK3-based GUI and notification area icon for syncthing
ubuntu-mate-themes - GTK2 and GTK3 themes for Ubuntu MATE
uim-gtk3 - Universal Input Method - GTK+3.x front end
uim-gtk3-immodule - Universal Input Method - GTK+3.x IM module
unity-gtk3-module - GtkMenuShell D-Bus exporter
vim-gtk - Vi IMproved - enhanced vi editor (dummy package)
vim-gtk3 - Vi IMproved - enhanced vi editor - with GTK3 GUI
yuyo-gtk-theme - Yuyo GTK2 and GTK3 Theme
`

**Comment by mrkapqa** [comment]
perl Build.PL --gtk
Checking prerequisites...
  requires:
    !  Gtk2 is not installed

Checking optional features...
fixed_width_support....disabled
  requires:
    ! Unicode::GCString is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Run 'Build installdeps' to install missing prerequisites.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'WWW-YoutubeViewer' version 'v3.7.4'

**Comment by mrkapqa** [comment]
it seems it tries to build for gtk2.

`sudo ./Build installdeps
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/root/.cpan/Metadata'
  Database was generated on Thu, 19 Mar 2020 20:55:38 GMT
Running install for module 'Gtk2'
Checksum for /root/.cpan/sources/authors/id/X/XA/XAOC/Gtk2-1.24993.tar.gz ok
Configuring X/XA/XAOC/Gtk2-1.24993.tar.gz with Makefile.PL
Including generated API documentation...
Checking if your kit is complete...
Looks good
Unrecognized argument in LIBS ignored: '-pthread'
Generating a Unix-style Makefile
Writing Makefile for Gtk2
Writing MYMETA.yml and MYMETA.json
  XAOC/Gtk2-1.24993.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for X/XA/XAOC/Gtk2-1.24993.tar.gz
cp /root/.cpan/build/Gtk2-1.24993-8/gtk.typemap blib/arch/Gtk2/Install/gtk.typemap
cp build/gtk2perl-versions.h blib/arch/Gtk2/Install/gtk2perl-versions.h
cp lib/Gtk2/SimpleMenu.pm blib/lib/Gtk2/SimpleMenu.pm
`

maybe this version of ubuntu does not include the necessary gtk3 packages?

**Comment by mrkapqa** [comment]
![Screenshot 2020-03-20 12:22:24](https://user-images.githubusercontent.com/12947465/77159614-fd4c3700-6aa5-11ea-9c53-c4d0be00593a.png)
![Screenshot 2020-03-20 12:22:45](https://user-images.githubusercontent.com/12947465/77159618-fe7d6400-6aa5-11ea-9c82-823b88442cef.png)
![Screenshot 2020-03-20 12:24:59](https://user-images.githubusercontent.com/12947465/77159619-fe7d6400-6aa5-11ea-998b-25903c68dc7a.png)
![Screenshot 2020-03-20 12:25:14](https://user-images.githubusercontent.com/12947465/77159622-ff15fa80-6aa5-11ea-9030-82f16851c1f3.png)
![Screenshot 2020-03-20 12:25:30](https://user-images.githubusercontent.com/12947465/77159623-ffae9100-6aa5-11ea-88aa-5e1b5f6d0cb6.png)

**Comment by mrkapqa** [comment]
![Screenshot 2020-03-20 12:25:41](https://user-images.githubusercontent.com/12947465/77159681-181eab80-6aa6-11ea-98cb-60d0d8827219.png)

**Comment by trizen** [comment]
To install only the Gtk3 version of GTK YouTube Viewer, execute:

```console
perl Build.PL --gtk3
sudo ./Build installdeps
sudo ./Build install
```

**Comment by mrkapqa** [comment]
ah sorry, did that already,
now it is there.
sorry for being bit lame this time.
