### ISSUE TITLE
download suddenly stopped to work

### ISSUE THREAD

**Issue by emeth69** [trizen/youtube-viewer#314]
Hi,
since today when I try to download a video through gtk3-youtube-viewer I get this error:

  sh: -c: line 0: unexpected EOF while looking for matching `''
  sh: -c: line 1: syntax error: unexpected end of file
  [Sun Mar 22 16:36:47 2020]: youtube-viewer - exit code: 256

Yesterday I've downloaded some videos without troubles. Playing videos still working. I've a personal google key.

My installed version is 3.7.4 on Linux Fedora 31 (up-to-date).

Any suggestion?

**Comment by trizen** [comment]
Hi. Make sure the values of `terminal` and `terminal_exec` are set correctly in the configuration file.

Example for `tilix`:

```perl
  terminal                    => "/usr/bin/tilix",
  terminal_exec               => "-e '%s'",
```

To see what is going on, set `debug => 1` in the config-file and execute `gtk3-youtube-viewer` from a terminal.

**Comment by emeth69** [comment]
My config says:
```
terminal                    => "/usr/bin/terminator",
terminal_exec               => "-e '%s'",
```
Instead this is the result with the debugging option on:

```
** Backgrounding process: /usr/bin/terminator -e '/usr/local/bin/youtube-viewer --resolution=best --no-interactive --download-dir=\/home\/emeth69\/Download\'s\ Videos --video-id=mB69kHKFTkE --download'
sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
/usr/bin/terminator -e '/usr/local/bin/youtube-viewer --resolution=best --no-interactive --download-dir=\/home\/emeth69\/Download\'s\ Videos --video-id=mB69kHKFTkE --download'
[Sun Mar 22 16:57:49 2020]: youtube-viewer - exit code: 256
```
Thank you for the prompt replay

**Comment by trizen** [comment]
The issue seems to be `'` in `Download's`. Try changing `terminal_exec` to:

```perl
terminal_exec => q{-e "%s"},
```

**Comment by emeth69** [comment]
You are right the apostrophe was the problem. Thank you.
