### ISSUE TITLE
[!] No streaming URL has been found...

### ISSUE THREAD

**Issue by aasutossh** [trizen/youtube-viewer#323]
I get results after a search but trying to play results in the error `[!] No streaming URL has been found...`. My `youtube-dl` version is 2020.05.29 (which is latest). Was working till few days ago, didn't change anything.

**Comment by trizen** [comment]
With what version of youtube-viewer?

**Comment by aasutossh** [comment]
3.7.5. Which sadly isn't the latest.

I haven't got the updates. I am using Manjaro KDE.

**Comment by trizen** [comment]
It should be fixed in 3.7.6. (https://github.com/trizen/youtube-viewer/commit/b2ac969756ed1e7d3d81c9c4d4ec3a740deadc1f)

**Comment by aasutossh** [comment]
I'll just get it from `aur`. That should fix the issue.
