### ISSUE TITLE
Version 3.7.6 doesn't run via terminal from /usr/local/bin/

### ISSUE THREAD

**Issue by kortewegdevries** [trizen/youtube-viewer#324]
Terminal Output:
```
:~/Repos/youtube-viewer-3.7.6$ /usr/local/bin/gtk3-youtube-viewer
[Thu Jun 25 12:24:25 2020]: Invalid key: 'use_invidious_api' at /home/korte/perl5/lib/perl5/WWW/YoutubeViewer.pm line 179.
[Thu Jun 25 12:24:26 2020]: Undefined subroutine &WWW::YoutubeViewer::set_use_invidious_api called at /usr/local/bin/gtk3-youtube-viewer line 895.
Undefined subroutine &WWW::YoutubeViewer::set_use_invidious_api called at /usr/local/bin/gtk3-youtube-viewer line 895.
```
However can run with: 
$ `gtk3-youtube-viewer`

Application was build from source version 3.7.6, no errors on install, Gtk3 option,backend is Smplayer, everything runs okay.
```
System:    Kernel: 5.4.0-37-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Xfce 4.14.2 
           Distro: Ubuntu 20.04 LTS (Focal Fossa) 
```
I'm running firejail so sometimes I need to run applications out of the sandbox hence the need $ /usr/local/bin/gtk3-youtube-viewer

**Comment by trizen** [comment]
Hi. That's because `/usr/local/bin/gtk3-youtube-viewer` is from an older installation of youtube-viewer.

See also: https://github.com/trizen/youtube-viewer/issues/321#issuecomment-635888194

**Comment by kortewegdevries** [comment]
Uh, neither runs I used default gtk with 3.7.5 and gtk3 with 3.7.6
`
:~$ locate *-youtube-viewer
/usr/local/bin/gtk-youtube-viewer
/usr/local/bin/gtk3-youtube-viewer
:~$ /usr/local/bin/gtk-youtube-viewer
[Thu Jun 25 19:21:48 2020]: Invalid key: 'use_invidious_api' at /home/korte/perl5/lib/perl5/WWW/YoutubeViewer.pm line 179.
[Thu Jun 25 19:21:48 2020]: Undefined subroutine &WWW::YoutubeViewer::set_use_invidious_api called at /usr/local/bin/gtk3-youtube-viewer line 895.
Undefined subroutine &WWW::YoutubeViewer::set_use_invidious_api called at /usr/local/bin/gtk3-youtube-viewer line 895.
:~$ /usr/local/bin/gtk3-youtube-viewer
[Thu Jun 25 19:21:59 2020]: Invalid key: 'use_invidious_api' at /home/korte/perl5/lib/perl5/WWW/YoutubeViewer.pm line 179.
[Thu Jun 25 19:21:59 2020]: Undefined subroutine &WWW::YoutubeViewer::set_use_invidious_api called at /usr/local/bin/gtk3-youtube-viewer line 895.
Undefined subroutine &WWW::YoutubeViewer::set_use_invidious_api called at /usr/local/bin/gtk3-youtube-viewer line 895.
:~$ 
`
