### ISSUE TITLE
Error parsing commandline option audio-file: option requires parameter

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#325]
Hello ,

 i just encountered this issue here

Error parsing commandline option audio-file: option requires parameter

with youtube-viewer 3.7.6 on Mac OS X 10.6.8
and mpv 0.32

is there some error i did?

https://pastebin.com/WGQFrt8F

changing in 
mpv options
the line  

from

`                               audio => "--audio-file *AUDIO*",`

into

`                               audio => "--audio-file=*AUDIO*",`

would make the error disappear but video would not play nevertheless.

**Comment by trizen** [comment]
You need to change the mpv entry to:

```perl
                             mpv => {
                               arg => "--really-quiet --title=*TITLE* --no-ytdl",
                               audio => "--audio-file=*AUDIO*",
                               cmd => "mpv",
                               fs => "--fullscreen",
                               novideo => "--no-video",
                               srt => "--sub-file=*SUB*",
                             },
```

**Comment by mrkapqa** [comment]
Thank you!
Now it is playing.
Am pleased i am able to continue use this Mac OS X Edition as it is a very stable one.
