### ISSUE TITLE
How to undo changes executed while trying youtube-viewer?

### ISSUE THREAD

**Issue by Amandaville** [trizen/youtube-viewer#326]
How do I roll-back the command 'perl -pi -ne 's{DEVEL = 0}{DEVEL = 1}' {gtk2-,gtk3-,}youtube-viewer'?

I followed the instructions to try youtube-viewer without installing.  Afterwards, I want to roll back any changes to my system but I cannot figure out how to undo the above perl command.  The perl man pages are no help whatsoever.  I do not want to leave those changes to my system.  I don't usually run commands that I don't understand prior to running them but I made an exception this time, now I want to undo those changes.

**Comment by trizen** [comment]
After [trying youtube-viewer](https://github.com/trizen/youtube-viewer#try) without installing it, `youtube-viewer` creates its configuration folder on `~/.config/youtube-viewer`, which can be removed with the following command:

```console
rm -r ~/.config/youtube-viewer
```

If [LWP::UserAgent::Cached](https://metacpan.org/pod/LWP::UserAgent::Cached) is installed, then some files may be cached in `~/.cache/youtube-viewer`, which can be removed with:

```console
rm -r ~/.cache/youtube-viewer
```

This are the only changes made by `youtube-viewer` to your system.

The command (see also `perl -h`):

```console
perl -pi -ne 's{DEVEL = 0}{DEVEL = 1}' {gtk2-,gtk3-,}youtube-viewer
```

just changes `DEVEL = 0` to `DEVEL = 1` inside the temporary files in `/tmp/youtube-viewer-master/bin/`.

To remove the `/tmp/youtube-viewer-master` directory, execute:

```console
rm -r /tmp/youtube-viewer-master
```

(although the temporary files in `/tmp/` are automatically removed after a reboot)
