### ISSUE TITLE
    !  Gtk2 is not installed

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#328]
Hello,

on an older computer i am having this issue with Debian Wheezy

      !  Gtk2 is not installed

although it is clearly installed and so is the development files.

therefore 

perl ./build.PL --gtk2

fails everytime.

**Comment by mrkapqa** [comment]
sudo apt-get install build-essential libgtk2.0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version.
libgtk2.0-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
rich@debian:~/Programs/youtube-viewer-master$ sudo apt-get install gtk2.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libgtk2.0-common' for regex 'gtk2.0'
Note, selecting 'libgtk2.0-0-dbg' for regex 'gtk2.0'
Note, selecting 'monodoc-gtk2.0-manual' for regex 'gtk2.0'
Note, selecting 'lazarus-ide-gtk2-0.9.30.4' for regex 'gtk2.0'
Note, selecting 'librccgtk2-0' for regex 'gtk2.0'
Note, selecting 'libgtk2.0-cil-dev' for regex 'gtk2.0'
Note, selecting 'libgtk2.0-bin' for regex 'gtk2.0'
Note, selecting 'libgtk2.0-cil' for regex 'gtk2.0'
Note, selecting 'libgtk2.0-dev' for regex 'gtk2.0'
Note, selecting 'libgwengui-gtk2-0' for regex 'gtk2.0'
Note, selecting 'libgtk2.0-doc' for regex 'gtk2.0'
Note, selecting 'gtk2.0-binver-2.10.0' for regex 'gtk2.0'
Note, selecting 'uim-gtk2.0' for regex 'gtk2.0'
Note, selecting 'gtk2.0-examples' for regex 'gtk2.0'
Note, selecting 'lcl-gtk2-0.9.30.4' for regex 'gtk2.0'
Note, selecting 'libgirara-gtk2-0' for regex 'gtk2.0'
Note, selecting 'libgtk2.0-0' for regex 'gtk2.0'
Note, selecting 'libgtk2.0-0' instead of 'gtk2.0-binver-2.10.0'
libgirara-gtk2-0 is already the newest version.
gtk2.0-examples is already the newest version.
libgtk2.0-0 is already the newest version.
libgtk2.0-0-dbg is already the newest version.
libgtk2.0-bin is already the newest version.
libgtk2.0-common is already the newest version.
libgtk2.0-dev is already the newest version.
libgtk2.0-doc is already the newest version.
libgtk2.0-cil is already the newest version.
libgtk2.0-cil-dev is already the newest version.
monodoc-gtk2.0-manual is already the newest version.
lazarus-ide-gtk2-0.9.30.4 is already the newest version.
lcl-gtk2-0.9.30.4 is already the newest version.
libgwengui-gtk2-0 is already the newest version.
librccgtk2-0 is already the newest version.
uim-gtk2.0 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by trizen** [comment]
You also need the Perl [Gtk2](https://metacpan.org/pod/Gtk2) module to be installed.

The package I think it's called `libgtk2-perl`:

```console
sudo apt-get install libgtk2-perl
```

To test if the module is installed and is working correctly, try the following command:

```console
perl -MGtk2=init -E 'Gtk2::Window->new->show_all; Gtk2->main;'
```

(a blank window should pop-up)

**Comment by mrkapqa** [comment]
Thank you,

i installed it but still it would complain of not gtk2 (v.3.7.7 of yout-vwr)
hmm, very strange. 
it was an old computer with pentium 4 but that should not matter.
but scrapped the hd and installed windows xp/7 for the moment so please close (unsolved)

**Comment by mrkapqa** [comment]
rich@debian:~/Programs/youtube-viewer-master$ sudo apt-get install libgtk2.0-0 libgtk2.0-dev libgtk2-perl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgtk2.0-0 is already the newest version.
libgtk2.0-0 set to manually installed.
libgtk2.0-dev is already the newest version.
libgtk2-perl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
rich@debian:~/Programs/youtube-viewer-master$ perl Build.PL --gtk2Checking prerequisites...
  requires:
    !  Gtk2 is not installed

Checking optional features...
fixed_width_support....disabled
  requires:
    ! Unicode::GCString is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.

**Comment by mrkapqa** [comment]
Hello Trizen,

tried today and i am still incuring in this error (gtk2. not found)


please see

Can't locate Gtk2.pm in @INC (you may need to install the Gtk2 module) (@INC contains: /home/rich/perl5/perlbrew/perls/perl-5.30.1/lib/site_perl/5.30.1/x86_64-linux-thread-multi-ld /home/rich/perl5/perlbrew/perls/perl-5.30.1/lib/site_perl/5.30.1 /home/rich/perl5/perlbrew/perls/perl-5.30.1/lib/5.30.1/x86_64-linux-thread-multi-ld /home/rich/perl5/perlbrew/perls/perl-5.30.1/lib/5.30.1).Linux
BEGIN failed--compilation aborted.


sudo apt-get install libgtk2.0-0 libgtk2-perl libgtk2.0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgtk2.0-0 is already the newest version.
libgtk2.0-dev is already the newest version.
libgtk2-perl is already the newest version.

**Comment by trizen** [comment]
Hi. With perlbrew, you will have to build Gtk2 from source:

```console
perlbrew use 5.30.1
cpan Gtk2 --force
```

**Comment by mrkapqa** [comment]
Thank you, it functions!


on another computer, however, it seems less so (Mac OS X)


cpan install Gtk2 --force
Reading '/Users/rich/.cpan/Metadata'
  Database was generated on Sun, 13 Sep 2020 11:17:03 GMT
Running install for module 'Gtk2'
Checksum for /Users/rich/.cpan/sources/authors/id/X/XA/XAOC/Gtk2-1.24993.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring X/XA/XAOC/Gtk2-1.24993.tar.gz with Makefile.PL
Package gtk+-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-2.0' found
 at Makefile.PL line 77.
*** can not find package gtk+-2.0 >= 2.0.0
*** check that it is properly installed and available in PKG_CONFIG_PATH
 at Makefile.PL line 77.
No 'Makefile' created  XAOC/Gtk2-1.24993.tar.gz
  /Users/rich/perl5/perlbrew/perls/perl-5.20.1/bin/perl Makefile.PL -- NOT OK
Warning: Cannot install --force, don't know what it is.
Try the command

    i /--force/

to find objects with matching identifiers.


does this mean that cpan is trying to install a too old version of gtk2?

**Comment by trizen** [comment]
The Perl module [Gtk2](https://metacpan.org/pod/Gtk2) requires the system [gtk2](https://www.gtk.org/) library, which seems to not be installed.

**Comment by mrkapqa** [comment]
hello ,
is it possible to receive a new api key please?
it seems it has expired.
am willing to pay for it if necessary.
thank you.
