### ISSUE TITLE
no mplayer listed as video-player

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#329]
Hello ,

i'd like to add Mplayer as VideoPlayer.
(on older system it seems the only viable option)

could you please help me with the correct settings?

Thank you very much.

**Comment by trizen** [comment]
Hello,

The `mplayer` entry should be:

```perl
                             mplayer       => {
                                                arg => "-prefer-ipv4 -title *TITLE*",
                                                audio => "-audiofile *AUDIO*",
                                                cmd => "mplayer",
                                                fs => "-fs",
                                                novideo => "-novideo",
                                                srt => "-sub *SUB*",
                                              },
```

The support for `mplayer` has been removed from `youtube-viewer` because `mplayer` cannot play some videos and there are some weird bugs when a video is paused for a few minutes. Therefore, `mpv` is recommended instead.

(sorry for the late reply)
