### ISSUE TITLE
[Feature Request] reverse full results list

### ISSUE THREAD

**Issue by TheKevJames** [trizen/youtube-viewer#330]
(this feature may already exist and I just can't find it -- please let me know if so!)

As far as I can tell, the only way to reverse results is via the `-B` feature which seems to operate on a per-page basis. It would be great if we could reverse the _pages of results themselves_, eg. so you could watch your likes in order from oldest to newest.

**Comment by trizen** [comment]
This option, as far as I know, is not provided by the YouTube API.

**Comment by TheKevJames** [comment]
> In fact, it may be possible to calculate the page number from the number of total results and jump to the last page. I may add an option for this in the next few days. Thanks for the request.

I think this would pretty much solve my issue, and especially if there was the ability to have a `:app` (auto-previous-page) [maybe `:abp` auto-back-page to line up with `:n` and `:b`?] option in addition to `:anp`. I'm not quite sure how this might necessarily play out with search results, but for predefined playlists, at least, I imagine calculating the total page count would make this all possible.

**Comment by trizen** [comment]
The STDIN option `:page=i` is available starting with version 3.7.8. For last page, we have `:page=last` or `:end`.

There is no `:app` at the moment, but we can use `-B`, which will apply `:back` until it reaches the first page.

See also:

* https://stackoverflow.com/questions/17821089/youtube-api-retrieve-results-specific-page
* https://stackoverflow.com/questions/25918405/youtube-api-v3-page-tokens
* https://stackoverflow.com/questions/25079501/youtube-data-api-version-3-pagination

**Comment by TheKevJames** [comment]
Thanks, this seems to be working wonderfully! `:end` and `-B` are doing exactly what I was hoping for. Thanks again!
