### ISSUE TITLE
Regex impaired

### ISSUE THREAD

**Issue by SlidingHorn** [trizen/youtube-viewer#335]
So I know nothing about regex, but I'd like to be able to narrow down my searches a little.

How would I go about pulling videos that must contain wordA, but must also not contain wordB?

(e.g.  I want to look for videos where the title contains "linux", but I'm not interested in "kali" linux)

**Comment by trizen** [comment]
Unfortunately, the YouTube API does not provide support for this.

**Comment by trizen** [comment]
Sorry, I was wrong. There is support for this:

> Your request can also use the Boolean NOT (-) and OR (\|) operators to exclude videos or to find videos that are associated with one of several search terms. For example, to search for videos matching either "boating" or "sailing", set the q parameter value to boating\|sailing. Similarly, to search for videos matching either "boating" or "sailing" but not "fishing", set the q parameter value to boating\|sailing -fishing. Note that the pipe character must be URL-escaped when it is sent in your API request. The URL-escaped value for the pipe character is %7C.

Therefore, if you want to search for "linux", but excluding results that contain "kali", then you can use:

```
youtube-viewer "linux -kali"
```
