### ISSUE TITLE
Browsing Videos from Youtube startpage

### ISSUE THREAD

**Issue by tbsmn** [trizen/youtube-viewer#337]
Hi, I started to use youtube-viewer for a few weeks now and I like it very much, awsome work!

I was wondering if there is a way to show the videos from the youtube startpage for browsing instead of searching fo a specific video?

**Comment by trizen** [comment]
Thanks! I added support for trending videos in https://github.com/trizen/youtube-viewer/commit/b39e68ca49c5edf1c3dbfe0f2986c6978e39955c, provided by the "Trending" category on `gtk3-youtube-viewer`.

To get trending videos from your region, set `regionCode` to a ISO 3166-1 alpha-2 country code (e.g. "RU" for Russia).

**Comment by tbsmn** [comment]
Thank you! That's great. Can't wait for the next release to test it ;-)

**Comment by trizen** [comment]
It's possible to test it right now, using the following commands:

```console
    cd /tmp
    wget https://github.com/trizen/youtube-viewer/archive/master.zip -O youtube-viewer-master.zip
    unzip -n youtube-viewer-master.zip
    cd youtube-viewer-master/bin
    perl -pi -ne 's{DEVEL = 0}{DEVEL = 1}' {gtk2-,gtk3-,}youtube-viewer
    ./gtk3-youtube-viewer
```

In the "Categories" tab, double-click on "Trending".

**Comment by tbsmn** [comment]
I already tried that.
But I get this error.

`Can't locate Gtk3.pm in @INC (you may need to install the Gtk3 module) (@INC contains: ../lib /Users/myusername/perl5/lib/perl5/5.18.4/darwin-thread-multi-2level /Users/myusername/perl5/lib/perl5/5.18.4 /Users/myusername/perl5/lib/perl5/darwin-thread-multi-2level /Users/myusername/perl5/lib/perl5 /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.4/darwin-thread-multi-2level /Library/Perl/Updates/5.18.4 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at ./gtk3-youtube-viewer line 34.
BEGIN failed--compilation aborted at ./gtk3-youtube-viewer line 34.
`

I am on MacOS and installed the previews version with homebrew, guess it has something todo with that. I probably will have to install the dependencies via perl first. But i fear that this would get me in some trouble with the previuos hombrew installation. I'm relatively new to this stuff.

**Comment by tbsmn** [comment]
OK I managed to get the dependencies to work and run `./youtube-viewer -c`
But I get this categories and can't see one with "Trending"

 1. Film & Animation                         (id: 1)
 2. Autos & Vehicles                         (id: 2)
 3. Music                                    (id: 10)
 4. Pets & Animals                           (id: 15)
 5. Sports                                   (id: 17)
 6. Travel & Events                          (id: 19)
 7. Gaming                                   (id: 20)
 8. People & Blogs                           (id: 22)
 9. Comedy                                   (id: 23)
10. Entertainment                            (id: 24)
11. News & Politics                          (id: 25)
12. Howto & Style                            (id: 26)
13. Education                                (id: 27)
14. Science & Technology                     (id: 28)
15. Trailers                                 (id: 44)


The Trailer Category seams to be new I don't get this when using the 3.7.7 release version. Any Ideas?

**Comment by trizen** [comment]
In `youtube-viewer`, there is the `--trending` option.

**Comment by tbsmn** [comment]
This works! Thank you very much!
