### ISSUE TITLE
Can't locate LWP/Authen/Bearer.pm

### ISSUE THREAD

**Issue by ZaxonXP** [trizen/youtube-viewer#338]
I used the latest version of `gtk-youtube-viewer` and did the search. Then I noticed that on the terminal the following error was displayed:
```
Can't locate LWP/Authen/Bearer.pm in @INC (you may need to install the LWP::Authen::Bearer module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/share/perl/5.28.1/LWP/UserAgent.pm line 404
```
Strangely I could not find this `LWP::Authen::Bearer` module in CPAN repository. 

How to fix this?

Regards,
Piotr

**Comment by trizen** [comment]
It just an harmless warning from `LWP::UserAgent`. It can be safely ignored.
