### ISSUE TITLE
No streaming URL has been found...

### ISSUE THREAD

**Issue by gcbork** [trizen/youtube-viewer#340]
Exactly the same as bug #323
My version is 3.7.7 on Ubuntu 18.04
Thanks

**Comment by trizen** [comment]
For what video? Is the issue also reproducible with the latest version? (3.7.9)

Try to install "youtube-dl" to see if that fixes the issue.

**Comment by gcbork** [comment]
It happens for any video that a search would return.
I will try your suggestions. Sorry I wasn’t aware that there is a newer version.
Thanks.



Saturday, October 10, 2020, 02:17 -0400 from notifications@github.com  <notifications@github.com>:
