### ISSUE TITLE
No longer working on fedora ("Compilation failed")

### ISSUE THREAD

**Issue by aadilayub** [trizen/youtube-viewer#341]
Hi, I'm using Fedora 32, and since running a `sudo dnf update` (which included an update to `youtube-dl`) last week, I have not been able to get youtube-viewer to work.

Here is the error I get:
```
❯ youtube-viewer
Can't locate Memoize.pm in @INC (you may need to install the Memoize module) (@INC contains: /usr/local/lib64/perl5/5.30 /usr/local/share/perl5/5.30 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /usr/share/perl5/vendor_perl/WWW/YoutubeViewer.pm line 7.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/WWW/YoutubeViewer.pm line 7.
Compilation failed in require at /usr/bin/youtube-viewer line 77.
BEGIN failed--compilation aborted at /usr/bin/youtube-viewer line 77.

```

**Comment by trizen** [comment]
The Memoize Perl module is needed: https://metacpan.org/pod/Memoize

Normally, this module should be included with Perl itself, but it seems that this is not the case in Fedora, which needs to be installed separately.
