### ISSUE TITLE
[Question] [mpv] Is it possible to set titles based on the video ? 

### ISSUE THREAD

**Issue by Silipwn** [trizen/youtube-viewer#342]
Normally while playing music through `mpv`, `youtube-dl` accurately sets the name based on the URL, but while playing the music through `youtube-viewer`, the title is set to a big URL 
`mp4&gir=yes&clen=6645316&dur=225.000&lmt=1471615573137899&mt=1602607374&fvip=5&keepalive=yes...(removed)`
Is there anyway to change this behaviour?

**Comment by trizen** [comment]
Yes, by replacing `--title=*TITLE*` with `--force-media-title=*TITLE*` in the configuration file for the `mpv` player.
