### ISSUE TITLE
BUG: Quiet and really quiet flags leaves partial downloads.

### ISSUE THREAD

**Issue by ZaxonXP** [trizen/youtube-viewer#344]
Version 3.8.0

If you try to download the link without `-q` or `--really-quiet` flags then it will download correctly (`*.opus` file):
```
youtube-viewer -A -noI -d --resolution=audio https://www.youtube.com/watch?v=6Wz6T8LqtoY
```
But if you add one of the flag then the downloaded file will be with `*.part` filename:
```
youtube-viewer --really-quiet -A -noI -d --resolution=audio https://www.youtube.com/watch?v=6Wz6T8LqtoY
```

**Comment by trizen** [comment]
Thanks for reporting! It seems to be a [lwp-download](https://metacpan.org/pod/distribution/libwww-perl/bin/lwp-download) bug. Workaround committed [here](https://github.com/trizen/youtube-viewer/commit/62a1b438ecdd8b376697b4ce685316c875c2c9a1).

An alternative solution would be to install [wget](https://www.gnu.org/software/wget/) and set `download_with_wget => 1` in the config-file, as it does not have this issue.
