### ISSUE TITLE
[Feature request] Local playlists

### ISSUE THREAD

**Issue by rgasc** [trizen/youtube-viewer#345]
Hey, I thought of a new feature which would be nice to have, which is to be able to obtain videos from a local playlist instead of a URL or ID. So after viewing the code a bit I noticed a similar feature, which is the watched history because this uses the watched.txt file to obtain videos. I basically copied this code and used this for obtaining a local playlist from a file.

The feature can be viewed here as a tag [https://github.com/rgasc/youtube-viewer/releases/tag/3.8.1](https://github.com/rgasc/youtube-viewer/releases/tag/3.8.1) and the commits are here so you can see the code [https://github.com/rgasc/youtube-viewer/commits/3.8.1](https://github.com/rgasc/youtube-viewer/commits/3.8.1).

I just thought I'd share this with you because even though I think the code is dirty (I didn't know Perl before I found your project), it is a small feature I preferred and maybe you could use the code or the idea itself somehow.

**Comment by trizen** [comment]
Thanks! Implemented in https://github.com/trizen/youtube-viewer/commit/c5685481709894c0b715c689ace63e70c5b59449.
