### ISSUE TITLE
Setting the MPV title to *ID* or *URL* in the configuration file causes videos to not play.

### ISSUE THREAD

**Issue by ggtylerr** [trizen/youtube-viewer#348]
I'm not exactly sure why this behavior happens (since no errors seem to pop up in debug mode) but if the user sets their configuration like so:
```
...
video_player_selected => "mpv",
video_players         => {
    ...
    mpv => {
        arg => "--really-quiet --title=*ID* --no-ytdl",
        audio => "--audio-file=*AUDIO*",
        cmd => "/usr/bin/mpv",
        fs => "--fullscreen",
        novideo => "--no-video",
        srt => "--sub-file=*SUB*",
    },
    ...
},
...
```
...then videos just don't play. This happens in both the GTK and CLI versions, and also means you can't run mpv scripts that need the youtube id to function (Like [SponsorBlock](https://github.com/po5/mpv_sponsorblock), although I'm not entirely sure if it can work with a forced title rather than a filename.) This might also happen with other tokens, but the only one I know it happens in is both \*ID\* and \*URL\*.

**Comment by trizen** [comment]
to fix this, insert `*VIDEO*` in the value for `arg` (after `--no-ytdl`).

This behavior is intentional, for allowing the streaming of a video by YouTube URL, by using either `*ID*` or `*URL*` in the argument line, in which case the `*VIDEO*` value is not implicitly passed to player.
