### ISSUE TITLE
Feature Request: Toggle between video and audio playing

### ISSUE THREAD

**Issue by HawaiinPizza** [trizen/youtube-viewer#349]
Youtube-viewer doesn't allow you to switch to video after you play a video in audio mode. I managed to create a work around, but it only works in the compiled version, and I'm not sure how to make it work wtih the actual source code.
```perl
        'novideo|no-video|n|audio!'          => \$opt{novideo},
        'video'                               => \$opt{video},
```
```perl
sub get_streaming_url {
    my ($video_id) = @_;

    my ($urls, $captions, $info) = $yv_obj->get_streaming_urls($video_id);

    if (not defined $urls) {
        return scalar {};
    }

    # Download the closed-captions
    my $srt_file;
    if($opt{video} and $opt{novideo}){
            delete $opt{video};
            delete $opt{novideo};
    }
...
```

**Comment by trizen** [comment]
This is intentional in order to save bandwidth. For video+audio, start the video normally, then switch to audio mode from the video player.
