### ISSUE TITLE
403 Forbidden: videoCategories and search googleapis

### ISSUE THREAD

**Issue by elig0n** [trizen/youtube-viewer#351]
Using my own API key and trying to search something yields:

```
No results...

=>> Previous warnings:
[Sun Dec 27 07:16:27 2020]: [403 Forbidden] Error occurred on URL: https://www.googleapis.com/youtube/v3/videoCategories?hl=en_US&key=[...]&maxResults=10&part=snippet&prettyPrint=false&regionCode=US
[Sun Dec 27 07:16:28 2020]: [403 Forbidden] Error occurred on URL: https://www.googleapis.com/youtube/v3/search?key=[...]&maxResults=10&part=snippet&prettyPrint=false&q=asdf&safeSearch=none&type=video
```
YouTube Viewer 3.8.0

**Comment by trizen** [comment]
Use the `--debug` option to see the URL with the API key included:

```
youtube-viewer --debug test
```

Copy-paste the URL in a browser to check if that works, or to see if there is any error message.

Make sure the API key is correct.

**Comment by elig0n** [comment]
Thanks. The URL showed an exceeded quota error and since I haven't used that key for a while it it is possible that Google blocked it, so [I had to regenerate API key with a new project](https://stackoverflow.com/a/63211212).
