### ISSUE TITLE
mpv scripts when watching videos

### ISSUE THREAD

**Issue by ChausseBenjamin** [trizen/youtube-viewer#352]
Some mpv scripts do not run when using youtube-viewer.
For example, [Sponsorblock_mpv](https://github.com/po5/mpv_sponsorblock) is an awesome plugin that skips sponsorspots in youtube videos. Yet, it doesn't work.
I suspect that it has to do with the fact that a videofile is being passed to mpv instead of the video url. Is there a way around this?

Thanks!

**Comment by trizen** [comment]
Hi! In order to pass the YouTube video URL to `mpv`, try adding the following player entry in the configuration file:

```perl
  video_player_selected  => "mpv_native",
  video_players => {

        # ...
        mpv_native    => {
                  arg => "--really-quiet *URL*",
                  cmd => "/usr/bin/mpv",
                  fs => "--fullscreen",
                  novideo => "--no-video",
                  srt => "--sub-file *SUB*",
                },
        #...
  },
```

**Comment by trizen** [comment]
A small hack to no longer pass the `*URL*` to `mpv`, but still having sponsorblock working:

1. Place [mpv_sponsorblock_minimal](https://codeberg.org/jouni/mpv_sponsorblock_minimal/src/branch/master/sponsorblock_minimal.lua) in `~/.config/mpv/scripts`.
2. Add the following entry in the list of urls:  `"[?&]v=([%w-_]+).*"` inside the function `file_loaded()`

And now in the configuration of `youtube-viewer`, change the `mpv` section to:

```perl
mpv => {
        arg     => "--really-quiet --force-media-title=*TITLE* --no-ytdl *VIDEO*\\&v=*ID*",
        audio   => "--audio-file=*AUDIO*",
        cmd     => "mpv",
        fs      => "--fullscreen",
        novideo => "--no-video",
        srt     => "--sub-file=*SUB*",
       },
```
