### ISSUE TITLE
ADD option to automatically like played videos

### ISSUE THREAD

**Issue by allanlaal** [trizen/youtube-viewer#356]
I use an autolike plugin in the browser and I've found autoLiking videos you watch ≥50% trains the Youtube Algorithm better

**Comment by trizen** [comment]
Added the `autolike_watched` config-option (disabled by default), which will automatically like a video after watching it.

However, be aware that liking a video is [a bit costly](https://developers.google.com/youtube/v3/docs/videos/rate): 50 units of quota per like (half the cost required for a search).
