### ISSUE TITLE
[Feature request] Select custom layout from command line/internal

### ISSUE THREAD

**Issue by ZaxonXP** [trizen/youtube-viewer#359]
It would be nice to have an option to select custom layout or use the program default. Currently it is only possible to change it in the config file or comment it out to get the default. Could you please add some command line options for this?

Regards,
Piotr

**Comment by trizen** [comment]
The `--custom-layout=s` flag is still available, but, for some reason, was undocumented:

```console
youtube-viewer --custom-layout='*NO*. *TITLE* -- *TIME*' test
```

**Comment by ZaxonXP** [comment]
Thanks for fast reply. Indeed, it was not in the docs. :)
