### ISSUE TITLE
Undefined subroutine error

### ISSUE THREAD

**Issue by zensubz** [trizen/youtube-viewer#363]
The latest git commit da345e4 throws an error like this when I try to invoke gtk-youtube-viewer from terminal:

```
Undefined subroutine &File::Basename::basename called at /usr/share/perl5/vendor_perl/WWW/YoutubeViewer/Utils.pm line 549.
Undefined subroutine &File::Basename::basename called at /usr/share/perl5/vendor_perl/WWW/YoutubeViewer/Utils.pm line 549. at /usr/bin/gtk-youtube-viewer line 452.
Undefined subroutine &File::Basename::basename called at /usr/share/perl5/vendor_perl/WWW/YoutubeViewer/Utils.pm line 549.
```

The first run goes fine without any issues (only the api.json and gtk-history.txt files were kept in the ~/.config/youtube-viewer folder). But any subsequent call fails to start gtk-youtube-viewer, and throws the above error. 

Just to highlight, the commit  b2f9af7 doesn't throw any subroutine errors mentioned above (I need to start afresh keeping only the api.json and gtk-history.txt files).

Just wanted to bring this to your kind attention, and if possible, provide a fix. Thanks.

**Comment by trizen** [comment]
Thanks for reporting. Should be fixed in the above commit.

**Comment by zensubz** [comment]
Thanks, just wanted to confirm that the commit cf2db12 has solved the issue.
