### ISSUE TITLE
Can't Get Logged In

### ISSUE THREAD

**Issue by VidarrKerr** [trizen/youtube-viewer#368]
This is probably a very simple question to answer, but I couldn't figure it out. 

{
    "key":           "WHAT GOES HERE?",
    "client_id":     "I GOT THIS PART RIGHT.apps.googleusercontent.com",
    "client_secret": "AND I GOT THIS PART RIGHT TOO--0O-otbdPZQR3FLVr"
}

THANK YOU!!!!

VK

**Comment by trizen** [comment]
See the discussion on: https://github.com/trizen/youtube-viewer/issues/353#issuecomment-763574106

**Comment by VidarrKerr** [comment]
Yeah, I did that already.  It doesn't show where that "key" info comes from.

**Comment by trizen** [comment]
Maybe this will help: https://www.videoconverterfactory.com/kodi/youtube-api-key.html

**Comment by VidarrKerr** [comment]
Yep, that one did it. Thank You!

**Comment by VidarrKerr** [comment]
It sucks you have to be "logged in" for this to work.  I'll still use it, but I am going to check out these other pipe-viewer/straw-viewer type apps.  I was reading about them last night and then came across this video:

ytfzf - Search Youtube via FZF Dmenu or Rofi - Linux CLI GUI

Going to check some of that out today.  Eventually, I'd like to be able to search ALL video platforms inside one app running in a terminal. Youtube, Peertube, Bitchute, lbry... 

Thank You.

**Comment by trizen** [comment]
Only an API key is need. Logging in is optional. But, yes, [pipe-viewer](https://github.com/trizen/pipe-viewer) is an alternative to `youtube-viewer` that does not require an API key.

[ytfzf](https://github.com/pystardust/ytfzf) is also a great alternative.

No problem.
