### ISSUE TITLE
[Feature Request]: Compatibility with umpv script

### ISSUE THREAD

**Issue by Silipwn** [trizen/youtube-viewer#373]
Hi, 
I was trying to modify the existing mpv to run with `umpv` (Wrapper Script around mpv, which allows to run it as a single window instance) but it tends to give a lot of other parameters to the [Python script](https://raw.githubusercontent.com/mpv-player/mpv/master/TOOLS/umpv) . 
I was wondering if it will possible to just directly pass the Youtube URL to mpv. 
Any directions to look at would be really helpful.

**Comment by trizen** [comment]
Hi. It's possible to pass the special token `*URL*` to `umpv`.

Something like this:

```perl
                                     umpv    => {
                                                        arg => "*URL*",
                                                        cmd => "umpv",
                                                        fs => "--fullscreen",
                                                        novideo => "--no-video",
                                                        srt => "--sub-file=*SUB*",
                                                      },
```
