### ISSUE TITLE
404 Not Found error

### ISSUE THREAD

**Issue by zensubz** [trizen/youtube-viewer#374]
I have noticed the following error in almost all videos that I play in terminal (via gtk-youtube-viewer) - just to give an example, here is a link:

```[404 Not Found] Error occurred on URL: https://www.youtube.com/get_video_info?video_id=MHG5LBhwndU&el=detailpage&ps=default&eurl=&gl=US&hl=en```

The video(s) play in most cases without throwing any further error (but this line is displayed on top).

I use git commit 0b54754. Thanks.

**Comment by trizen** [comment]
It's either an YouTube error or an intentional protection by YouTube.

However, we already use `youtube-dl` as a fallback, or invidious if `youtube-dl` is not available or it fails too.

**Comment by zensubz** [comment]
Thanks a lot for fixing this issue. This has also solved another problem that I had, in the sense some videos were simply not playing (though youtube-dl/mpv would try to start, but would silently die without throwing any warning/error).
