### ISSUE TITLE
When did -C / --colorful get removed?

### ISSUE THREAD

**Issue by SlidingHorn** [trizen/youtube-viewer#378]
This was a great feature that made it very easy for me to read the results and see which videos I'd already watched, etc.

**Comment by trizen** [comment]
Option `-C` has been removed in https://github.com/trizen/youtube-viewer/commit/282c03302d0d68f0613c6361e9040013b1b6f993

The format of results can now be customized by changing the values of "custom_layout*" config-options.

**Comment by SlidingHorn** [comment]
Aw, dang - I had to do some issue searching to find out how that works, and I found your reply [here](https://github.com/trizen/youtube-viewer/issues/320#issuecomment-631933026_) (...and after typing half of my comment, in the man page 🤦) - Is there no longer an option to have "new" videos show up differently than previously watched videos? (e.g. making only the unwatched videos bold, etc.)

I don't see any token signifying a difference.

**Comment by trizen** [comment]
To highlight watched videos across sessions, make sure to have in the config-file:

```perl
  highlight_color               => "bold",
  highlight_watched             => 1,
  watch_history                 => 1,
```

**Comment by SlidingHorn** [comment]
> To highlight watched videos across sessions, make sure to have in the config-file:
> 
> ```perl
>   highlight_color               => "bold",
>   highlight_watched             => 1,
>   watch_history                 => 1,
> ```

Awesome, thanks!
