### ISSUE TITLE
Setting cookies query

### ISSUE THREAD

**Issue by celtichawk** [trizen/youtube-viewer#384]
Heya, simple questions relating to cookies.

1. I see in the .conf it's undef, but when I try putting the path to my cookies it brings up a regexp error on startup.
2. Do cookies work like they do for other apps, giving me the ability to download/play videos without an API key or logging in?

**Comment by trizen** [comment]
The cookie file must be a `# Netscape HTTP Cookie File`. Same format as `youtube-dl` requires.

Here's a Firefox extension that can extract the cookies in the required format: https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/

Passing a cookie is only useful to overcome the `429: Too Many Requests` issue. And maybe also in viewing age-restricted videos in Europe. But, other than that, there is no benefit in passing a cookie. An API key will still be needed.

See also: https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl

Alternatively, you can try [pipe-viewer](https://github.com/trizen/pipe-viewer), which is a fork of `youtube-viewer` that does not require an API key. Passing a cookie to `pipe-viewer` will behave a little bit like being logged in, allowing you to see unlisted playlists from your account.
