### ISSUE TITLE
[SUPPORT] How can I create a queue and add more videos while I watch videos

### ISSUE THREAD

**Issue by jso8910** [trizen/youtube-viewer#385]
Trying to switch from youtube.com to this and the only feature i *really* care about in youtube is the queue. I need to be able to start watching a video then add more as I continue browsing for more videos. I would rather not have to create new playlists every time I want to use YouTube.

**Comment by trizen** [comment]
Take a look at task-spooler, by placing "tsp" in front of the video player command in the config file.

See also: https://m.youtube.com/watch?v=I4tfHUmklWo

**Comment by jso8910** [comment]
So I put `tsp` in front of the command (right here I assume this is right)
```
  video_players                 => {
                                     mpv => {
                                              arg => "--really-quiet --force-media-title=*TITLE* --no-ytdl *VIDEO*",
                                              audio => "--audio-file=*AUDIO*",
                                              cmd => "tsp /usr/bin/mpv",
                                              fs => "--fullscreen",
                                              novideo => "--no-video",
                                              srt => "--sub-file=*SUB*",
                                            },
```
However it complains that the tsp command is not found.

**Comment by jso8910** [comment]
Nevermind installed task-spooler and it works like a charm!

**Comment by jso8910** [comment]
Sorry for replying again but now I have the issue that I can't view comments or anything because the video is no longer playing in youtube-viewer's point of view. Any way to fix that whilst still using tsp?

**Comment by trizen** [comment]
An alternative to `tsp` would be to use `:q=i` option to enqueue videos for playing, followed by `:pq` which will start playing the enqueued videos.

**Comment by jso8910** [comment]
Only issue with that is that iirc you can't add more videos to it as you go
