### ISSUE TITLE
youtube-viewer does not pick up options from (mpv.conf)?

### ISSUE THREAD

**Issue by mrkapqa** [trizen/youtube-viewer#387]
Hello ,

i have an mpv.conf that i would like to use 
to limit videos in 720p and to upconvert them with help of svp4linux to 60/75fps videos.

it seems that youtube-viewer does not pick up the mpv.conf in .config/mpv/mpv.conf

the inserted options are

`--hwdec=auto-copy
--input-ipc-server=/tmp/mpvsocket 
ytdl-format="[height<720]/best"
`

do i need to change something in the youtube-viewer.conf?

thank you very much!

**Comment by trizen** [comment]
Hi,

By default, `youtube-viewer` extracts the YouTube URLs on its own, the `youtube-dl` options from `mpv.conf` do not apply.

To use `mpv` + `youtube-dl` to play the videos, set in the configuration file (inside the `video_players` section):

```perl
 mpv    => {
        arg => "*URL*",
        cmd => "/usr/bin/mpv",
        fs => "--fullscreen",
        novideo => "--no-video",
        srt => "--sub-file=*SUB*",
      },
```
