### ISSUE TITLE
append-arg multiple args not working

### ISSUE THREAD

**Issue by thenoobtester** [trizen/youtube-viewer#392]
Hi,

first this is an awesome project and makes it really fun to watch youtube videos :)

I have a question, when I run :

`./youtube-viewer url --append-arg="--cache-secs=20 --autofit=1024 --geometry=50%:50%" `

It works perfectly, --append-arg=, that is, however when I do the same in interactive mode (i.e. search and do for example` 1 -3 --append-arg="--cache-secs=20 --autofit=1024 --geometry=50%:50%"` ) it doesn't. It fails silently and I'm brought back to the search input/results page.

But it works with only one, e.g. `1 -3 --append-arg="--cache-secs=20"`.

Could anyone please help with this?

Thank you.

**Comment by trizen** [comment]
Hi. This issue has been fixed in https://github.com/trizen/youtube-viewer/commit/4c2930f23b84f09f5148e96b47ba53ea461575a5. Thanks for reporting!

**Comment by thenoobtester** [comment]
Thank you :+1:
