### ISSUE TITLE
Stay logged in

### ISSUE THREAD

**Issue by plasmoduck** [trizen/youtube-viewer#393]
How do I stay logged in? When I loggin and paste my 0auth key and choose remember me, but after some time I get looked out. Like after an hour or so, havent really timed it. But it doesnt stay logged in.

**Comment by trizen** [comment]
Make sure `youtube-viewer` has the permission to create the file `~/.config/youtube-viewer/reg.dat`. This is where the encrypted tokens are kept in.

**Comment by plasmoduck** [comment]
Thanks I patched it. Closing this issue.
