### ISSUE TITLE
[Feature Request] Readline or equivalent for search prompt in terminal.

### ISSUE THREAD

**Issue by tinesife94** [trizen/youtube-viewer#395]
It would be nice for the program to have support for GNU Readline or some equivalent tool. That would allow access the search history, make changes and corrections efficiently, etc.

**Comment by trizen** [comment]
This is already implemented, using https://metacpan.org/release/Term-ReadLine-Gnu

Make sure to have that module installed and set `history => 1` in the configuration file.

**Comment by tinesife94** [comment]
I installed the package on my system and changed the config file. It's working great, thank you.
