### ISSUE TITLE
[feature request] extract title of video

### ISSUE THREAD

**Issue by ghost** [trizen/youtube-viewer#4]
Hi

I use youtube-viewer when opening a youtube link in urxvt. Now I want to make a script to be able to select the following action (watch or download the video) using dmenu. For this it would be nice to have the ability to get the title of the video. For now I have to use youtube-dl for that, which I want to avoid in the near future, because I only want to use youtube-viewer for everything.

Thanks and best
Army

**Comment by trizen** [comment]
Good news: the `--extract=s` option has been added which can extract information about videos using a special format. (see: `youtube-viewer -T`).

Example: 
```shell
youtube-viewer --no-interactive --extract '*TITLE*' [URL]
```
