### ISSUE TITLE
Youtube is now throttling every single third party app that has access to it

### ISSUE THREAD

**Issue by pitsi** [trizen/youtube-viewer#402]
The following applies to pipe-viewer as well.

As of this Wednesday, October 6th 2021, every app that accesses youtube, be it via api or scraping it as a web page, is throttled to speeds of maybe 20kb/s! This makes any video an unwatchable slideshow, even on low resolutions like 360p. 
And it happens on other apps too. I first noticed it on kodi's youtube addon, then on your apps and finally on ytfzf by pystartdust. Yes, I use a lot of third party apps because I hate watching youtube in a browser. I have also removed google's garbage app of youtube from my phone. 

So far, the only available workaround for this mess is yt-dlp's (a fork of youtube-dl) 
`--extractor-args youtube:player_client=android`
but youtube-viewer does not use this. In fact, I think it does not even use youtube-dl.

p.s. The forementioned issue does not happen on every video. 1 out of 7 or 8 videos plays fine, but the remaining ones are still slideshows. Some users have reported that after ~5 attempts on the same video they also get it to play fine. Unfortunately for me, I am not that patient.

**Comment by trizen** [comment]
I pushed a workaround for this a few days ago: https://github.com/trizen/youtube-viewer/commit/caa0fc484de1a4c2af71e8b9335277b7f8132d32

When `force_fallback` is set to `1`, in order for `youtube-viewer` to use `yt-dlp` instead of `youtube-dl`, change the value of `ytdl_cmd` to "yt-dlp" in the configuration file.

**Comment by pitsi** [comment]
So it does use youtube-dl. Good to know, because I am will probably remove it by the end of next month because it seems dead from upstream. 
Thank you for the quick fix. Will it be added to pipe-viewer too?

Feel free to close this issue whenever you like.

**Comment by trizen** [comment]
I will release a new version soon with the better workaround: https://github.com/trizen/youtube-viewer/commit/8853969a240189b6ec61e5226c2ac19a3d38ccbe (which no longer depends on `youtube-dl` or `yt-dlp`).
