### ISSUE TITLE
Search channels without having to pass in argument

### ISSUE THREAD

**Issue by trames57** [trizen/youtube-viewer#404]
I am new to youtube-viewer.  I did not see a way to search for channels unless I passed in the -sc argument.  Perhaps a new option could be added to the Base search like **:ch distrotube** which would take me to the search channel results page like I passed in the -sc  argument. 

Thanks.

**Comment by trizen** [comment]
Welcome! The command-line argument `-sc` can also be used in user input:

Example:

```
[...]

=>> Select one or more videos to play (:h for help)
> -sc distrotube

[channels results for <distrotube>]
```

**Comment by trames57** [comment]
Awesome!  Thanks!!
