### ISSUE TITLE
[400 Bad Request] Error occurred on URL: https://www.googleapis.com/youtube/v3/search?key=[...]&maxResults=45&part=snippet&prettyPrint=false&q=test&type=video

### ISSUE THREAD

**Issue by ZaxonXP** [trizen/youtube-viewer#412]
Today morning I got this error and I cannot use `youtube-viewer` anymore.
I tried to change the `key` `client_id` and `client_secret` in the `.config/youtube-viewer/api.json` to the newly generated one, but it is still the same error.

Did something changed on the YT side that `youtube-viewer` no longer works or is it only my local issue?

I made many queries today, but not exceeding the quota.

Kind regards,
Piotr

**Comment by trizen** [comment]
Run `youtube-viewer` with the `--debug` argument to see the full URL, then open it in the browser to see if there is any error message.

Probably some issue with your API key, as my API key still works fine.

Note that if you changed the values of `client_id` and `client_secret`, you will need to logout and then log back in:

```console
$ youtube-viewer --logout
$ youtube-viewer --login
```

**Comment by ZaxonXP** [comment]
With the debug flag enabled I got the info that I exceeded my quota. Updated quotas statistics shows that now. Looks like I need to make less queries per day. 

Thanks for the help.
