### ISSUE TITLE
Updated Google API Policies Causing Authorization Error

### ISSUE THREAD

**Issue by Kirfkin** [trizen/youtube-viewer#415]
Attempting to sign in today, I received the following error page:

Error 400: invalid_request

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules.
Request Details
The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
If you’re the app developer, make sure that these request details comply with Google policies.
redirect_uri: urn:ietf:wg:oauth:2.0:oob

Digging into it, Google recently made a change to their API Policies:

https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#dates-oob

I'm not sure if there's a work around. I am running 3.9.7.

**Comment by f1vefour** [comment]
Same issue on revision 3.9.9
![googlerror](https://user-images.githubusercontent.com/354289/161199115-c83de92e-54df-4b6d-922a-1fa4376977b3.png)
