### ISSUE TITLE
Permission denied for binary

### ISSUE THREAD

**Issue by illettante** [trizen/youtube-viewer#418]
Sorry, i'm a total nubcake, you may have to spoonfeed me if i don't give you the information you need. Debian 11, eeepc 901.

When I try to run youtube-viewer, I get 
```
[!] Can't open '/home/████/.config/youtube-viewer/youtube-viewer.conf' for write: Permission denied at /usr/local/bin/youtube-viewer line 475.
Can't locate '/home/████/.config/youtube-viewer/youtube-viewer.conf' at /usr/local/bin/youtube-viewer line 475.
````
 I've manually created API key _home/████/.config/youtube-viewer/api.json_  and created and added an API key, and created an empty _home/████/.config/youtube-viewer/youtube-viewer.config_.

I've tried running as sudo, but that doesn't seem to create the other files, the playlist text files etc. As sudo or as user, program launches but tells me I haven't set an API key.

I've added all the write permissions i can to the binary with chmod, no idea whether that was a useful thing to do or not.
I've clearly cooked it somehow,

Please help?

**Comment by trizen** [comment]
Try running the following command:

```
USER=$(whoami); sudo chown $USER -R ~/.config/youtube-viewer
```

-----


Alternatively, delete the config directory of `youtube-viewer`, and execute `youtube-viewer` as a user (without sudo):

```
sudo rm -rf ~/.config/youtube-viewer
youtube-viewer
```

`youtube-viewer` will automatically create the config directory with the correct permissions for the current user.

-----

Let me know if this helped.

P.S.: Never execute `youtube-viewer` with `sudo` in the future.

**Comment by illettante** [comment]
yep, 
`USER=$(whoami); sudo chown $USER -R ~/.config/youtube-viewer` sorted it.
Thanks for the tip. I think where i went wrong was i actually ran the install script as sudo. Learning experience.
