### ISSUE TITLE
[400 Bad Request] Error occurred on URL

### ISSUE THREAD

**Issue by zensubz** [trizen/youtube-viewer#421]
Hi,

I get the following errors with gtk-youtube-viewer (git commit 0f69457) when I search for videos using specific key words. For convenience, I have omitted the repeating ones:

```
[400 Bad Request] Error occurred on URL: https://www.googleapis.com/youtube/v3/videos?id=XXX&key=[...]&maxResults=50&part=contentDetails,statistics,snippet&prettyPrint=false
Use of uninitialized value in sprintf at /usr/bin/gtk-youtube-viewer line 3260.
...
...
Not a HASH reference at /usr/share/perl5/vendor_perl/WWW/YoutubeViewer/Utils.pm line 641.
Not a HASH reference at /usr/share/perl5/vendor_perl/WWW/YoutubeViewer/Utils.pm line 641. at /usr/bin/gtk-youtube-viewer line 467.
*** unhandled exception in callback:
***   Not a HASH reference at /usr/share/perl5/vendor_perl/WWW/YoutubeViewer/Utils.pm line 641.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 546.
...
...
FATAL: could not convert value 0 to enum type GtkResponseType at /usr/share/perl5/vendor_perl/Gtk3.pm line 280.
```

Please note that **XXX** is simply used as an alternative - the original api-related stuff is quite long.

It does fetch the results, but I notice few items are missed out - for example, the thumbnails and time (upload date) are not fetched. Having said this, I encounter this only on selective keywords.

Will it be possible to provide a fix for this? Thanks.

**Comment by trizen** [comment]
This happens when the API quota has been exceeded. We do have a (slow) fallback method that retrieves video info each video ID in such cases (without using the API), but there was a bug (fixed in https://github.com/trizen/youtube-viewer/commit/cb6527f50ee990a78a1b565650a6f68a0804961e), which prevented the fallback method to work correctly.

For people that make a lot of searches, I recommend https://github.com/trizen/pipe-viewer instead, which does not require an API key and thus it is not limited in the number of searches per day.

**Comment by zensubz** [comment]
Thanks @trizen for providing the fix. I have checked the search-results using commit cb6527f. The error-msgs have gone, and also thumbnails appear. One small observation, time (upload date) entry goes missing, but it appears when I select a particular video, right-click on it, select Author->Uploads, and then it brings all the info (including the upload-time).

In such cases, the following info appears, when I invoke gtk-youtube-viewer from the terminal:
```
Use of uninitialized value in sprintf at /usr/bin/gtk-youtube-viewer line 4187.
```

**Comment by trizen** [comment]
Unfortunately, the current fallback method does not provide the upload date of a video.

**Comment by zensubz** [comment]
@trizen, thanks for the fix - I can confirm that the error msgs are gone with the latest commit (24c0ca9). Just for information, this sort of thing happens only with a few typical keywords. I don't face this problem if I slightly modify them, so I think the combination of keywords, perhaps, plays some role.

I have tried the latest commit of pipe-viewer (v0.4.2 branch) - it is really awesome. Great work..!
