### ISSUE TITLE
Error parsing commandline option audio-file: option requires parameter

### ISSUE THREAD

**Issue by mikdmst1** [trizen/youtube-viewer#423]
youtube-viewer -A https://www.youtube.com/watch?v=_ihNT1AC198&list=PLC8r07jWL40tE-l_O7yMM6PxUSoqq_Neu

Error parsing commandline option audio-file: option requires parameter
Make sure you're using e.g. '--audio-file=value' instead of '--audio-file value'.
Exiting... (Fatal error)

archlinux

-------------
and simple search doesnt work...

=>> Select one or more videos to play (:h for help)
> music

[!] No video results!

=>> Select one or more videos to play (:h for help)
> shuffle

[!] No video results!

**Comment by trizen** [comment]
By default, we already use `--audio-file=*AUDIO*` for `mpv`.

Regarding the search not working, make sure the API key is correct. Additionally, execute youtube-viewer with the `--debug` argument to see if there are any errors.
