### ISSUE TITLE
Like failed with: Failed to send a positive rating ...

### ISSUE THREAD

**Issue by Flashwalker** [trizen/youtube-viewer#426]
I set ouath and token, and then i login in **gtk-youtube-viewer**, and press enter in termianl login prompt,  
but can't like the video:
```
Failed to send a positive rating to <<YA0ugEZGPUQ>>! at /home/user/perl5/bin/gtk-youtube-viewer line 1239.
```

**Comment by trizen** [comment]
This is probably related to: https://github.com/trizen/youtube-viewer/commit/77ba84a0803a15482288920185009f34c4beacea

**Comment by Flashwalker** [comment]
> This is probably related to: [77ba84a](https://github.com/trizen/youtube-viewer/commit/77ba84a0803a15482288920185009f34c4beacea) (maybe not)
> 
> If possible, install the [perl-lwp-consolelogger](https://metacpan.org/dist/LWP-ConsoleLogger) package and execute `gtk-youtube-viewer` as:
> 
> ```
> perl -MLWP::ConsoleLogger::Everywhere $(which gtk-youtube-viewer)
> ```
> 
> and then try liking a video and check what error message it outputs.

I reset app credential setting according to https://github.com/trizen/youtube-viewer/commit/77ba84a0803a15482288920185009f34c4beacea and now Like works, thanks.

Am i right, that i can't comments any more via gtk-youtube-viewer?
