### ISSUE TITLE
vlc crash when starting video through youtube-viewer

### ISSUE THREAD

**Issue by j0lle** [trizen/youtube-viewer#430]
Hello

I am running youtube-viewer on opensuse. I can search, but when I start a video, vlc immediately crashes.
vlc log says: 

`-- logger module started --
main: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
access error: HTTP connection failure
main: end of playlist, exiting
-- logger module stopped --
`

I have enabled debug in youtube-viewer, which gives me the command it tries to run: 
`-> Video type: video/webm; codecs="vp9"
-> Audio type: audio/webm; codecs="opus"
-> Command: /usr/bin/vlc --input-slave=https\:\/\/rr5\-\-\-sn\-5hnednsz\.googlevideo\.com\/videoplayback\?expire\=168emqL2oCg.......`

however, when copy/pasting the command to a seperate terminal, vlc runs just fine and the video plays...

No idea where to start looking, any help greatly appreciated!

**Comment by ItsTerm1n4l** [comment]
I know this does not fix the problem and may now work for you,
but you could try using `mpv`?

**Comment by j0lle** [comment]
Thanks, I kind of forgot to update the ticket. Switching to mpv worked perfectly! 
It was very new, and I was stuck in troubleshooting that vlc issue :-)

**Comment by ItsTerm1n4l** [comment]
np! 
shall I close the issue?

**Comment by ItsTerm1n4l** [comment]
np!
close the issue?
