### ISSUE TITLE
Error about api keys and JSON invalid character [Solved]

### ISSUE THREAD

**Issue by z3r0sTr3sS** [trizen/youtube-viewer#436]
```
[JSON]: invalid character encountered while parsing JSON string, at character offset 220 (before "\n"\n}\n") at /usr/share/perl5/vendor_perl/WWW/YoutubeViewer/ParseJSON.pm line 38.


Error: no API key has been set!

For creating/setting an YouTube API key, please see:
https://github.com/trizen/youtube-viewer#logging-in


=>> Search for YouTube videos (:h for help)
>
```
_i insert correcly keys on ~/.config/youtube-viewer/api.json_
**youtube-viewer version : 3.10.8
OS : Archlinux 
Kernel : 6.1.38-1-LTS**

**Comment by trizen** [comment]
Double-check the file `~/.config/youtube-viewer/api.json` for syntax errors, by executing the following command:

```
json_pp < ~/.config/youtube-viewer/api.json
```

**Comment by z3r0sTr3sS** [comment]
> Double-check the file `~/.config/youtube-viewer/api.json` for syntax errors, by executing the following command:
> 
> ```
> json_pp < ~/.config/youtube-viewer/api.json
> ```
yeah my bad some syntax was wrong after key "xxxxxxx 
"
thank you my mistake
