### ISSUE TITLE
No result 

### ISSUE THREAD

**Issue by mohammed777200** [trizen/youtube-viewer#440]
Hi

When I set a keyword for searching in terminal it doesn't show any result, just empty list:
 
**~ >  youtube-viewer

Error: no API key has been set!

For creating/setting an YouTube API key, please see:
https://github.com/trizen/youtube-viewer#logging-in

=>> Search for YouTube videos (:h for help)
> linux

=>> Select one or more videos to play (:h for help)
>**

thanks for any help

**Comment by trizen** [comment]
You need an YouTube API key.

For more details, please see: https://github.com/trizen/youtube-viewer#logging-in

Alternatively, try "pipe-viewer", which does not require an API key: https://github.com/trizen/pipe-viewer
