### ISSUE TITLE
I'd like a option to choose "My panel" as the default tab and list my subscriptions automatically at start

### ISSUE THREAD

**Issue by Hund** [trizen/youtube-viewer#60]
I'd like a option to choose "My panel" as the default tab and list my subscriptions automatically at start. 

Would that be possible?

**Comment by trizen** [comment]
To set a specific default tab, you need to change the `default_notebook_page`, in configuration file or preferences, to the value `0` (meaning the first tab).

Unfortunately, to list the subscriptions automatically at start it is not currently possible, but it's easy enough to just click the `Subscriptions` button or press `Tab` 3 times, then `Enter` or `Space`.

**Comment by Hund** [comment]
Oh. Didnt know that. Thanks! :)

**Comment by trizen** [comment]
No problem. :)
