### ISSUE TITLE
Rename downloaded video

### ISSUE THREAD

**Issue by waldnercharles** [trizen/youtube-viewer#61]
Does youtube-viewer have the ability to save the file as something in particular when I download it? Something other than the title of the youtube video?

If not, I'd like to open this as a feature request.

**Comment by trizen** [comment]
By adding the following entry inside the `video_players` in configuration file, you can download videos with `wget` with a custom name, by executing `youtube-viewer --player=wget`:

```perl
   wget => {
	 # download video with wget with a custom name (title-id.format)
         cmd => "wget -O *TITLE*-*ID*.*FORMAT* *VIDEO*",
    },
```

Now quite what you are asking for, but pretty close. I will try, in the future, to add an easier way for doing this.

**Comment by waldnercharles** [comment]
That's a great idea. Thanks.

**Comment by trizen** [comment]
An easier way has been added here: https://github.com/trizen/youtube-viewer/commit/ac0fed3476c3e40021bd9874b90fedaffb905b76

Usage:
      `youtube-viewer --filename '*FTITLE*-*ID*.*FORMAT*' -d [URL]` 

For more special tokens, see: `youtube-viewer -T`
