### ISSUE TITLE
Error during Build test

### ISSUE THREAD

**Issue by Jzarecta** [trizen/youtube-viewer#62]
I get the following issue when doing the Build test, using perl 5.12.3:
$ ./Build test
t/00-load.t ....... Bareword found where operator expected at /home/jza/tmp/youtube-viewer/WWW-YoutubeViewer/blib/lib/WWW/YoutubeViewer.pm line 1645, near "}er"
        (Missing operator before r?)
t/00-load.t ....... 1/1 
#   Failed test 'use WWW::YoutubeViewer;'
#   at t/00-load.t line 6.
#     Tried to use 'WWW::YoutubeViewer'.
#     Error:  syntax error at /home/jza/tmp/youtube-viewer/WWW-YoutubeViewer/blib/lib/WWW/YoutubeViewer.pm line 1645, near "}er"
# BEGIN not safe after errors--compilation aborted at /home/jza/tmp/youtube-viewer/WWW-YoutubeViewer/blib/lib/WWW/YoutubeViewer.pm line 1663.
# Compilation failed in require at t/00-load.t line 6.
# BEGIN failed--compilation aborted at t/00-load.t line 6.
Bailout called.  Further testing stopped:  
# Testing WWW::YoutubeViewer , Perl 5.012003, /usr/bin/perl5.12.3
# Looks like you failed 1 test of 1.
FAILED--Further testing stopped.

**Comment by trizen** [comment]
`YoutubeViewer.pm` requires perl>=5.14.0, while `youtube-viewer` requires perl>=5.16.0; Upgrade your Perl to the latest version and it will work.

Also, see: http://perlbrew.pl/
