### ISSUE TITLE
Signed in but still can't view age restricted content

### ISSUE THREAD

**Issue by frank604** [trizen/youtube-viewer#63]
I've logged in and saved the token.  I can't view age restricted content and having this error:

[!] Error occurred on getting info for video ID: VpXUIh7rlWI
[*] Reason: This video may be inappropriate for some users.
Use of uninitialized value in hash element at /usr/share/perl5/vendor_perl/WWW/YoutubeViewer/Itags.pm line 129, <FIN> line 5.

Latest install from git.  Help?

**Comment by trizen** [comment]
As the reason says, that video is considered inappropriate for some users. There are more factors involved, such as age and location. Check your Google profile to see if the age is set properly.
