### ISSUE TITLE
Are videos to mp3 format above 128kbs possible?

### ISSUE THREAD

**Issue by naterex** [trizen/youtube-viewer#64]
Are videos to mp3 format above 128kbs possible?

**Comment by trizen** [comment]
Yes, of course. The `ffmpeg_command` can be modified to include any arguments that ffmpeg recognizes.

For example,  to convert videos to mp3 at 192kbps, replace inside the configuration file the value of `ffmpeg_command` with `"ffmpeg -i %s -y -vn -ac 2 -ab 192K -ar 48000 %s"`.
