### ISSUE TITLE
[Request] Automatically hide watched videos

### ISSUE THREAD

**Issue by Hund** [trizen/youtube-viewer#65]
This is a somewhat new feature in Kodi and I love it. It would be great to have this feature in youtube-viewer as well. :)

**Comment by trizen** [comment]
Gtk, CLI or both?

**Comment by Hund** [comment]
I use the cli version. I'm guessing I'm not the only one who would want this feature.

**Comment by trizen** [comment]
I think it's a nice feature too, but we also need an option to restore the hidden results (maybe a configurable option, like `:restore=3` to restore the last 3 hidden videos,  and a simply `:restore` which defaults to `1` (or all?)).

Another idea would be to mark a given video as watched by either underlining its title or render it some other color. What do you think about this?

P.S. I leave the computer only when I sleep. The cool thing is: I never sleep! :-)

**Comment by Hund** [comment]
In Kodi theres a option to toggle this feature. How about a option in the config to toggle this feature and a optional flag when you start the application in the terminal?

Colors are a nice option to. I dont use colors myself though. But I think it would be a popular feature.

I dont know much about coding, so I really dont know how much I'm asking for here. You should go do whatever you want to. I dont want to be that needy guy everyone hates. :D
