### ISSUE TITLE
Migration to APIv3 announcement!

### ISSUE THREAD

**Issue by trizen** [trizen/youtube-viewer#68]
This is an important announcement for every youtube-viewer user!

In about a month, youtube-viewer will start to use the YouTube APIv3. This process may result in loosing many of the current features and bringing in a lot of bugs. (I'm sorry)

I hope that, in the end, everything will work as smooth as it does today, but I can't promise this. So, let's enjoy youtube-viewer as much as possible in the time which is left.

http://youtube-eng.blogspot.ro/2014/03/committing-to-youtube-data-api-v3_4.html

**Comment by leoj3n** [comment]
:tada:

**Comment by trizen** [comment]
The migration to APIv3 has been a success and it now sits on the master branch, ready to be tested.

There are some features missing, as expected, but pretty much else works as before (bug-reports are welcome). Also, new dependencies had been introduced, such as: LWP::UserAgent::Cached, LWP::Protocol::https and JSON.

The features that are currently missing, will be implemented (slowly) in the future.
