### ISSUE TITLE
Bug when --results=10

### ISSUE THREAD

**Issue by kriskropd** [trizen/youtube-viewer#70]
With latest github build, I noticed when --results=10, the list of videos it procures does not begin with the latest video. Any other value used with --results seems to start with the most recent video (assuming default --order=date) however with a value of '10' it seems to only display videos uploaded prior to April 23rd. I'm suspicious that this could also be a local cache issue, somehow. I can't yet verify this at this moment, but I'll edit when I get the chance to.

**Comment by trizen** [comment]
It may be a cache issue. Try to delete `~/.cache/youtube-viewer` and try again. It works fine here.

**Comment by kriskropd** [comment]
So it was - I suspected it might be since I had aliased --result=10 with youtube-viewer in my ~/.bashrc. didn't think it would be in ~/.cache - tyvm

**Comment by trizen** [comment]
To avoid cache related issues in the future, a trick would be to set the config value of `cache_dir` to a volatile directory, such as `/tmp`.
