### ISSUE TITLE
did youtube block youtube-viewer?

### ISSUE THREAD

**Issue by shibumi** [trizen/youtube-viewer#71]
Hello,
I started youtube-viewer today after a couple of months and realized that youtube-viewer does not work anymore... Seems like youtube  changed its API or whatever.

when I search for a video I only get

```
1. https://youtube.com/devicesupport (by youtubehelp) (03:56)
```

I've heard that pvstar+ has the same at the moment but they get still search results after this first dummy-URL.

Version: YouTube Viewer 3.1.1

**Comment by trizen** [comment]
Hello shibumi,

The YouTube APIv2 (which was used in all version of youtube-viewer prior to 3.1.4) is no longer maintained by YouTube.

The solution is to update to the latest version of youtube-viewer.

**Comment by shibumi** [comment]
Wow that was fast! Awesome! thx
