### ISSUE TITLE
Respect HTTP Cache-Control

### ISSUE THREAD

**Issue by alexwh** [trizen/youtube-viewer#73]
Cache control is not respected for files in $XDG_CACHE_HOME/youtube-viewer - probably causing problems like #70

Example headers of a request that should never be cached to disk (edited for brevity):
```
https://www.googleapis.com/youtube/v3/playlistItems?key=redacted&maxResults=1&part=contentDetails,snippet&playlistId=redacted&prettyPrint=false
HTTP/1.1 200 OK
Cache-Control: private, max-age=0, must-revalidate, no-transform
ETag: "redacted"
[...]
```

And an image that should be cached for a specific time:
```
https://i.ytimg.com/vi/-YaohNgQcY8/mqdefault.jpg
HTTP/1.1 200 OK
Cache-Control: public, max-age=21600
Expires: Thu, 07 May 2015 03:06:49 GMT
Last-Modified: Thu, 01 Jan 1970 00:23:50 GMT
[...]
```

**Comment by trizen** [comment]
This issue is a must-fix. I will look into it as soon as possible. Thanks for the report.

**Comment by trizen** [comment]
Fixed here: https://github.com/trizen/youtube-viewer/commit/38649068926a02c6161fc23a94c9acaf0f309e38
