### ISSUE TITLE
Subscriptions loaded out of order

### ISSUE THREAD

**Issue by alexwh** [trizen/youtube-viewer#74]
When loading subscriptions in gtk-youtube-viewer, the order will be different to the proper order (as it is on the site)

youtube-viewer order:
![gtk-youtube-viewer order](http://i.imgur.com/XEziYaD.png)
Actual order:
![site order](http://i.imgur.com/FaLRBS2.png)

My default "order by" setting is set to "relevance", though changing it to "date" didn't change the results.
This doesn't seem to happen on any other playlist view (liked videos, uploads, etc)
(there also doesn't seem to be a "next page" button on subscriptions like there was in api v2)

**Comment by trizen** [comment]
This is a known issue, unfortunately. The APIv3 doesn't provide any way for retrieving the new subscription videos, yet. (see: https://code.google.com/p/gdata-issues/issues/detail?id=3946)

To overcome this problem, youtube-viewer uses a trick that just gets one video from each subscribed channel (up to maxResults). The order is: "unread" videos first.

More info at: https://github.com/trizen/youtube-viewer/blob/master/lib/WWW/YoutubeViewer/Subscriptions.pm#L63

**Comment by trizen** [comment]
The behavior of the "Subscriptions" button has been changed, which fixes this issue. See: https://github.com/trizen/youtube-viewer/commit/a075819d962731775da7f23af74a12e3372b8bc7
