### ISSUE TITLE
text file for following youtube channels

### ISSUE THREAD

**Issue by gotbletu** [trizen/youtube-viewer#8]
$ youtube-viewer -u=~/.config/youtube-viewer/youtube_users.txt 
                                                ~
Invalid url: http://gdata.youtube.com/feeds/api/users/~/.config/youtube-viewer/youtube_users.txt/uploads at /usr/share/perl5/site_perl/WWW/YoutubeViewer.pm line 438.
[400 Bad Request] Error occured on URL: http://gdata.youtube.com/feeds/api/users/~/.config/youtube-viewer/youtube_users.txt/uploads
Use of uninitialized value in subroutine entry at /usr/lib/perl5/vendor_perl/XML/Fast.pm line 28.
Empty document at /usr/lib/perl5/vendor_perl/XML/Fast.pm line 28.

---

Not sure what im missing, the old version allowed txt file, im guessing this option has been removed?

Arch XFCE
Kernel: 3.5.3-1-ARCH i686 (32 bit)

**Comment by trizen** [comment]
Option re-added in https://github.com/trizen/youtube-viewer/commit/5b82298ecb95829bf48c6efb61ca34dd76434053 as `-fc`.
