### ISSUE TITLE
No video streaming with latest update

### ISSUE THREAD

**Issue by CactusSoup** [trizen/youtube-viewer#80]
Gentoo package is out of date, uninstalled it and rebuilt using this source, logged out and logged back in to clear other issues.

I can no longer get this program to actually stream any video, subscriptions come up properly, selecting a number will bring up description and tags as normal, but instantly fail to play with no warning or error message.

-d will still download videos correctly, -dp will still download and then play videos correctly, but default options just bring up video information and will not play anything.

**Comment by trizen** [comment]
It may be a problem with `mplayer`.  Try to install `mpv` and change the value of `video_player_selected` to `mpv` and see if this fixes the issue.

See: https://github.com/trizen/config-files/blob/master/.config/youtube-viewer/youtube-viewer.conf#L51

**Comment by CactusSoup** [comment]
Done, no change.
Is there a way to make output more verbose?

**Comment by trizen** [comment]
To make the output verbose, remove the `--really-quiet` argument from `mpv`. (https://github.com/trizen/config-files/blob/master/.config/youtube-viewer/youtube-viewer.conf#L62)

**Comment by CactusSoup** [comment]
Ah, goodness me, turns out it was a problem with ffmpeg after all. It seems the gentoo youtube-viewer package didn't previously require https support in ffmpeg and that was what lead to the problem.

Thank you for your help and I'll go update the package.

(May I suggest a new option for troubleshooting which would temporarily turn off any quiet options in the config file)

**Comment by trizen** [comment]
No problem. For troubleshooting, there is `--debug=1` and `--debug=2`, but I will consider improving them in the future. Thanks!
