### ISSUE TITLE
Ubuntu compatibility (no LWP::UserAgent::Cached)

### ISSUE THREAD

**Issue by hotice** [trizen/youtube-viewer#84]
Hello,

I maintain Ubuntu packages for youtube-viewer in a PPA. Ubuntu (not even the latest 15.04) doesn't have LWP::UserAgent::Cached and since the old YouTube Viewer was using the YouTube API v2, it means neither the old or the latest version work. Would it be possible to tweak the app so that it doesn't need LWP::UserAgent::Cached somehow? Thanks!

**Comment by trizen** [comment]
Hello Andrew,

Thanks for maintaining the Ubuntu packages for youtube-viewer. Theoretically, it is possible to apply a patch so that `LWP::UserAgent::Cached` is no longer needed.

An way of doing this, is by substituting `LWP::UserAgent::Cached` with `LWP::UserAgent` anywhere inside `Build.PL` and `lib/WWW/YoutubeViewer.pm`.

**Comment by hotice** [comment]
Thanks! But before I do that, will this affect some of the application's functionality?

**Comment by trizen** [comment]
`LWP::UserAgent::Cached` is now optional. When it's not installed, `LWP::UserAgent` will be used instead. For performance reasons, it is recommended to have it installed, but when this is not possible, there will be no difference in functionality.

**Comment by hotice** [comment]
Thank you!

**Comment by trizen** [comment]
No problem. :)

**Comment by hotice** [comment]
I patched the app and when I search for X, then for Y, the X search results are still displayed and the Y results are displayed under X results in GTK YouTube Viewer. Also, each time I close the app I get a segmentation fault. Is this related somehow to not having ``LWP::UserAgent::Cached``?

**Comment by trizen** [comment]
The segmentation fault is from `Gtk2`, I guess. I got the same error under version 1.2492. Recently, I upgraded to 1.2495 and the segmentation fault seems to be gone.

About the search results being concatenated, it was meant to be a feature (maybe, a silly one). To deactivate it, just check the "Clear search list" option under the "More options" menu.

**Comment by hotice** [comment]
Everything is fine now, thank you!
