### ISSUE TITLE
[feature request] Playlist searching

### ISSUE THREAD

**Issue by Jookia** [trizen/youtube-viewer#91]
It'd be nice to be able to find a playlist a video is in or search for playlists

**Comment by trizen** [comment]
The "search for playlists" feature is already available.

usage: `youtube-viewer [kewords] -p`

**Comment by Jookia** [comment]
I don't see that in the GTK which doesn't really help users like me. It's also not in the stdin version either from what I can tell.

**Comment by trizen** [comment]
In the GTK version, this feature is available after checking "Playlists" in "Seach for:" menu (in Settings tab, just under the search entry).

In the stdin version, you can insert at any time `[keywords] -p` and it will search for playlists. Another related feature is `:p=i` which displays the playlists created by the author of video `i`.

**Comment by Jookia** [comment]
Oh, I hadn't noticed you could drop down that menu.
