### ISSUE TITLE
Fails when forking process to media player

### ISSUE THREAD

**Issue by gary9872** [trizen/youtube-viewer#94]
When youtube-viewer forks the process to vlc, mpv, mplayer is fails

Downloading however works fine.

http://pastebin.com/iYuUjqPz

Any suggestions greatly appreciated.

Gary

**Comment by trizen** [comment]
This is interesting. Which version actually fails: graphical or command-line? On what operating system? Thanks

**Comment by gary9872** [comment]
They both fail. Using 64 Bit Amd system on Gentoo Linux. Is the

**Comment by gary9872** [comment]
From what I can tell in the past youtube-viewer has requested/received http, rather than https:/

To that end I recompiled ffmpeg with ssl support. ( for mpv and mplayer)
and vlc with gnutls support

mpv  now works fine.
mplayer doesn't work. I'm assuming it won't because it lacks ssl support in the stable version. 
vlc if i copy the link from the video info dialogue it plays fine. But it I allow youtube-viewer to play it it complains it can't play the video.

**Comment by gary9872** [comment]
Going to mark this as resolved... VLC seems to have an issue with some https outside of youtube-viewer for me as well.
