### ISSUE TITLE
Invalid key 

### ISSUE THREAD

**Issue by zenny** [trizen/youtube-viewer#96]
Installed youtube-viewer from the source as well as ubuntu ppa in 14.04, but in both instances it pops up the the error that says:

"Invalid key: 'cache_dir' at /usr/local/share/perl/5.18.2/WWW/YoutubeViewer.pm line 151.
Invalid key: 'youtube_url_format' at /usr/local/share/perl/5.18.2/WWW/YoutubeViewer/Utils.pm line 66.
Undefined subroutine &WWW::YoutubeViewer::set_maxResults called at /usr/bin/youtube-viewer line 1090."

**Comment by trizen** [comment]
There seems to be an old library of youtube-viewer installed previously which didn't get uninstalled.

Try to remove `/usr/local/share/perl/5.18.2/WWW/YoutubeViewer.pm` and `/usr/local/share/perl/5.18.2/WWW/YoutubeViewer`.

**Comment by zenny** [comment]
Thanks, trizen. It runs now, yet does not play any video from the list.

**Comment by trizen** [comment]
Any error?

**Comment by zenny** [comment]
None.

**Comment by zenny** [comment]
$ youtube-viewer justforlaughstv

 1. NEW,EPIC 1 HOUR Just for Laughs Gags Epic Collection !! 1 HOUR PART 63 (by UCesePYtn8nEjsBl6SG7-Q5Q) [01:02:22]
 2. Best of Just For Laughs Gags - Top Epic Old Man Pranks (by JustForLaughsTV) [07:50]
 3. Blip Standard Player   JustForLaughsTV Best Cats Pranks   Best of Just for Laughs Gags (by UCz46UGY9bwQdJZSSw2bcT_Q) [09:24]
 4. Virgin Mary Comes Alive Prank (by JustForLaughsTV) [01:28]
 5. Best Of Just For Laughs Gags - Marie-Pierre Top 10 (by JustForLaughsTV) [15:34]
 6. Just For Laughs: Gags - Season 9 - Episode 2 (by JustForLaughsTV) [22:13]
 7. Best of just for laughs part 4 - HQ 2 HOURS! (by 4038137045) [02:01:18]
 8. Statue comes to life By JustForLaughsTv (by TheGfeSquad) [01:40]
 9. Just for Laughs Gags 2014 Epic Collection !! 1 HOUR Complete HD! Enjoy to your fullest. (by pixelsystudios) [01:04:14]
10. Crazy Moving Van (by JustForLaughsTV) [01:23]
11. The bests of Just for Laughs 2012 & 2013 The Best Episode EVER!!! (by Joniel120) [20:56]
12. just for laughs tv,just for laughs gags videos,just for laughs gags,gags just for laughs new (by TheJustForLaughsGags) [02:00:54]
13. Scary Clown in a Real 3D TV Prank (by JustForLaughsTV) [01:13]
14. Heavy Hammer Prank (by JustForLaughsTV) [01:16]
15. Wife cheated on her husband. |Epic Fail|Smosh|Disney|PewDiePie|collegehumor|JustForLaughsTV (by UCm2_P-o5KNZ-toZuID0zgOQ) [12:39]
16. Best of Just For Laughs Gags 2012 part 18funniest videos (by TheJustForLaughsGags) [01:59:33]
17. Just For Laugh Gags top 10 funny prank 2014 (by DxBKhan1) [16:24]
18. Just for Laughs Gags (HD) New 2015 (by UC5DVtzM31ZakFOrwabFLz9Q) [01:02:38]
19. Groundhog Day Prank (by JustForLaughsTV) [01:16]
20. Dart In Back Prank (by JustForLaughsTV) [01:03]

=>> Select one or more videos to play (:h for help)
> 20

=>> Description
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
http://gags.justforlaughs.com | Subscribe! http://goo.gl/wJxjG Shoppers are asked to shoot a dart on a magic wheel of money but end up getting a poor man in the ...
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
* URL: http://www.youtube.com/watch?v=Cvu1HnAVuww
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                            =>> Dart In Back Prank <<=

-> Channel   : JustForLaughsTV
-> ChannelID : UCpsSadsgX_Qk9i6i_bJoUwQ
-> Definition: SD
-> Duration  : 01:03
-> Likes     : 152
-> Dislikes  : 26
-> Comments  : 35
-> Views     : 78,621
-> Published : 06 May 2011
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 1. NEW,EPIC 1 HOUR Just for Laughs Gags Epic Collection !! 1 HOUR PART 63 (by UCesePYtn8nEjsBl6SG7-Q5Q) [01:02:22]
 2. Best of Just For Laughs Gags - Top Epic Old Man Pranks (by JustForLaughsTV) [07:50]
 3. Blip Standard Player   JustForLaughsTV Best Cats Pranks   Best of Just for Laughs Gags (by UCz46UGY9bwQdJZSSw2bcT_Q) [09:24]
 4. Virgin Mary Comes Alive Prank (by JustForLaughsTV) [01:28]
 5. Best Of Just For Laughs Gags - Marie-Pierre Top 10 (by JustForLaughsTV) [15:34]
 6. Just For Laughs: Gags - Season 9 - Episode 2 (by JustForLaughsTV) [22:13]
 7. Best of just for laughs part 4 - HQ 2 HOURS! (by 4038137045) [02:01:18]
 8. Statue comes to life By JustForLaughsTv (by TheGfeSquad) [01:40]
 9. Just for Laughs Gags 2014 Epic Collection !! 1 HOUR Complete HD! Enjoy to your fullest. (by pixelsystudios) [01:04:14]
10. Crazy Moving Van (by JustForLaughsTV) [01:23]
11. The bests of Just for Laughs 2012 & 2013 The Best Episode EVER!!! (by Joniel120) [20:56]
12. just for laughs tv,just for laughs gags videos,just for laughs gags,gags just for laughs new (by TheJustForLaughsGags) [02:00:54]
13. Scary Clown in a Real 3D TV Prank (by JustForLaughsTV) [01:13]
14. Heavy Hammer Prank (by JustForLaughsTV) [01:16]
15. Wife cheated on her husband. |Epic Fail|Smosh|Disney|PewDiePie|collegehumor|JustForLaughsTV (by UCm2_P-o5KNZ-toZuID0zgOQ) [12:39]
16. Best of Just For Laughs Gags 2012 part 18funniest videos (by TheJustForLaughsGags) [01:59:33]
17. Just For Laugh Gags top 10 funny prank 2014 (by DxBKhan1) [16:24]
18. Just for Laughs Gags (HD) New 2015 (by UC5DVtzM31ZakFOrwabFLz9Q) [01:02:38]
19. Groundhog Day Prank (by JustForLaughsTV) [01:16]
20. Dart In Back Prank (by JustForLaughsTV) [01:03]

=>> Select one or more videos to play (:h for help)
>

**Comment by trizen** [comment]
Which player is selected inside the configuration file?

**Comment by trizen** [comment]
Try this to check for codec problems: `mpv $(youtube-viewer -no-interactive --no-dash --extract '*VIDEO*' 'http://www.youtube.com/watch?v=Cvu1HnAVuww')` (replace `mpv` with `vlc` if you're using VLC)

If the video plays correctly, try to remove the configuration file of youtube-viewer: `~/.config/youtube-viewer/youtube-viewer.conf`

**Comment by zenny** [comment]
It plays alright with:

mpv $(youtube-viewer -no-interactive --no-dash --extract '*VIDEO*' 'http://www.youtube.com/watch?v=Cvu1HnAVuww')

But, the problem remained the same even after removing ~/.config/youtube-viewer/youtube-viewer.conf

**Comment by trizen** [comment]
Modify the configuration file to include the following:

```perl
  video_player_selected   => "mpv",
  video_players           => {
                               mpv => {
                                 arg => "--really-quiet --title *TITLE*",
                                 audio => "--audio-file *AUDIO*",
                                 cmd => "mpv",
                                 fs => "--fullscreen",
                                 novideo => "--no-video",
                                 srt => "--sub-file *SUB*",
                               },
                             },
```

For further debugging, run youtube-viewer with the `--debug` argument and also try to removed the `--really-quiet` argument from mpv to see what's really going on behind the scenes.

**Comment by trizen** [comment]
Also, in order to play videos with encrypted signatures, `youtube-dl` is required. Otherwise, it simply fails silently.

**Comment by zenny** [comment]
Thanks, trizen, after appending the configuration file, it works find.

**Comment by trizen** [comment]
No problem. I'm glad you got it working. ;)
