### ISSUE TITLE
Playlists in search result not playing

### ISSUE THREAD

**Issue by eNTi** [trizen/youtube-viewer#97]
trying to start any youtube playlist silently fails... no idea why but the url of the playlists clearly shows the playlist itself and not the video site that actually plays the songs.

**Comment by trizen** [comment]
Can you provide an example?

**Comment by eNTi** [comment]
searching for "Melodic Death Metal playlist 2014 / 2015" gives you https://www.youtube.com/playlist?list=PLfDNq6JIpILwL-R6gXb30g6pcKPZnowWl which is just the list of songs and youtube-viewer doesn't know what to do with that url.
you really want https://www.youtube.com/watch?v=YvAOk-M_MiM&list=PLfDNq6JIpILwL-R6gXb30g6pcKPZnowWl

**Comment by trizen** [comment]
To play a given playlist, there is the `-pp=ID` option:
```
youtube-viewer --pp 'PLfDNq6JIpILwL-R6gXb30g6pcKPZnowWl'
```

or to list a given playlist in youtube-viewer, we have `-p=ID`:
```
youtube-viewer -p 'PLfDNq6JIpILwL-R6gXb30g6pcKPZnowWl'
```

Does this solves the issue?

**Comment by eNTi** [comment]
not really, because i'm trying to use the gui.

**Comment by trizen** [comment]
This is possible as well.

See the attached screenshot:
![2015-08-05-125115_1920x1080_scrot](https://cloud.githubusercontent.com/assets/614513/9083160/63e0105e-3b71-11e5-9032-414ce0fd4145.png)

Instructions:
- select `Playlists` from the `Search for:` menu
- search for `Melodic Death Metal playlist 2014 / 2015`
- double-click the first result
- bellow it will display the videos from that playlists which can be played by double-clicking them

**Comment by eNTi** [comment]
but it can't play the playlist automatically? it's not really useful if i have to click on each song separately.

**Comment by eNTi** [comment]
awesome! :)

**Comment by trizen** [comment]
Added support to right-click a given playlist and select `Play this video in a terminal` and will play all videos from that playlists in a new terminal, using youtube-viewer.

**Comment by eNTi** [comment]
just tried it, but it doesn't work. i've seen that you are the maintainer of the aur package. could you probably rename "gtk-youtube-viewer" package to "gtk-youtube-viewer-git"?

**Comment by onedrawingperday** [comment]
Thank you @trizen 

This works for me on Ubuntu Gnome 16.04  However I have set VLC as my default video player and when I click "Run in Terminal" the playlist videos open with MPV.

Is there a way to fix this?

**Comment by trizen** [comment]
@onedrawingperday - the CLI version of youtube-viewer uses a different configuration file, so you will have to set VLC as the default player in `~/.config/youtube-viewer/youtube-viewer.conf` as well.

In addition to this, starting with version 3.2.4, we can specify command-line arguments to the instance of CLI youtube-viewer that is executed by gtk-youtube-viewer (in `~/.config/youtube-viewer/gtk-youtube-viewer.conf`):

```perl
youtube_viewer_args  => ['--player=vlc'],
```

**Comment by trizen** [comment]
@eNTi make sure the value of `terminal_format` is correct for the selected terminal.

See also: https://github.com/trizen/youtube-viewer/issues/158

I'm closing this now, as the feature works as expected with a correct terminal configuration.
