### ISSUE TITLE
No sound with ogg

### ISSUE THREAD

**Issue by solarlodge** [trizen/youtube-viewer#98]
I run the current version from github on Debian Jessie. Some videos appear to play without sound. The --debug told me that it's reproducable when:
-> Video type: video/webm;+codecs="vp9"
-> Audio type: audio/webm;+codecs="vorbis"
Strange thing is that these videos are playable when i hand over the video url directly to mpv. Tried other players as well - they refuse to play the videos completely. Videos with other audio encoding work well.

**Comment by trizen** [comment]
This is a codec problem.
