### ISSUE TITLE
videos not playing in vlc

### ISSUE THREAD

**Issue by mrfricks** [trizen/youtube-viewer#99]
hi trizen,

i'm trying to get the latest gtk-youttube-viewer working in puppylinux (tahrpup) with vlc.
clicking on a link causes vlc to open and then immediately close.
i've seen your comments on the closed issue here https://github.com/trizen/youtube-viewer/issues/96 and tried 
```
vlc $(youtube-viewer --no-interactive --no-dash --extract '*VIDEO*' 'http://www.youtube.com/watch?v=Cvu1HnAVuww')
```
which works fine.
removing youtube-viewer.conf didn't help.

any suggestions?
cheers

**Comment by trizen** [comment]
Hi,

I will investigate tomorrow this issue in detail. Meanwhile, make sure the version of vlc you're using is new enough (>2.1.*) and also try to remove `gtk-youtube-viewer.conf` as well.

**Comment by trizen** [comment]
I can't confirm the issue with VLC 2.2.1.

Make sure you have in the configuration file (`~/.config/youtube-viewer/gtk-youtube-viewer.conf`) the following entries:

```perl
  video_player_selected         => "vlc",
  video_players                 => {
                                     vlc => {
                                       arg   => "--quiet --play-and-exit --no-video-title-show --input-title-format *TITLE*",
                                       audio => "--input-slave *AUDIO*",
                                       cmd   => "vlc",
                                       fs    => "--fullscreen",
                                       srt   => "--sub-file *SUB*",
                                     },
                                    },
```

**Comment by mrfricks** [comment]
hi trizen,

i can confirm that it is a problem with the default vlc that comes with tahrpup ..2.1.4 rincewind.
vlc 2.2.0 is working fine, even with the default config

i'll see if i can get 2.1.4 working. tahrpup might be missing a plugin or something.
i'll close this but post back if i figure it out.

thankyou for your time
